; Tile index $000
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $001
.db $F7 $30 $F7 $DF $F7 $30 $F7 $FF $F7 $30 $F7 $FF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $002
.db $EB $28 $EB $D7 $EB $28 $EB $FF $C3 $00 $C3 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $003
.db $EB $28 $EB $D7 $FD $7C $FD $FF $FD $7C $FD $FF $A9 $28 $A9 $D7 $FD $7C $FD $83 $A9 $28 $A9 $D7 $C3 $00 $C3 $FF $FF $00 $FF $FF
; Tile index $004
.db $EB $28 $EB $D7 $FD $7C $FD $FF $E9 $E8 $E9 $FF $7D $7C $7D $83 $AE $2E $AE $D1 $FC $7C $FC $83 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $005
.db $EE $E6 $EE $7F $AC $AC $AC $FF $F9 $F8 $F9 $FF $3E $3E $3E $C1 $EA $6A $EA $95 $CE $CE $CE $31 $10 $00 $10 $FF $FF $00 $FF $FF
; Tile index $006
.db $FB $F8 $FB $7F $C3 $C0 $C3 $FF $6D $6C $6D $FF $B9 $B8 $B9 $47 $9D $9C $9D $63 $76 $76 $76 $89 $80 $00 $80 $FF $FF $00 $FF $FF
; Tile index $007
.db $FB $18 $FB $EF $F3 $30 $F3 $FF $E7 $20 $E7 $FF $CF $00 $CF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $008
.db $FB $18 $FB $EF $FB $38 $FB $FF $F3 $30 $F3 $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $DB $18 $DB $E7 $E3 $00 $E3 $FF $FF $00 $FF $FF
; Tile index $009
.db $F7 $30 $F7 $DF $FB $38 $FB $FF $DB $18 $DB $FF $FB $18 $FB $E7 $FB $18 $FB $E7 $F3 $30 $F3 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $00A
.db $FF $00 $FF $FF $F7 $10 $F7 $EF $D5 $54 $D5 $FF $B9 $38 $B9 $C7 $D5 $54 $D5 $AB $91 $10 $91 $EF $E7 $00 $E7 $FF $FF $00 $FF $FF
; Tile index $00B
.db $FF $00 $FF $FF $F7 $10 $F7 $EF $F7 $10 $F7 $FF $FD $7C $FD $83 $91 $10 $91 $EF $F7 $10 $F7 $EF $E7 $00 $E7 $FF $FF $00 $FF $FF
; Tile index $00C
.db $FF $00 $FF $FF $FF $00 $FF $FF $F7 $30 $F7 $DF $F7 $30 $F7 $CF $D7 $10 $D7 $EF $E7 $20 $E7 $DF $CF $00 $CF $FF $FF $00 $FF $FF
; Tile index $00D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FD $7C $FD $83 $81 $00 $81 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $00E
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $00F
.db $FE $06 $FE $FB $FC $0C $FC $FF $F9 $18 $F9 $FF $F3 $30 $F3 $CF $E7 $60 $E7 $9F $CF $C0 $CF $3F $1F $00 $1F $FF $FF $00 $FF $FF
; Tile index $010
.db $FB $78 $FB $BF $FD $FC $FD $FF $CD $CC $CD $FF $DD $CC $DD $33 $DD $CC $DD $33 $79 $78 $79 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $011
.db $FB $78 $FB $BF $FB $78 $FB $FF $9B $18 $9B $FF $FB $18 $FB $E7 $FB $18 $FB $E7 $FB $18 $FB $E7 $E3 $00 $E3 $FF $FF $00 $FF $FF
; Tile index $012
.db $FB $F8 $FB $7F $FD $FC $FD $FF $0D $0C $0D $FF $F9 $18 $F9 $E7 $F3 $30 $F3 $CF $FD $7C $FD $83 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $013
.db $FB $F8 $FB $7F $FD $FC $FD $FF $0D $0C $0D $FF $F9 $38 $F9 $C7 $CD $0C $CD $F3 $F9 $78 $F9 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $014
.db $FB $38 $FB $DF $FB $78 $FB $FF $FB $78 $FB $FF $CB $C8 $CB $37 $FD $FC $FD $03 $19 $18 $19 $E7 $E3 $00 $E3 $FF $FF $00 $FF $FF
; Tile index $015
.db $FD $FC $FD $7F $FD $FC $FD $FF $E1 $E0 $E1 $FF $7B $78 $7B $87 $8D $0C $8D $F3 $F9 $78 $F9 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $016
.db $FB $78 $FB $BF $C3 $C0 $C3 $FF $FB $F8 $FB $FF $FD $FC $FD $03 $8D $8C $8D $73 $79 $78 $79 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $017
.db $FD $FC $FD $7F $FD $FC $FD $FF $09 $08 $09 $FF $FB $18 $FB $E7 $F3 $30 $F3 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $018
.db $FB $78 $FB $BF $FD $FC $FD $FF $CD $CC $CD $FF $79 $78 $79 $87 $CD $CC $CD $33 $79 $78 $79 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $019
.db $FB $78 $FB $BF $FD $FC $FD $FF $CD $CC $CD $FF $7D $7C $7D $83 $89 $08 $89 $F7 $F3 $30 $F3 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $01A
.db $F7 $30 $F7 $DF $F7 $30 $F7 $FF $C7 $00 $C7 $FF $FF $00 $FF $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $01B
.db $F7 $30 $F7 $DF $F7 $30 $F7 $FF $C7 $00 $C7 $FF $F7 $30 $F7 $CF $D7 $10 $D7 $EF $E7 $20 $E7 $DF $CF $00 $CF $FF $FF $00 $FF $FF
; Tile index $01C
.db $FB $18 $FB $EF $FB $38 $FB $FF $F3 $30 $F3 $FF $E7 $60 $E7 $9F $B7 $30 $B7 $CF $DB $18 $DB $E7 $E3 $00 $E3 $FF $FF $00 $FF $FF
; Tile index $01D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FD $7C $FD $BF $81 $00 $81 $FF $FD $7C $FD $83 $81 $00 $81 $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $01E
.db $EF $60 $EF $BF $F7 $70 $F7 $FF $B7 $30 $B7 $FF $DB $18 $DB $E7 $F3 $30 $F3 $CF $E7 $60 $E7 $9F $8F $00 $8F $FF $FF $00 $FF $FF
; Tile index $01F
.db $FD $FC $FD $7F $CD $CC $CD $FF $1D $0C $1D $FF $F1 $30 $F1 $CF $C7 $00 $C7 $FF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $020
.db $FB $78 $FB $BF $FD $FC $FD $FF $D5 $D4 $D5 $FF $DD $DC $DD $23 $C1 $C0 $C1 $3F $7B $78 $7B $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $021
.db $FB $38 $FB $DF $FD $7C $FD $FF $ED $6C $ED $FF $CD $CC $CD $33 $FD $FC $FD $03 $8D $8C $8D $73 $31 $00 $31 $FF $FF $00 $FF $FF
; Tile index $022
.db $FB $F8 $FB $7F $FD $FC $FD $FF $CD $CC $CD $FF $F9 $F8 $F9 $07 $CD $CC $CD $33 $F9 $F8 $F9 $07 $03 $00 $03 $FF $FF $00 $FF $FF
; Tile index $023
.db $FD $7C $FD $BF $FD $FC $FD $FF $C1 $C0 $C1 $FF $DF $C0 $DF $3F $DF $C0 $DF $3F $7B $78 $7B $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $024
.db $FB $F8 $FB $7F $FD $FC $FD $FF $CD $CC $CD $FF $DD $CC $DD $33 $DD $CC $DD $33 $F9 $F8 $F9 $07 $03 $00 $03 $FF $FF $00 $FF $FF
; Tile index $025
.db $FD $FC $FD $7F $FD $FC $FD $FF $C1 $C0 $C1 $FF $FB $F8 $FB $07 $C3 $C0 $C3 $3F $FB $F8 $FB $07 $03 $00 $03 $FF $FF $00 $FF $FF
; Tile index $026
.db $FD $FC $FD $7F $FD $FC $FD $FF $C1 $C0 $C1 $FF $FB $F8 $FB $07 $C3 $C0 $C3 $3F $DF $C0 $DF $3F $1F $00 $1F $FF $FF $00 $FF $FF
; Tile index $027
.db $FD $7C $FD $BF $FD $FC $FD $FF $C1 $C0 $C1 $FF $DD $CC $DD $33 $DD $CC $DD $33 $7D $7C $7D $83 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $028
.db $DD $CC $DD $77 $DD $CC $DD $FF $DD $CC $DD $FF $FD $FC $FD $03 $CD $CC $CD $33 $DD $CC $DD $33 $11 $00 $11 $FF $FF $00 $FF $FF
; Tile index $029
.db $F7 $30 $F7 $DF $F7 $30 $F7 $FF $F7 $30 $F7 $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $02A
.db $FD $0C $FD $F7 $FD $0C $FD $FF $FD $0C $FD $FF $FD $0C $FD $F3 $ED $6C $ED $93 $F9 $78 $F9 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $02B
.db $DD $CC $DD $77 $DD $DC $DD $FF $F9 $F8 $F9 $FF $F3 $F0 $F3 $0F $DB $D8 $DB $27 $CD $CC $CD $33 $11 $00 $11 $FF $FF $00 $FF $FF
; Tile index $02C
.db $EF $60 $EF $BF $EF $60 $EF $FF $EF $60 $EF $FF $EF $60 $EF $9F $EF $60 $EF $9F $FB $78 $FB $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $02D
.db $BE $8E $BE $77 $DE $DE $DE $FF $FE $FE $FE $FF $F6 $F6 $F6 $09 $A6 $A6 $A6 $59 $8E $86 $8E $79 $38 $00 $38 $FF $FF $00 $FF $FF
; Tile index $02E
.db $DD $CC $DD $7F $ED $EC $ED $FF $FD $FC $FD $FF $BD $BC $BD $43 $9D $9C $9D $63 $AD $8C $AD $73 $31 $00 $31 $FF $FF $00 $FF $FF
; Tile index $02F
.db $FD $7C $FD $BF $FE $FE $FE $FF $C6 $C6 $C6 $FF $DE $C6 $DE $39 $DE $C6 $DE $39 $7C $7C $7C $83 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $030
.db $FB $F8 $FB $7F $FD $FC $FD $FF $CD $CC $CD $FF $DD $CC $DD $33 $F9 $F8 $F9 $07 $C3 $C0 $C3 $3F $1F $00 $1F $FF $FF $00 $FF $FF
; Tile index $031
.db $FD $7C $FD $BF $FE $FE $FE $FF $C6 $C6 $C6 $FF $DE $C6 $DE $39 $DC $CC $DC $33 $7E $7E $7E $81 $80 $00 $80 $FF $FF $00 $FF $FF
; Tile index $032
.db $FB $F8 $FB $7F $FD $FC $FD $FF $CD $CC $CD $FF $D9 $C8 $D9 $37 $FB $F8 $FB $07 $CD $CC $CD $33 $11 $00 $11 $FF $FF $00 $FF $FF
; Tile index $033
.db $FD $7C $FD $BF $FD $FC $FD $FF $E1 $E0 $E1 $FF $7B $78 $7B $87 $9D $1C $9D $E3 $F9 $78 $F9 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $034
.db $FD $FC $FD $7F $FD $FC $FD $FF $31 $30 $31 $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $035
.db $DD $CC $DD $7F $DD $CC $DD $FF $DD $CC $DD $FF $DD $CC $DD $33 $DD $CC $DD $33 $79 $78 $79 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $036
.db $DD $CC $DD $7F $DD $CC $DD $FF $59 $48 $59 $FF $FB $78 $FB $87 $B3 $30 $B3 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $037
.db $DE $C6 $DE $7F $D6 $D6 $D6 $FF $D6 $D6 $D6 $FF $7C $7C $7C $83 $FD $7C $FD $83 $A9 $28 $A9 $D7 $C3 $00 $C3 $FF $FF $00 $FF $FF
; Tile index $038
.db $DD $CC $DD $7F $DD $CC $DD $FF $79 $78 $79 $FF $B3 $30 $B3 $CF $FB $78 $FB $87 $CD $CC $CD $33 $11 $00 $11 $FF $FF $00 $FF $FF
; Tile index $039
.db $DD $CC $DD $7F $DD $CC $DD $FF $DD $CC $DD $FF $79 $78 $79 $87 $B3 $30 $B3 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $03A
.db $FD $FC $FD $7F $FD $FC $FD $FF $19 $18 $19 $FF $F3 $30 $F3 $CF $E7 $60 $E7 $9F $FB $F8 $FB $07 $03 $00 $03 $FF $FF $00 $FF $FF
; Tile index $03B
.db $FB $38 $FB $DF $FB $38 $FB $FF $F3 $30 $F3 $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $FB $38 $FB $C7 $C3 $00 $C3 $FF $FF $00 $FF $FF
; Tile index $03C
.db $DF $C0 $DF $7F $6F $60 $6F $FF $B7 $30 $B7 $FF $DB $18 $DB $E7 $ED $0C $ED $F3 $F6 $06 $F6 $F9 $F8 $00 $F8 $FF $FF $00 $FF $FF
; Tile index $03D
.db $FB $38 $FB $DF $FB $38 $FB $FF $DB $18 $DB $FF $FB $18 $FB $E7 $FB $18 $FB $E7 $FB $38 $FB $C7 $C3 $00 $C3 $FF $FF $00 $FF $FF
; Tile index $03E
.db $FB $18 $FB $EF $F3 $30 $F3 $FF $E7 $20 $E7 $FF $CF $00 $CF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $03F
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FD $7C $FD $83 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $040
.db $FB $18 $FB $EF $F3 $30 $F3 $FF $E7 $20 $E7 $FF $CF $00 $CF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $041
.db $FF $00 $FF $FF $FB $78 $FB $BF $8D $0C $8D $FF $FD $7C $FD $83 $CD $CC $CD $33 $7D $7C $7D $83 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $042
.db $DF $C0 $DF $7F $DF $C0 $DF $FF $FB $F8 $FB $FF $FD $FC $FD $03 $CD $CC $CD $33 $F9 $F8 $F9 $07 $03 $00 $03 $FF $FF $00 $FF $FF
; Tile index $043
.db $FF $00 $FF $FF $FD $7C $FD $BF $FD $FC $FD $FF $C1 $C0 $C1 $3F $DF $C0 $DF $3F $7B $78 $7B $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $044
.db $FD $0C $FD $F7 $FD $0C $FD $FF $FD $7C $FD $FF $FD $FC $FD $03 $C5 $C4 $C5 $3B $7D $7C $7D $83 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $045
.db $FF $00 $FF $FF $FB $78 $FB $BF $CD $CC $CD $FF $FD $FC $FD $03 $C1 $C0 $C1 $3F $7B $78 $7B $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $046
.db $FD $1C $FD $EF $FD $3C $FD $FF $F1 $30 $F1 $FF $FD $7C $FD $83 $B1 $30 $B1 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $047
.db $FD $7C $FD $BF $FD $FC $FD $FF $CD $CC $CD $FF $7D $7C $7D $83 $8D $0C $8D $F3 $F9 $78 $F9 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $048
.db $EF $60 $EF $BF $EF $60 $EF $FF $FB $78 $FB $FF $FD $7C $FD $83 $CD $4C $CD $B3 $DD $4C $DD $B3 $91 $00 $91 $FF $FF $00 $FF $FF
; Tile index $049
.db $F7 $30 $F7 $DF $C7 $00 $C7 $FF $F7 $30 $F7 $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $04A
.db $FB $18 $FB $EF $E3 $00 $E3 $FF $FB $18 $FB $FF $FB $18 $FB $E7 $DB $58 $DB $A7 $F3 $70 $F3 $8F $87 $00 $87 $FF $FF $00 $FF $FF
; Tile index $04B
.db $DF $C0 $DF $7F $DD $CC $DD $FF $DD $DC $DD $FF $F9 $F8 $F9 $07 $F3 $F0 $F3 $0F $CD $CC $CD $33 $11 $00 $11 $FF $FF $00 $FF $FF
; Tile index $04C
.db $F7 $30 $F7 $DF $F7 $30 $F7 $FF $F7 $30 $F7 $FF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $F7 $30 $F7 $CF $C7 $00 $C7 $FF $FF $00 $FF $FF
; Tile index $04D
.db $FF $00 $FF $FF $ED $EC $ED $7F $FE $FE $FE $FF $D6 $D6 $D6 $29 $D6 $D6 $D6 $29 $D6 $D6 $D6 $29 $00 $00 $00 $FF $FF $00 $FF $FF
; Tile index $04E
.db $FF $00 $FF $FF $FB $F8 $FB $7F $FD $FC $FD $FF $8D $8C $8D $73 $BD $8C $BD $73 $BD $8C $BD $73 $31 $00 $31 $FF $FF $00 $FF $FF
; Tile index $04F
.db $FF $00 $FF $FF $FB $78 $FB $BF $FD $FC $FD $FF $CD $CC $CD $33 $DD $CC $DD $33 $79 $78 $79 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $050
.db $FF $00 $FF $FF $FB $F8 $FB $7F $FD $FC $FD $FF $CD $CC $CD $33 $F9 $F8 $F9 $07 $C3 $C0 $C3 $3F $1F $00 $1F $FF $FF $00 $FF $FF
; Tile index $051
.db $FF $00 $FF $FF $FD $7C $FD $BF $FD $FC $FD $FF $CD $CC $CD $33 $7D $7C $7D $83 $8D $0C $8D $F3 $F1 $00 $F1 $FF $FF $00 $FF $FF
; Tile index $052
.db $FF $00 $FF $FF $ED $6C $ED $BF $ED $6C $ED $FF $F1 $70 $F1 $8F $E7 $60 $E7 $9F $EF $60 $EF $9F $8F $00 $8F $FF $FF $00 $FF $FF
; Tile index $053
.db $FF $00 $FF $FF $FD $7C $FD $BF $FD $FC $FD $FF $61 $60 $61 $9F $BB $38 $BB $C7 $F3 $F0 $F3 $0F $07 $00 $07 $FF $FF $00 $FF $FF
; Tile index $054
.db $F7 $30 $F7 $DF $FD $7C $FD $FF $FD $7C $FD $FF $B1 $30 $B1 $CF $F7 $30 $F7 $CF $DB $18 $DB $E7 $E3 $00 $E3 $FF $FF $00 $FF $FF
; Tile index $055
.db $FF $00 $FF $FF $DB $D8 $DB $7F $DB $D8 $DB $FF $DB $D8 $DB $27 $DB $D8 $DB $27 $6D $6C $6D $93 $81 $00 $81 $FF $FF $00 $FF $FF
; Tile index $056
.db $FF $00 $FF $FF $ED $6C $ED $BF $ED $6C $ED $FF $ED $6C $ED $93 $B9 $38 $B9 $C7 $D3 $10 $D3 $EF $E7 $00 $E7 $FF $FF $00 $FF $FF
; Tile index $057
.db $FF $00 $FF $FF $DE $C6 $DE $7F $D6 $D6 $D6 $FF $D6 $D6 $D6 $29 $7C $7C $7C $83 $A9 $28 $A9 $D7 $C3 $00 $C3 $FF $FF $00 $FF $FF
; Tile index $058
.db $FF $00 $FF $FF $DD $CC $DD $7F $DD $CC $DD $FF $79 $78 $79 $87 $B3 $30 $B3 $CF $CD $CC $CD $33 $11 $00 $11 $FF $FF $00 $FF $FF
; Tile index $059
.db $FF $00 $FF $FF $DD $CC $DD $77 $DD $CC $DD $FF $7D $7C $7D $83 $8D $0C $8D $F3 $F9 $78 $F9 $87 $83 $00 $83 $FF $FF $00 $FF $FF
; Tile index $05A
.db $FF $00 $FF $FF $FD $FC $FD $7F $F9 $F8 $F9 $FF $33 $30 $33 $CF $E7 $60 $E7 $9F $FB $F8 $FB $07 $03 $00 $03 $FF $FF $00 $FF $FF
