; Tile index $000
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $001
.db $30 $30 $F7 $DF $30 $30 $F7 $FF $30 $30 $F7 $FF $30 $30 $F7 $CF $00 $00 $C7 $FF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $002
.db $28 $28 $EB $D7 $28 $28 $EB $FF $00 $00 $C3 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $003
.db $28 $28 $EB $D7 $7C $7C $FD $FF $7C $7C $FD $FF $28 $28 $A9 $D7 $7C $7C $FD $83 $28 $28 $A9 $D7 $00 $00 $C3 $FF $00 $00 $FF $FF
; Tile index $004
.db $28 $28 $EB $D7 $7C $7C $FD $FF $E8 $E8 $E9 $FF $7C $7C $7D $83 $2E $2E $AE $D1 $7C $7C $FC $83 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $005
.db $E6 $E6 $EE $7F $AC $AC $AC $FF $F8 $F8 $F9 $FF $3E $3E $3E $C1 $6A $6A $EA $95 $CE $CE $CE $31 $00 $00 $10 $FF $00 $00 $FF $FF
; Tile index $006
.db $F8 $F8 $FB $7F $C0 $C0 $C3 $FF $6C $6C $6D $FF $B8 $B8 $B9 $47 $9C $9C $9D $63 $76 $76 $76 $89 $00 $00 $80 $FF $00 $00 $FF $FF
; Tile index $007
.db $18 $18 $FB $EF $30 $30 $F3 $FF $20 $20 $E7 $FF $00 $00 $CF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $008
.db $18 $18 $FB $EF $38 $38 $FB $FF $30 $30 $F3 $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $18 $18 $DB $E7 $00 $00 $E3 $FF $00 $00 $FF $FF
; Tile index $009
.db $30 $30 $F7 $DF $38 $38 $FB $FF $18 $18 $DB $FF $18 $18 $FB $E7 $18 $18 $FB $E7 $30 $30 $F3 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $00A
.db $00 $00 $FF $FF $10 $10 $F7 $EF $54 $54 $D5 $FF $38 $38 $B9 $C7 $54 $54 $D5 $AB $10 $10 $91 $EF $00 $00 $E7 $FF $00 $00 $FF $FF
; Tile index $00B
.db $00 $00 $FF $FF $10 $10 $F7 $EF $10 $10 $F7 $FF $7C $7C $FD $83 $10 $10 $91 $EF $10 $10 $F7 $EF $00 $00 $E7 $FF $00 $00 $FF $FF
; Tile index $00C
.db $00 $00 $FF $FF $00 $00 $FF $FF $30 $30 $F7 $DF $30 $30 $F7 $CF $10 $10 $D7 $EF $20 $20 $E7 $DF $00 $00 $CF $FF $00 $00 $FF $FF
; Tile index $00D
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $7C $7C $FD $83 $00 $00 $81 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $00E
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $00F
.db $06 $06 $FE $FB $0C $0C $FC $FF $18 $18 $F9 $FF $30 $30 $F3 $CF $60 $60 $E7 $9F $C0 $C0 $CF $3F $00 $00 $1F $FF $00 $00 $FF $FF
; Tile index $010
.db $78 $78 $FB $BF $FC $FC $FD $FF $CC $CC $CD $FF $CC $CC $DD $33 $CC $CC $DD $33 $78 $78 $79 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $011
.db $78 $78 $FB $BF $78 $78 $FB $FF $18 $18 $9B $FF $18 $18 $FB $E7 $18 $18 $FB $E7 $18 $18 $FB $E7 $00 $00 $E3 $FF $00 $00 $FF $FF
; Tile index $012
.db $F8 $F8 $FB $7F $FC $FC $FD $FF $0C $0C $0D $FF $18 $18 $F9 $E7 $30 $30 $F3 $CF $7C $7C $FD $83 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $013
.db $F8 $F8 $FB $7F $FC $FC $FD $FF $0C $0C $0D $FF $38 $38 $F9 $C7 $0C $0C $CD $F3 $78 $78 $F9 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $014
.db $38 $38 $FB $DF $78 $78 $FB $FF $78 $78 $FB $FF $C8 $C8 $CB $37 $FC $FC $FD $03 $18 $18 $19 $E7 $00 $00 $E3 $FF $00 $00 $FF $FF
; Tile index $015
.db $FC $FC $FD $7F $FC $FC $FD $FF $E0 $E0 $E1 $FF $78 $78 $7B $87 $0C $0C $8D $F3 $78 $78 $F9 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $016
.db $78 $78 $FB $BF $C0 $C0 $C3 $FF $F8 $F8 $FB $FF $FC $FC $FD $03 $8C $8C $8D $73 $78 $78 $79 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $017
.db $FC $FC $FD $7F $FC $FC $FD $FF $08 $08 $09 $FF $18 $18 $FB $E7 $30 $30 $F3 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $018
.db $78 $78 $FB $BF $FC $FC $FD $FF $CC $CC $CD $FF $78 $78 $79 $87 $CC $CC $CD $33 $78 $78 $79 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $019
.db $78 $78 $FB $BF $FC $FC $FD $FF $CC $CC $CD $FF $7C $7C $7D $83 $08 $08 $89 $F7 $30 $30 $F3 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $01A
.db $30 $30 $F7 $DF $30 $30 $F7 $FF $00 $00 $C7 $FF $00 $00 $FF $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $01B
.db $30 $30 $F7 $DF $30 $30 $F7 $FF $00 $00 $C7 $FF $30 $30 $F7 $CF $10 $10 $D7 $EF $20 $20 $E7 $DF $00 $00 $CF $FF $00 $00 $FF $FF
; Tile index $01C
.db $18 $18 $FB $EF $38 $38 $FB $FF $30 $30 $F3 $FF $60 $60 $E7 $9F $30 $30 $B7 $CF $18 $18 $DB $E7 $00 $00 $E3 $FF $00 $00 $FF $FF
; Tile index $01D
.db $00 $00 $FF $FF $00 $00 $FF $FF $7C $7C $FD $BF $00 $00 $81 $FF $7C $7C $FD $83 $00 $00 $81 $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $01E
.db $60 $60 $EF $BF $70 $70 $F7 $FF $30 $30 $B7 $FF $18 $18 $DB $E7 $30 $30 $F3 $CF $60 $60 $E7 $9F $00 $00 $8F $FF $00 $00 $FF $FF
; Tile index $01F
.db $FC $FC $FD $7F $CC $CC $CD $FF $0C $0C $1D $FF $30 $30 $F1 $CF $00 $00 $C7 $FF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $020
.db $78 $78 $FB $BF $FC $FC $FD $FF $D4 $D4 $D5 $FF $DC $DC $DD $23 $C0 $C0 $C1 $3F $78 $78 $7B $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $021
.db $38 $38 $FB $DF $7C $7C $FD $FF $6C $6C $ED $FF $CC $CC $CD $33 $FC $FC $FD $03 $8C $8C $8D $73 $00 $00 $31 $FF $00 $00 $FF $FF
; Tile index $022
.db $F8 $F8 $FB $7F $FC $FC $FD $FF $CC $CC $CD $FF $F8 $F8 $F9 $07 $CC $CC $CD $33 $F8 $F8 $F9 $07 $00 $00 $03 $FF $00 $00 $FF $FF
; Tile index $023
.db $7C $7C $FD $BF $FC $FC $FD $FF $C0 $C0 $C1 $FF $C0 $C0 $DF $3F $C0 $C0 $DF $3F $78 $78 $7B $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $024
.db $F8 $F8 $FB $7F $FC $FC $FD $FF $CC $CC $CD $FF $CC $CC $DD $33 $CC $CC $DD $33 $F8 $F8 $F9 $07 $00 $00 $03 $FF $00 $00 $FF $FF
; Tile index $025
.db $FC $FC $FD $7F $FC $FC $FD $FF $C0 $C0 $C1 $FF $F8 $F8 $FB $07 $C0 $C0 $C3 $3F $F8 $F8 $FB $07 $00 $00 $03 $FF $00 $00 $FF $FF
; Tile index $026
.db $FC $FC $FD $7F $FC $FC $FD $FF $C0 $C0 $C1 $FF $F8 $F8 $FB $07 $C0 $C0 $C3 $3F $C0 $C0 $DF $3F $00 $00 $1F $FF $00 $00 $FF $FF
; Tile index $027
.db $7C $7C $FD $BF $FC $FC $FD $FF $C0 $C0 $C1 $FF $CC $CC $DD $33 $CC $CC $DD $33 $7C $7C $7D $83 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $028
.db $CC $CC $DD $77 $CC $CC $DD $FF $CC $CC $DD $FF $FC $FC $FD $03 $CC $CC $CD $33 $CC $CC $DD $33 $00 $00 $11 $FF $00 $00 $FF $FF
; Tile index $029
.db $30 $30 $F7 $DF $30 $30 $F7 $FF $30 $30 $F7 $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $02A
.db $0C $0C $FD $F7 $0C $0C $FD $FF $0C $0C $FD $FF $0C $0C $FD $F3 $6C $6C $ED $93 $78 $78 $F9 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $02B
.db $CC $CC $DD $77 $DC $DC $DD $FF $F8 $F8 $F9 $FF $F0 $F0 $F3 $0F $D8 $D8 $DB $27 $CC $CC $CD $33 $00 $00 $11 $FF $00 $00 $FF $FF
; Tile index $02C
.db $60 $60 $EF $BF $60 $60 $EF $FF $60 $60 $EF $FF $60 $60 $EF $9F $60 $60 $EF $9F $78 $78 $FB $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $02D
.db $8E $8E $BE $77 $DE $DE $DE $FF $FE $FE $FE $FF $F6 $F6 $F6 $09 $A6 $A6 $A6 $59 $86 $86 $8E $79 $00 $00 $38 $FF $00 $00 $FF $FF
; Tile index $02E
.db $CC $CC $DD $7F $EC $EC $ED $FF $FC $FC $FD $FF $BC $BC $BD $43 $9C $9C $9D $63 $8C $8C $AD $73 $00 $00 $31 $FF $00 $00 $FF $FF
; Tile index $02F
.db $7C $7C $FD $BF $FE $FE $FE $FF $C6 $C6 $C6 $FF $C6 $C6 $DE $39 $C6 $C6 $DE $39 $7C $7C $7C $83 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $030
.db $F8 $F8 $FB $7F $FC $FC $FD $FF $CC $CC $CD $FF $CC $CC $DD $33 $F8 $F8 $F9 $07 $C0 $C0 $C3 $3F $00 $00 $1F $FF $00 $00 $FF $FF
; Tile index $031
.db $7C $7C $FD $BF $FE $FE $FE $FF $C6 $C6 $C6 $FF $C6 $C6 $DE $39 $CC $CC $DC $33 $7E $7E $7E $81 $00 $00 $80 $FF $00 $00 $FF $FF
; Tile index $032
.db $F8 $F8 $FB $7F $FC $FC $FD $FF $CC $CC $CD $FF $C8 $C8 $D9 $37 $F8 $F8 $FB $07 $CC $CC $CD $33 $00 $00 $11 $FF $00 $00 $FF $FF
; Tile index $033
.db $7C $7C $FD $BF $FC $FC $FD $FF $E0 $E0 $E1 $FF $78 $78 $7B $87 $1C $1C $9D $E3 $78 $78 $F9 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $034
.db $FC $FC $FD $7F $FC $FC $FD $FF $30 $30 $31 $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $035
.db $CC $CC $DD $7F $CC $CC $DD $FF $CC $CC $DD $FF $CC $CC $DD $33 $CC $CC $DD $33 $78 $78 $79 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $036
.db $CC $CC $DD $7F $CC $CC $DD $FF $48 $48 $59 $FF $78 $78 $FB $87 $30 $30 $B3 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $037
.db $C6 $C6 $DE $7F $D6 $D6 $D6 $FF $D6 $D6 $D6 $FF $7C $7C $7C $83 $7C $7C $FD $83 $28 $28 $A9 $D7 $00 $00 $C3 $FF $00 $00 $FF $FF
; Tile index $038
.db $CC $CC $DD $7F $CC $CC $DD $FF $78 $78 $79 $FF $30 $30 $B3 $CF $78 $78 $FB $87 $CC $CC $CD $33 $00 $00 $11 $FF $00 $00 $FF $FF
; Tile index $039
.db $CC $CC $DD $7F $CC $CC $DD $FF $CC $CC $DD $FF $78 $78 $79 $87 $30 $30 $B3 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $03A
.db $FC $FC $FD $7F $FC $FC $FD $FF $18 $18 $19 $FF $30 $30 $F3 $CF $60 $60 $E7 $9F $F8 $F8 $FB $07 $00 $00 $03 $FF $00 $00 $FF $FF
; Tile index $03B
.db $38 $38 $FB $DF $38 $38 $FB $FF $30 $30 $F3 $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $38 $38 $FB $C7 $00 $00 $C3 $FF $00 $00 $FF $FF
; Tile index $03C
.db $C0 $C0 $DF $7F $60 $60 $6F $FF $30 $30 $B7 $FF $18 $18 $DB $E7 $0C $0C $ED $F3 $06 $06 $F6 $F9 $00 $00 $F8 $FF $00 $00 $FF $FF
; Tile index $03D
.db $38 $38 $FB $DF $38 $38 $FB $FF $18 $18 $DB $FF $18 $18 $FB $E7 $18 $18 $FB $E7 $38 $38 $FB $C7 $00 $00 $C3 $FF $00 $00 $FF $FF
; Tile index $03E
.db $18 $18 $FB $EF $30 $30 $F3 $FF $20 $20 $E7 $FF $00 $00 $CF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $03F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $7C $7C $FD $83 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $040
.db $18 $18 $FB $EF $30 $30 $F3 $FF $20 $20 $E7 $FF $00 $00 $CF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $041
.db $00 $00 $FF $FF $78 $78 $FB $BF $0C $0C $8D $FF $7C $7C $FD $83 $CC $CC $CD $33 $7C $7C $7D $83 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $042
.db $C0 $C0 $DF $7F $C0 $C0 $DF $FF $F8 $F8 $FB $FF $FC $FC $FD $03 $CC $CC $CD $33 $F8 $F8 $F9 $07 $00 $00 $03 $FF $00 $00 $FF $FF
; Tile index $043
.db $00 $00 $FF $FF $7C $7C $FD $BF $FC $FC $FD $FF $C0 $C0 $C1 $3F $C0 $C0 $DF $3F $78 $78 $7B $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $044
.db $0C $0C $FD $F7 $0C $0C $FD $FF $7C $7C $FD $FF $FC $FC $FD $03 $C4 $C4 $C5 $3B $7C $7C $7D $83 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $045
.db $00 $00 $FF $FF $78 $78 $FB $BF $CC $CC $CD $FF $FC $FC $FD $03 $C0 $C0 $C1 $3F $78 $78 $7B $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $046
.db $1C $1C $FD $EF $3C $3C $FD $FF $30 $30 $F1 $FF $7C $7C $FD $83 $30 $30 $B1 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $047
.db $7C $7C $FD $BF $FC $FC $FD $FF $CC $CC $CD $FF $7C $7C $7D $83 $0C $0C $8D $F3 $78 $78 $F9 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $048
.db $60 $60 $EF $BF $60 $60 $EF $FF $78 $78 $FB $FF $7C $7C $FD $83 $4C $4C $CD $B3 $4C $4C $DD $B3 $00 $00 $91 $FF $00 $00 $FF $FF
; Tile index $049
.db $30 $30 $F7 $DF $00 $00 $C7 $FF $30 $30 $F7 $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $04A
.db $18 $18 $FB $EF $00 $00 $E3 $FF $18 $18 $FB $FF $18 $18 $FB $E7 $58 $58 $DB $A7 $70 $70 $F3 $8F $00 $00 $87 $FF $00 $00 $FF $FF
; Tile index $04B
.db $C0 $C0 $DF $7F $CC $CC $DD $FF $DC $DC $DD $FF $F8 $F8 $F9 $07 $F0 $F0 $F3 $0F $CC $CC $CD $33 $00 $00 $11 $FF $00 $00 $FF $FF
; Tile index $04C
.db $30 $30 $F7 $DF $30 $30 $F7 $FF $30 $30 $F7 $FF $30 $30 $F7 $CF $30 $30 $F7 $CF $30 $30 $F7 $CF $00 $00 $C7 $FF $00 $00 $FF $FF
; Tile index $04D
.db $00 $00 $FF $FF $EC $EC $ED $7F $FE $FE $FE $FF $D6 $D6 $D6 $29 $D6 $D6 $D6 $29 $D6 $D6 $D6 $29 $00 $00 $00 $FF $00 $00 $FF $FF
; Tile index $04E
.db $00 $00 $FF $FF $F8 $F8 $FB $7F $FC $FC $FD $FF $8C $8C $8D $73 $8C $8C $BD $73 $8C $8C $BD $73 $00 $00 $31 $FF $00 $00 $FF $FF
; Tile index $04F
.db $00 $00 $FF $FF $78 $78 $FB $BF $FC $FC $FD $FF $CC $CC $CD $33 $CC $CC $DD $33 $78 $78 $79 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $050
.db $00 $00 $FF $FF $F8 $F8 $FB $7F $FC $FC $FD $FF $CC $CC $CD $33 $F8 $F8 $F9 $07 $C0 $C0 $C3 $3F $00 $00 $1F $FF $00 $00 $FF $FF
; Tile index $051
.db $00 $00 $FF $FF $7C $7C $FD $BF $FC $FC $FD $FF $CC $CC $CD $33 $7C $7C $7D $83 $0C $0C $8D $F3 $00 $00 $F1 $FF $00 $00 $FF $FF
; Tile index $052
.db $00 $00 $FF $FF $6C $6C $ED $BF $6C $6C $ED $FF $70 $70 $F1 $8F $60 $60 $E7 $9F $60 $60 $EF $9F $00 $00 $8F $FF $00 $00 $FF $FF
; Tile index $053
.db $00 $00 $FF $FF $7C $7C $FD $BF $FC $FC $FD $FF $60 $60 $61 $9F $38 $38 $BB $C7 $F0 $F0 $F3 $0F $00 $00 $07 $FF $00 $00 $FF $FF
; Tile index $054
.db $30 $30 $F7 $DF $7C $7C $FD $FF $7C $7C $FD $FF $30 $30 $B1 $CF $30 $30 $F7 $CF $18 $18 $DB $E7 $00 $00 $E3 $FF $00 $00 $FF $FF
; Tile index $055
.db $00 $00 $FF $FF $D8 $D8 $DB $7F $D8 $D8 $DB $FF $D8 $D8 $DB $27 $D8 $D8 $DB $27 $6C $6C $6D $93 $00 $00 $81 $FF $00 $00 $FF $FF
; Tile index $056
.db $00 $00 $FF $FF $6C $6C $ED $BF $6C $6C $ED $FF $6C $6C $ED $93 $38 $38 $B9 $C7 $10 $10 $D3 $EF $00 $00 $E7 $FF $00 $00 $FF $FF
; Tile index $057
.db $00 $00 $FF $FF $C6 $C6 $DE $7F $D6 $D6 $D6 $FF $D6 $D6 $D6 $29 $7C $7C $7C $83 $28 $28 $A9 $D7 $00 $00 $C3 $FF $00 $00 $FF $FF
; Tile index $058
.db $00 $00 $FF $FF $CC $CC $DD $7F $CC $CC $DD $FF $78 $78 $79 $87 $30 $30 $B3 $CF $CC $CC $CD $33 $00 $00 $11 $FF $00 $00 $FF $FF
; Tile index $059
.db $00 $00 $FF $FF $CC $CC $DD $77 $CC $CC $DD $FF $7C $7C $7D $83 $0C $0C $8D $F3 $78 $78 $F9 $87 $00 $00 $83 $FF $00 $00 $FF $FF
; Tile index $05A
.db $00 $00 $FF $FF $FC $FC $FD $7F $F8 $F8 $F9 $FF $30 $30 $33 $CF $60 $60 $E7 $9F $F8 $F8 $FB $07 $00 $00 $03 $FF $00 $00 $FF $FF
