; Tile index $060
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $061
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FE $FF $03 $FC $FD $FF $07 $F8 $FB
; Tile index $062
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FE $FF $00 $FC $FC
; Tile index $063
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $40 $BF $BF $FF $E0 $1F $5F $FF $7C $83 $A3 $FF $3F $40 $5C
; Tile index $064
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $1C $E3 $E3 $FF $3E $C1 $DD $FF $3F $80 $9E $FF $1F $00 $0E $FF $FF $00 $06
; Tile index $065
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $03 $FC $FC $FF $3F $C0 $C3 $FF $FF $00 $3C
; Tile index $066
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $80 $7F $7F $FF $F0 $0F $0F
; Tile index $067
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $04 $FB $FB $FF $1E $E1 $E5 $FF $3E $C1 $DD $FF $7E $81 $BD
; Tile index $068
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $0F $F0 $F0 $FF $7F $80 $8F $FF $FF $00 $7F
; Tile index $069
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $C0 $3F $3F $FF $E0 $1F $DF $FF $F0 $0F $EF
; Tile index $06A
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FE $FF $03 $FC $FD $FF $07 $F8 $FB $FF $0F $F0 $F4 $FF $1C $E0 $E8
; Tile index $06B
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $C0 $3F $3F $FF $F0 $0F $CF $FF $F8 $07 $F7 $FF $FC $03 $7B $FF $7C $03 $3B
; Tile index $06C
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $1C $E3 $E3 $FF $3E $C1 $DD
; Tile index $06D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $30 $CF $CF $FF $78 $87 $B7 $FF $FC $03 $7B
; Tile index $06E
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FE $FF $03 $FC $FD $FF $07 $F8 $FA
; Tile index $06F
.db $FF $00 $FF $FF $FF $07 $F8 $F8 $FF $3F $C0 $C7 $FF $7F $80 $BF $FF $FF $00 $7F $FF $FF $00 $C1 $FF $C3 $00 $01 $FF $01 $00 $00
; Tile index $070
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $C0 $3F $3F $FF $E0 $1F $DF $FF $F0 $0F $EF $FF $F8 $07 $F7 $FF $F8 $07 $F7 $FF $F8 $07 $F7
; Tile index $071
.db $FF $0F $F0 $F7 $FF $0F $E0 $E7 $FF $0F $C0 $C7 $FF $0F $C0 $C7 $FF $0F $C0 $C7 $FF $0F $C0 $C7 $FF $0F $C0 $C7 $FF $0F $C0 $C7
; Tile index $072
.db $FF $E0 $1F $DF $FF $E0 $1F $DF $FF $E0 $1F $DF $FF $C0 $3F $BF $FF $C0 $3F $BF $FF $C0 $3F $BF $FF $C0 $3F $BF $FF $80 $7F $7F
; Tile index $073
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FC $FC
; Tile index $074
.db $FF $07 $F8 $F8 $FF $1F $E0 $E7 $FF $3F $C0 $DF $FF $7F $80 $BE $FF $7F $00 $3E $FF $FE $01 $7D $FF $FC $03 $7B $FF $78 $07 $07
; Tile index $075
.db $FF $E0 $1F $1F $FF $F0 $0F $EF $FF $F8 $07 $37 $FF $3C $03 $1B $FF $1E $01 $0D $FF $0F $00 $06 $FF $0F $80 $86 $FF $37 $C0 $C3
; Tile index $076
.db $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FE $FF $03 $FC $FD $FF $03 $F8 $F9 $FF $83 $70 $71
; Tile index $077
.db $FF $1F $00 $03 $FF $03 $00 $00 $FF $3C $80 $80 $FF $FF $00 $3C $FF $FF $00 $F3 $FF $F3 $00 $C0 $FF $E0 $01 $C1 $FF $E0 $13 $D3
; Tile index $078
.db $FF $FF $00 $FF $FF $FF $00 $06 $FF $0F $00 $06 $FF $0F $00 $06 $FF $8F $40 $46 $FF $0F $C0 $C6 $FF $0F $C0 $C6 $FF $0F $C0 $C6
; Tile index $079
.db $FF $FF $00 $C1 $FF $C1 $00 $00 $FF $01 $00 $00 $FF $00 $F8 $F8 $FF $00 $F8 $F8 $FF $00 $FC $FC $FF $00 $FC $FC $FF $07 $F8 $F8
; Tile index $07A
.db $FF $F0 $0F $EF $FF $F1 $0E $EE $FF $FB $04 $F5 $FF $FF $00 $73 $FF $FF $00 $72 $FF $7F $00 $36 $FF $7E $01 $35 $FF $FE $01 $3D
; Tile index $07B
.db $FF $FD $02 $72 $FF $F3 $04 $C5 $FF $C7 $08 $8B $FF $87 $30 $33 $FF $0F $E0 $E7 $FF $0F $E0 $E7 $FF $0F $C0 $C7 $FF $0F $C0 $C7
; Tile index $07C
.db $FF $FF $00 $F0 $FF $F1 $00 $C0 $FF $C0 $00 $80 $FF $C0 $38 $B8 $FF $80 $7C $7C $FF $80 $7C $7C $FF $80 $7C $7C $FF $80 $7C $7C
; Tile index $07D
.db $FF $F8 $07 $F7 $FF $FC $03 $FB $FF $FE $01 $7D $FF $FE $01 $7D $FF $FE $01 $7D $FF $FE $01 $7D $FF $FE $01 $7D $FF $FE $01 $7D
; Tile index $07E
.db $FF $3C $C0 $D8 $FF $38 $86 $96 $FF $3C $02 $1A $FF $1E $01 $0D $FF $0F $00 $06 $FF $07 $80 $83 $FF $03 $C0 $C1 $FF $01 $E0 $E0
; Tile index $07F
.db $FF $7E $01 $3D $FF $3F $00 $1E $FF $1F $00 $0E $FF $1F $00 $0F $FF $8F $00 $07 $FF $E7 $00 $80 $FF $F0 $00 $E0 $FF $FC $02 $F2
; Tile index $080
.db $FF $3F $80 $9E $FF $7F $00 $3F $FF $7F $00 $3F $FF $FF $00 $3F $FF $FF $00 $3E $FF $7F $00 $3E $FF $7E $01 $3D $FF $7E $01 $3D
; Tile index $081
.db $FF $00 $FE $FE $FF $80 $7C $7C $FF $84 $78 $78 $FF $8E $70 $74 $FF $1E $E0 $EC $FF $1E $C0 $CC $FF $3E $80 $9C $FF $3E $80 $9C
; Tile index $082
.db $FF $FE $01 $7D $FF $7E $01 $3D $FF $7F $00 $3E $FF $7F $00 $3E $FF $7F $00 $3E $FF $7F $00 $3E $FF $3F $00 $1E $FF $3F $00 $1E
; Tile index $083
.db $FF $0E $F0 $F4 $FF $0F $E0 $E6 $FF $06 $C1 $C1 $FF $00 $C3 $C3 $FF $00 $E7 $E7 $FF $00 $FF $FF $FF $07 $F8 $F8 $FF $1F $E0 $E7
; Tile index $084
.db $FF $01 $F0 $F0 $FF $01 $F8 $F8 $FF $01 $F8 $F8 $FF $01 $F8 $F8 $FF $01 $F8 $F8 $FF $01 $F8 $F8 $FF $F1 $08 $08 $FF $FF $00 $F0
; Tile index $085
.db $FF $F8 $07 $F7 $FF $F8 $07 $F7 $FF $F8 $07 $F7 $FF $F8 $07 $F7 $FF $F8 $07 $F7 $FF $F8 $07 $F7 $FF $F8 $07 $F7 $FF $F8 $07 $F7
; Tile index $086
.db $FF $0F $C0 $C7 $FF $0F $C0 $C7 $FF $0F $C0 $C7 $FF $0F $C0 $C6 $FF $0F $C0 $C6 $FF $0F $C0 $C6 $FF $1F $C0 $CE $FF $1F $C0 $CF
; Tile index $087
.db $FF $80 $7F $7F $FF $80 $7F $7F $FF $87 $78 $78 $FF $1F $E0 $E7 $FF $7F $80 $9E $FF $FE $00 $64 $FF $E4 $01 $81 $FF $80 $07 $07
; Tile index $088
.db $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $FF $FF $FF $00 $87 $FF $87 $00 $01 $FF $01 $00 $00 $FF $00 $E0 $E0 $FF $00 $F8 $F8
; Tile index $089
.db $FF $00 $FF $FF $FF $C0 $3F $3F $FF $F8 $07 $C7 $FF $FC $03 $FB $FF $FE $01 $FD $FF $FF $00 $FE $FF $FF $00 $7F $FF $FF $00 $7F
; Tile index $08A
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $80 $7F $7F $FF $C0 $3F $BF
; Tile index $08B
.db $FF $01 $0E $0E $FF $07 $18 $19 $FF $0F $F0 $F6 $FF $1E $E0 $E8 $FF $38 $C0 $D0 $FF $38 $87 $97 $FF $38 $07 $17 $FF $78 $07 $37
; Tile index $08C
.db $FF $FF $00 $31 $FF $FF $00 $CF $FF $CF $00 $01 $FF $01 $00 $00 $FF $01 $C0 $C0 $FF $01 $F8 $F8 $FF $01 $F8 $F8 $FF $01 $F8 $F8
; Tile index $08D
.db $FF $C3 $30 $B1 $FF $C1 $30 $B0 $FF $E0 $10 $D0 $FF $E0 $18 $D8 $FF $E0 $1C $DC $FF $F8 $07 $E7 $FF $FD $02 $FA $FF $FD $00 $F8
; Tile index $08E
.db $FF $F0 $0F $CF $FF $FE $01 $F1 $FF $FF $00 $3E $FF $1F $00 $07 $FF $07 $00 $03 $FF $83 $00 $01 $FF $C7 $20 $A3 $FF $C7 $30 $B3
; Tile index $08F
.db $FF $0F $C0 $C6 $FF $0F $C0 $C6 $FF $CF $00 $06 $FF $EF $00 $C7 $FF $E7 $00 $C3 $FF $E7 $00 $C3 $FF $E7 $00 $C3 $FF $C3 $20 $A0
; Tile index $090
.db $FF $0F $F0 $F7 $FF $0F $E0 $E7 $FF $0F $C0 $C7 $FF $9F $40 $4E $FF $9E $41 $4D $FF $BC $03 $1B $FF $F8 $07 $37 $FF $F0 $0F $EF
; Tile index $091
.db $FF $FE $01 $BD $FF $BC $03 $1B $FF $BC $03 $1B $FF $3C $03 $1B $FF $3C $03 $1B $FF $3C $03 $1B $FF $3C $03 $1B $FF $1C $03 $0B
; Tile index $092
.db $FF $1F $C0 $CF $FF $1F $C0 $CF $FF $1F $80 $8F $FF $1F $80 $8F $FF $1F $80 $8F $FF $0F $80 $87 $FF $0F $80 $87 $FF $07 $C0 $C3
; Tile index $093
.db $FF $80 $7C $7C $FF $80 $7C $7C $FF $80 $7C $7C $FF $80 $7C $7C $FF $C0 $3C $BC $FF $C0 $3C $BC $FF $C3 $3C $BC $FF $FF $00 $83
; Tile index $094
.db $FF $FE $01 $7D $FF $FC $03 $7B $FF $FC $03 $7B $FF $F8 $06 $76 $FF $F0 $0C $6C $FF $E0 $1C $5C $FF $C0 $3C $BC $FF $80 $7C $7C
; Tile index $095
.db $FF $38 $C0 $C0 $FF $7C $80 $B8 $FF $FC $00 $78 $FF $FC $00 $78 $FF $FC $02 $7A $FF $FC $02 $7A $FF $7C $02 $3A $FF $7C $02 $3A
; Tile index $096
.db $FF $FE $00 $7C $FF $FF $00 $7E $FF $7F $00 $3E $FF $7F $00 $3F $FF $7F $00 $3F $FF $7F $00 $3F $FF $7F $00 $3E $FF $7E $01 $3D
; Tile index $097
.db $FF $7E $01 $3D $FF $7E $01 $3D $FF $7C $02 $3A $FF $BC $02 $1A $FF $BD $00 $18 $FF $BF $00 $19 $FF $3F $00 $1D $FF $3F $00 $1E
; Tile index $098
.db $FF $7E $01 $3D $FF $7E $01 $3D $FF $FE $01 $7D $FF $FE $01 $45 $FF $EF $00 $C6 $FF $C7 $00 $82 $FF $87 $40 $43 $FF $03 $E0 $E1
; Tile index $099
.db $FF $3F $00 $1E $FF $3E $01 $1D $FF $3F $00 $1C $FF $3F $00 $1C $FF $7F $00 $3C $FF $FD $00 $78 $FF $F8 $00 $F0 $FF $F8 $00 $F0
; Tile index $09A
.db $FF $7F $80 $9F $FF $FF $00 $7C $FF $FC $00 $F8 $FF $FC $03 $FB $FF $FC $03 $FB $FF $FE $01 $FD $FF $FF $00 $7C $FF $7F $00 $3F
; Tile index $09B
.db $FF $FF $00 $0E $FF $0F $00 $06 $FF $0F $00 $07 $FF $0F $C0 $C7 $FF $0F $C0 $C7 $FF $FF $00 $0E $FF $FF $00 $F0 $FF $F0 $00 $00
; Tile index $09C
.db $FF $F8 $07 $F7 $FF $F0 $0F $EF $FF $F0 $0F $EF $FF $F0 $0F $EF $FF $F0 $0F $EF $FF $F0 $0F $EF $FF $F0 $0F $EF $FF $E0 $1E $5E
; Tile index $09D
.db $FF $1F $80 $8E $FF $1E $81 $8D $FF $3E $81 $9D $FF $3C $83 $9B $FF $3C $03 $1B $FF $78 $07 $37 $FF $78 $07 $37 $FF $F8 $07 $77
; Tile index $09E
.db $FF $00 $6F $6F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $09F
.db $FF $00 $FC $FC $FF $00 $FC $FC $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A0
.db $FF $7F $00 $3F $FF $7F $00 $3F $FF $7F $00 $3F $FF $3F $00 $1F $FF $3F $00 $1F $FF $3F $00 $1F $FF $7F $00 $3F $FF $7F $00 $3F
; Tile index $0A1
.db $FF $C0 $3F $BF $FF $E0 $1F $DF $FF $E0 $1F $DF $FF $E0 $1F $DF $FF $E0 $1F $DF $FF $C0 $3F $BF $FF $C0 $3F $BF $FF $80 $7F $7F
; Tile index $0A2
.db $FF $00 $FF $FF $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE
; Tile index $0A3
.db $FF $78 $07 $37 $FF $78 $07 $37 $FF $7C $03 $3B $FF $7C $03 $3B $FF $7E $01 $3D $FF $7F $00 $3E $FF $7F $00 $3F $FF $7F $00 $3F
; Tile index $0A4
.db $FF $01 $F8 $F8 $FF $01 $F8 $F8 $FF $07 $F8 $F9 $FF $0F $F0 $F6 $FF $3E $C0 $CC $FF $FC $01 $39 $FF $F8 $07 $E7 $FF $E0 $0F $CF
; Tile index $0A5
.db $FF $F9 $00 $F0 $FF $F1 $08 $C8 $FF $C0 $18 $98 $FF $80 $38 $38 $FF $00 $FC $FC $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A6
.db $FF $CF $20 $A7 $FF $FF $00 $86 $FF $FE $01 $79 $FF $78 $03 $23 $FF $20 $07 $07 $FF $00 $1F $1F $FF $00 $7F $7F $FF $00 $FF $FF
; Tile index $0A7
.db $FF $81 $60 $60 $FF $00 $F0 $F0 $FF $00 $F8 $F8 $FF $00 $FC $FC $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A8
.db $FF $E0 $1F $DF $FF $C0 $3F $3F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A9
.db $FF $08 $07 $07 $FF $00 $8F $8F $FF $00 $DF $DF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AA
.db $FF $03 $C0 $C1 $FF $01 $E0 $E0 $FF $00 $F0 $F0 $FF $00 $F8 $F8 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AB
.db $FF $FF $00 $FC $FF $FC $01 $01 $FF $00 $03 $03 $FF $00 $0F $0F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AC
.db $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AD
.db $FF $3F $00 $1C $FF $3F $00 $1F $FF $1F $00 $07 $FF $07 $00 $00 $FF $00 $80 $80 $FF $00 $E1 $E1 $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AE
.db $FF $FC $03 $7B $FF $F8 $07 $C7 $FF $C0 $0F $8F $FF $80 $1F $1F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AF
.db $FF $1E $01 $0D $FF $0C $03 $03 $FF $00 $87 $87 $FF $00 $CF $CF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B0
.db $FF $01 $E0 $E0 $FF $00 $F0 $F0 $FF $00 $F8 $F8 $FF $00 $FC $FC $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B1
.db $FF $F0 $0C $EC $FF $E0 $1E $1E $FF $00 $3F $3F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B2
.db $FF $3F $00 $00 $FF $00 $00 $00 $FF $00 $03 $03 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B3
.db $FF $00 $00 $00 $FF $00 $3C $3C $FF $00 $FC $FC $FF $00 $FC $FC $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B4
.db $FF $E0 $1E $5E $FF $E1 $1C $5C $FF $43 $3C $3D $FF $01 $78 $78 $FF $00 $F0 $F0 $FF $00 $F8 $F8 $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B5
.db $FF $F8 $07 $77 $FF $F8 $07 $F7 $FF $FF $00 $F8 $FF $FF $00 $1F $FF $1F $00 $00 $FF $00 $00 $00 $FF $00 $80 $80 $FF $00 $FC $FC
; Tile index $0B6
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FE $01 $01 $FF $FF $00 $FE $FF $FF $00 $01 $FF $01 $00 $00 $FF $00 $00 $00
; Tile index $0B7
.db $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $7F $80 $80 $FF $FF $00 $7F $FF $FF $00 $80 $FF $80 $00 $00 $FF $00 $03 $03
; Tile index $0B8
.db $FF $7F $00 $3E $FF $7E $01 $3D $FF $FC $03 $7B $FF $F8 $07 $E7 $FF $E0 $0F $0F $FF $00 $1F $1F $FF $00 $7F $7F $FF $00 $FF $FF
; Tile index $0B9
.db $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BA
.db $FF $7F $00 $3F $FF $3F $00 $1E $FF $1E $00 $00 $FF $00 $03 $03 $FF $00 $87 $87 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BB
.db $FF $C0 $1F $1F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BC
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $7F $FF $80
; Tile index $0BD
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $49 $FF $B6
; Tile index $0BE
.db $FF $00 $F9 $F9 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BF
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FF $FE $FF $02 $FF $FD $FF $04 $FF $FB $FF $08 $FF $F7
; Tile index $0C0
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C1
.db $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C2
.db $FF $41 $FF $BE $FF $41 $FF $BE $FF $41 $FF $BE $FF $7F $FF $80 $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C3
.db $FF $41 $FF $BE $FF $41 $FF $BE $FF $7F $FF $80 $FF $40 $FF $BF $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C4
.db $FF $40 $FF $BF $FF $7F $FF $80 $FF $01 $FF $FE $FF $7F $FF $80 $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C5
.db $FF $49 $FF $B6 $FF $49 $FF $B6 $FF $49 $FF $B6 $FF $7F $FF $80 $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C6
.db $FF $41 $FF $BE $FF $7F $FF $80 $FF $41 $FF $BE $FF $41 $FF $BE $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C7
.db $FF $41 $FF $BE $FF $7F $FF $80 $FF $41 $FF $BE $FF $7F $FF $80 $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C8
.db $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7 $FF $08 $FF $F7
; Tile index $0C9
.db $FF $04 $FF $FB $FF $02 $FF $FD $FF $01 $FF $FE $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CA
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CB
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F8 $F8 $FF $00 $C0 $C7 $FF $00 $80 $BF $FF $00 $00 $70
; Tile index $0CC
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $1F $1F $FF $00 $07 $E7 $FF $00 $01 $F9 $FF $00 $00 $00
; Tile index $0CD
.db $FF $00 $FF $FF $FF $00 $F0 $F0 $FF $00 $C0 $CF $FF $00 $80 $B0 $FF $00 $80 $A0 $FF $00 $80 $80 $FF $23 $23 $00 $FF $7F $7F $00
; Tile index $0CE
.db $FF $00 $FF $FF $FF $00 $3F $3F $FF $00 $1F $DF $FF $00 $0F $6F $FF $00 $1F $1F $FF $C0 $DF $1F $FF $E0 $EF $0F $FF $C0 $DF $1F
; Tile index $0CF
.db $FF $00 $FC $FC $FF $00 $F8 $FB $FF $00 $F0 $F7 $FF $00 $E0 $EE $FF $00 $C0 $DC $DF $00 $A0 $98 $DF $00 $A0 $98 $BF $03 $43 $38
; Tile index $0D0
.db $FF $00 $00 $C0 $FF $00 $00 $C0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $00 $FF $03 $03 $00 $FF $0F $0F $00
; Tile index $0D1
.db $FF $3E $3E $00 $FF $3F $3F $00 $FF $7F $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $0D2
.db $FF $00 $7F $7F $FF $00 $3F $3F $FF $80 $9F $1F $FF $C0 $DF $1F $FF $C0 $CF $0F $FF $E0 $EF $0F $FF $F0 $F7 $07 $FF $F0 $F7 $07
; Tile index $0D3
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F0 $F0 $FF $00 $80 $8F
; Tile index $0D4
.db $FF $7F $7F $00 $FF $3F $BF $80 $FF $00 $C0 $C0 $F7 $00 $EB $E3 $EF $00 $D3 $CB $EF $00 $D3 $CB $EF $00 $13 $0B $F7 $00 $0B $E3
; Tile index $0D5
.db $FF $C0 $DF $1F $FF $80 $BF $3F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0D6
.db $BF $03 $43 $38 $BF $03 $43 $38 $BF $07 $47 $30 $BF $07 $47 $30 $BF $07 $47 $30 $DF $03 $A3 $98 $DF $03 $A3 $98 $E7 $01 $D9 $C4
; Tile index $0D7
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $0D8
.db $FF $F0 $F7 $07 $FF $F0 $F7 $07 $FF $F0 $F7 $07 $FF $F0 $F7 $07 $FF $F0 $F7 $07 $FF $F0 $F7 $07 $FF $E0 $E6 $06 $EE $C0 $D1 $00
; Tile index $0D9
.db $FF $00 $FC $FC $FE $00 $F9 $F8 $FB $00 $E4 $E3 $E7 $00 $D8 $C7 $DF $00 $A0 $9F $BF $00 $40 $3F $7F $00 $80 $7F $FF $00 $00 $FF
; Tile index $0DA
.db $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0DB
.db $FF $00 $03 $F3 $FF $00 $01 $FD $FF $00 $01 $FD $FF $00 $00 $FE $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0DC
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F $FF $00 $7F $7F $FF $00 $3F $BF
; Tile index $0DD
.db $FB $00 $E4 $E2 $FC $00 $FB $F8 $FF $00 $FC $FC $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0DE
.db $FF $FF $FF $00 $FF $7F $7F $00 $FF $7F $7F $00 $FF $0F $8F $80 $FF $00 $F0 $F0 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0DF
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FE $FE $00 $FF $F0 $F1 $01 $FF $00 $0F $0F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0E0
.db $F1 $80 $8E $31 $BF $00 $40 $3F $DF $00 $A0 $9F $EF $00 $D0 $CF $F7 $00 $C8 $C7 $F7 $00 $E8 $E7 $FF $00 $C0 $DF $FF $00 $C0 $DF
; Tile index $0E1
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0E2
.db $FF $00 $1F $DF $FF $00 $1F $DF $FF $00 $0F $EF $FF $00 $0F $EF $FF $00 $0F $EF $FF $00 $0F $EF $FF $00 $07 $F7 $FF $00 $07 $F7
; Tile index $0E3
.db $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F
; Tile index $0E4
.db $FF $00 $07 $F7 $FF $00 $07 $F7 $FF $00 $07 $F7 $FF $00 $07 $F7 $FF $00 $03 $FB $FF $00 $03 $FB $FF $00 $03 $DB $FF $00 $03 $BB
; Tile index $0E5
.db $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F $DF $00 $A0 $9F $EF $00 $D0 $CF $EF $00 $D0 $CF $EF $00 $D0 $CF $FF $00 $C0 $DF
; Tile index $0E6
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FD $00 $02 $FC
; Tile index $0E7
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $FD $FF $00 $00 $FB $FF $00 $00 $F7 $FF $00 $00 $CF $FF $00 $00 $3F
; Tile index $0E8
.db $FF $00 $03 $BB $FF $00 $03 $7B $FF $00 $03 $FB $FF $00 $03 $FB $FF $00 $03 $FB $FF $00 $03 $FB $FF $00 $03 $FB $FF $00 $03 $FB
