; Tile index $060
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $061
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $062
.db $FF $FF $FF $FF $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $063
.db $FF $FF $FF $FF $FF $00 $00 $00 $C0 $3F $3F $3F $DF $20 $3F $20 $CF $30 $3B $30 $FF $00 $2F $01 $FF $00 $1F $0F $FF $80 $9F $9F
; Tile index $064
.db $FF $FF $FF $FF $FF $00 $00 $00 $00 $FF $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $40
; Tile index $065
.db $FF $FF $FF $FF $FF $00 $00 $00 $00 $FF $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $066
.db $FF $FF $FF $FF $FF $01 $01 $01 $03 $FD $FD $FD $FF $01 $F9 $01 $FF $01 $F1 $01 $FF $01 $E1 $01 $FF $05 $C5 $05 $FF $07 $87 $07
; Tile index $067
.db $FF $FF $FF $FF $FF $80 $80 $80 $E0 $9F $9F $9F $EF $90 $9F $90 $EF $90 $9F $90 $FF $80 $83 $80 $FF $E0 $E3 $E0 $FD $F2 $F3 $F2
; Tile index $068
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FD $FD $FD
; Tile index $069
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $BF $BF $BF $FF $3F $3F $3F
; Tile index $06A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE
; Tile index $06B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $DF $DF $DF $FF $5F $5F $5F $FF $1F $1F $1F
; Tile index $06C
.db $FF $C0 $CF $CF $FF $C0 $C3 $C3 $FF $80 $83 $83 $FF $80 $81 $81 $FF $80 $80 $80 $FF $C0 $C0 $C0 $FF $D2 $D2 $D2 $FF $D2 $D2 $D2
; Tile index $06D
.db $FF $00 $FF $00 $FF $00 $FF $C0 $FF $00 $FF $F0 $FF $00 $FF $E0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FD $02 $FB $E2
; Tile index $06E
.db $FF $00 $FF $00 $FF $00 $FE $00 $FF $00 $FC $00 $FF $00 $F0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $EF $10 $98 $10
; Tile index $06F
.db $FF $07 $07 $07 $FF $0F $0F $0F $FF $1F $1F $1F $FF $3F $3F $3F $FF $3F $3F $3F $FF $7F $7F $7F $FF $FF $FF $FF $FF $EF $EF $EF
; Tile index $070
.db $FE $F1 $F1 $F1 $FF $F8 $F8 $F8 $FF $FE $FE $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F
; Tile index $071
.db $FF $00 $FF $00 $7F $80 $FF $80 $FF $00 $7F $00 $FF $00 $3F $00 $FF $80 $BF $80 $FF $80 $80 $80 $FF $C0 $C0 $C0 $FF $E0 $E3 $E0
; Tile index $072
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $01 $00 $FF $00 $D1 $00
; Tile index $073
.db $FF $FF $FF $FF $FF $F9 $F9 $F9 $FF $F8 $F8 $F8 $FF $F0 $F0 $F0 $FF $E0 $E0 $E0 $FF $E0 $E0 $E0 $FF $E0 $E0 $E0 $FF $C0 $C0 $C0
; Tile index $074
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $FF $1F $1F $1F $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $075
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $FF $E0 $E0 $E0 $FF $03 $03 $03
; Tile index $076
.db $FF $F9 $F9 $F9 $FF $FC $FC $FC $FF $F9 $F9 $F9 $FF $F9 $F9 $F9 $FF $F9 $F9 $F9 $FF $70 $70 $70 $FF $20 $20 $20 $FF $83 $83 $83
; Tile index $077
.db $FF $FF $FF $FF $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F $FF $3F $3F $3F $FF $3F $3F $3F $FF $8F $8F $8F
; Tile index $078
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FF $FC $FC $FC $FF $FC $FC $FC $FF $FC $FC $FC $FF $FC $FC $FC
; Tile index $079
.db $FF $1F $1F $1F $FF $3F $3F $3F $FF $3E $3E $3E $FF $3C $3C $3C $FF $3C $3C $3C $FF $1C $1C $1C $FF $0C $0C $0C $FF $00 $00 $00
; Tile index $07A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $FF $9F $9F $9F $FF $87 $87 $87 $FF $07 $07 $07 $FF $06 $06 $06 $FF $00 $00 $00
; Tile index $07B
.db $FF $FE $FE $FE $FF $FC $FC $FC $FF $FC $FC $FC $FF $FE $FE $FE $FF $FC $FC $FC $FF $D0 $D0 $D0 $FF $00 $00 $00 $FF $58 $58 $58
; Tile index $07C
.db $FF $1F $1F $1F $FF $CF $CF $CF $FF $AF $AF $AF $FF $6F $6F $6F $FF $6F $6F $6F $FF $2F $2F $2F $FF $00 $00 $00 $FF $75 $75 $75
; Tile index $07D
.db $FF $D6 $D6 $D6 $FF $D6 $D6 $D6 $FF $D6 $D6 $D6 $FF $F6 $F6 $F6 $FF $F2 $F2 $F2 $FF $F2 $F2 $F2 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $07E
.db $FD $02 $FB $E2 $7D $82 $FB $C2 $7D $82 $FB $92 $7D $82 $FB $82 $7D $82 $FB $82 $7D $82 $FB $82 $7D $82 $FB $82 $7D $82 $FB $82
; Tile index $07F
.db $EF $10 $D8 $10 $EF $10 $D0 $10 $EF $10 $D0 $10 $EF $10 $D0 $10 $EF $10 $D0 $10 $EF $10 $D0 $10 $EF $10 $D0 $10 $EF $10 $D8 $10
; Tile index $080
.db $FF $8F $8F $8F $FF $0F $0F $0F $FF $1F $1F $1F $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $081
.db $FF $FE $FE $FE $FF $FE $FE $FE $FF $FC $FC $FC $FF $1E $1E $1E $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $03 $00 $03
; Tile index $082
.db $FF $7F $7F $7F $FF $7F $7F $7F $FF $3F $3F $3F $FF $3F $3F $3F $FF $1F $1F $1F $FF $0F $0D $0F $FF $37 $00 $37 $FF $FF $00 $FF
; Tile index $083
.db $FF $F0 $F7 $F0 $FB $F4 $F7 $F4 $FB $F4 $F7 $F4 $FB $F4 $F7 $F4 $FB $84 $87 $84 $FB $74 $07 $74 $FB $F4 $07 $F4 $FB $F4 $07 $F4
; Tile index $084
.db $FF $00 $D9 $00 $EF $10 $DD $10 $EF $10 $DD $10 $EF $10 $DD $10 $EF $10 $DD $10 $EF $10 $DD $10 $EF $10 $DD $10 $EF $10 $DD $50
; Tile index $085
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $086
.db $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $1E $1E $1E $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $087
.db $FF $0F $0F $0F $FF $0F $0F $0F $FF $0F $0F $0F $FF $0F $0F $0F $FF $07 $07 $07 $FF $01 $01 $01 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $088
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $C3 $C3 $C3 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $089
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $08A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $07 $07 $07 $FF $00 $00 $00
; Tile index $08B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $F8 $F8 $FF $C0 $C0 $C0 $FF $00 $00 $00
; Tile index $08C
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FD $FD $FD $FF $F0 $F0 $F0 $FF $80 $80 $80 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $08D
.db $FF $FF $FF $FF $FF $FC $FC $FC $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $C0 $00 $C0
; Tile index $08E
.db $FF $FF $FF $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $08F
.db $FF $C2 $C2 $C2 $FF $18 $18 $18 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $07 $00 $07 $FF $1F $00 $1F $FF $3F $00 $3F
; Tile index $090
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $78 $00 $78 $FF $FC $00 $FC $FF $FC $00 $FC $FF $FC $00 $FC
; Tile index $091
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $092
.db $FF $03 $03 $03 $FF $02 $02 $02 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $093
.db $FF $00 $00 $00 $FF $07 $07 $07 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $094
.db $FF $00 $00 $00 $FF $80 $80 $80 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $095
.db $FF $8A $8A $8A $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $096
.db $FF $58 $58 $58 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $097
.db $FF $41 $41 $41 $FF $1D $1D $1D $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $098
.db $7D $82 $FB $82 $7D $82 $FB $82 $7D $82 $FB $82 $7D $82 $FB $82 $7D $82 $EB $82 $7D $82 $BB $82 $7D $82 $BB $82 $7D $82 $BB $82
; Tile index $099
.db $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10
; Tile index $09A
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $00 $01 $FF $03 $00 $03 $FF $07 $00 $07 $FF $1F $00 $1F $FF $3F $00 $3F
; Tile index $09B
.db $FF $1F $00 $1F $FF $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $09C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $09D
.db $FB $F4 $07 $F4 $FB $F4 $07 $F4 $FB $C4 $07 $C4 $FB $84 $0F $8C $FB $A4 $07 $A4 $FF $E0 $07 $E6 $FF $F0 $07 $F6 $FF $F0 $07 $F7
; Tile index $09E
.db $EF $10 $DD $50 $EF $10 $DD $50 $EF $10 $DD $50 $EF $10 $DD $90 $EF $10 $DD $10 $EF $10 $DB $10 $EF $10 $DB $90 $EF $10 $DB $10
; Tile index $09F
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $07 $00 $07
; Tile index $0A0
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $00 $01
; Tile index $0A1
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $7F $00 $7F $FF $FF $00 $FF
; Tile index $0A2
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $C0 $00 $C0 $FF $F8 $00 $F8
; Tile index $0A3
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $00 $01 $FF $03 $00 $03
; Tile index $0A4
.db $FF $03 $00 $03 $FF $07 $00 $07 $FF $0F $00 $0F $FF $1F $00 $1F $FF $3F $00 $3F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A5
.db $FF $F0 $00 $F0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A6
.db $FF $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A7
.db $FF $00 $00 $00 $FF $F0 $00 $F0 $FF $F8 $00 $F8 $FF $FC $00 $FC $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A8
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $78 $00 $78 $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A9
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $0F $00 $0F $FF $1F $00 $1F $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AA
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AB
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $80 $00 $80 $FF $FE $00 $FE
; Tile index $0AC
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FE $01 $01 $01 $FE $01 $01 $01 $FD $02 $03 $02
; Tile index $0AD
.db $FF $00 $00 $00 $FF $00 $00 $00 $E0 $1F $1F $1F $BF $40 $7F $40 $7F $80 $FF $80 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $0AE
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $80 $00 $FF $00 $80 $00 $FF $00 $C0 $00 $FF $00 $C0 $00
; Tile index $0AF
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $00 $01 $FF $1F $00 $1F $FF $7F $00 $7F
; Tile index $0B0
.db $FF $00 $00 $00 $FF $0F $00 $0F $FF $1F $00 $1F $FF $3F $00 $3F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0B1
.db $FF $7C $00 $7C $FF $FC $00 $FC $FF $FC $00 $FC $FF $FC $00 $FC $FF $FC $00 $FC $FF $FC $00 $FC $FF $FC $00 $FC $FF $F8 $00 $F8
; Tile index $0B2
.db $7D $82 $AB $82 $7D $82 $BB $82 $7D $82 $8B $82 $7D $82 $93 $82 $7D $82 $93 $82 $7D $82 $9B $82 $7D $82 $83 $82 $FF $00 $30 $00
; Tile index $0B3
.db $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $D8 $10 $EF $10 $DC $10 $FF $00 $00 $00
; Tile index $0B4
.db $FF $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $80 $7F $FF $3F $40 $3F $FF $3F $00 $3F $FF $1F $00 $1F $FF $0F $00 $0F
; Tile index $0B5
.db $FF $F0 $07 $F6 $FF $F0 $07 $F6 $FF $F0 $07 $F7 $FF $E0 $07 $E7 $FF $F0 $07 $F6 $FF $E0 $07 $E6 $FF $E0 $06 $E4 $FF $C0 $0E $CE
; Tile index $0B6
.db $EF $10 $DB $10 $EF $10 $DB $10 $FF $00 $9B $00 $FF $00 $FB $00 $FF $00 $FD $08 $FF $00 $3D $10 $FF $00 $FE $30 $FF $00 $00 $00
; Tile index $0B7
.db $FF $1F $00 $1F $FF $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $1F $00 $1F
; Tile index $0B8
.db $FF $F3 $00 $F3 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $00 $FC
; Tile index $0B9
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E0 $00 $E0 $FF $00 $00 $00
; Tile index $0BA
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $80 $00 $80 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0BB
.db $FF $80 $00 $80 $FF $F0 $00 $F0 $FF $FC $00 $FC $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0BC
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0BD
.db $FF $0F $00 $0F $FF $3F $00 $3F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0BE
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $03 $00 $03 $FF $00 $00 $00
; Tile index $0BF
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00
; Tile index $0C0
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FF $C0 $00 $C0 $FF $00 $01 $01
; Tile index $0C1
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $03 $00 $03 $FF $00 $08 $08 $FF $00 $FF $FF
; Tile index $0C2
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C3
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FF $80 $00 $80 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C4
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $C7 $00 $C7 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C5
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $00 $3F $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C6
.db $FF $C3 $00 $C3 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C7
.db $FB $F4 $07 $F4 $FB $F4 $07 $F4 $FB $E4 $07 $E4 $F7 $E8 $0F $E8 $FF $C0 $0F $C0 $FF $80 $1F $80 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C8
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $F8 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C9
.db $FF $00 $C0 $00 $FF $01 $E0 $01 $FF $01 $E0 $01 $FF $00 $E0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0CA
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $7F $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0CB
.db $FF $F0 $00 $F0 $FF $E0 $00 $E0 $FF $C0 $00 $C0 $FF $00 $04 $00 $FF $00 $4D $00 $FF $00 $60 $00 $FF $00 $00 $00 $FF $00 $02 $02
; Tile index $0CC
.db $FF $00 $40 $00 $FF $00 $17 $00 $FF $00 $1F $00 $FF $00 $9F $00 $FF $00 $13 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0CD
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $F3 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0CE
.db $FF $07 $00 $07 $FF $07 $E0 $07 $FF $03 $F0 $03 $FF $03 $F8 $03 $FF $03 $FC $03 $FF $03 $7C $03 $FF $00 $00 $00 $FF $00 $03 $03
; Tile index $0CF
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FF $FE $00 $FE $FF $FE $00 $FE $FF $FE $00 $FE $FF $00 $00 $00
; Tile index $0D0
.db $FF $C0 $1F $DE $FF $80 $1F $9F $FF $80 $3F $9E $FF $00 $3F $3F $FF $00 $7F $3F $FF $00 $08 $08 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D1
.db $FF $00 $FF $60 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $30 $FF $00 $C0 $40 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D2
.db $FF $00 $00 $00 $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D3
.db $FF $00 $1F $1F $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D4
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D5
.db $FF $00 $1C $1C $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D6
.db $FF $00 $07 $07 $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D7
.db $FF $00 $80 $80 $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D8
.db $FF $00 $0F $0F $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D9
.db $FF $00 $00 $00 $FF $00 $81 $81 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0DA
.db $FF $00 $3F $3F $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0DB
.db $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0DC
.db $FF $00 $00 $00 $FF $00 $F0 $F0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0DD
.db $FF $00 $00 $00 $FF $00 $20 $20 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
