; Tile index $060
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $061
.db $00 $FF $00 $00 $03 $FC $00 $00 $0F $F3 $03 $00 $1F $EF $0C $03 $3F $DF $10 $0F $3F $DF $00 $1F $7F $BF $20 $1F $7F $BF $00 $3F
; Tile index $062
.db $00 $FF $00 $00 $C0 $3F $00 $00 $F0 $CF $C0 $00 $F8 $F7 $30 $C0 $FC $FB $08 $F0 $FE $FD $04 $F8 $FF $FE $02 $FC $FF $FE $02 $FC
; Tile index $063
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $0C $F3 $00 $00
; Tile index $064
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00
; Tile index $065
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $7E $81 $00 $00 $FF $7E $7E $00
; Tile index $066
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $01 $01
; Tile index $067
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $07 $F8 $07 $07 $EF $10 $EF $EF
; Tile index $068
.db $00 $FF $00 $00 $01 $FE $00 $00 $07 $F9 $01 $00 $0F $F7 $06 $01 $3F $CF $08 $07 $7F $BF $30 $0F $7F $BF $00 $3F $FF $7F $40 $3F
; Tile index $069
.db $7F $80 $00 $00 $FF $7F $7F $00 $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $06A
.db $FF $7F $40 $3F $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $06B
.db $FF $FF $01 $FE $FF $FF $01 $FE $FF $FF $01 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $06C
.db $80 $7F $00 $00 $80 $7F $00 $00 $80 $7F $00 $00 $E0 $9F $80 $00 $F0 $EF $60 $80 $F8 $F7 $10 $E0 $FB $F4 $13 $E3 $FF $F8 $0B $F3
; Tile index $06D
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $0F $F0 $0F $0F $7F $80 $7F $7F $FF $00 $F8 $F8 $FF $07 $C7 $C0
; Tile index $06E
.db $00 $FF $00 $00 $00 $FF $00 $00 $03 $FC $00 $00 $1F $E3 $1B $18 $FF $07 $F4 $F3 $FF $0F $E8 $E7 $FF $1F $10 $0F $FF $FF $C0 $3F
; Tile index $06F
.db $7F $8C $0C $00 $FF $7F $73 $0C $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $070
.db $80 $7F $00 $00 $E0 $9F $80 $00 $F0 $EF $60 $80 $F8 $F7 $10 $E0 $FC $FB $08 $F0 $FE $FD $04 $F8 $FF $FC $04 $F8 $FF $FF $07 $F8
; Tile index $071
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $18 $E7 $00 $00 $FC $1B $18 $00 $FF $FC $E5 $19 $FF $FE $02 $FC
; Tile index $072
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $0F $F0 $0F $0F $7F $80 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $073
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $C0 $3F $C0 $C0 $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $074
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $80 $80 $C0 $3F $C0 $C0
; Tile index $075
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $01 $01 $1F $E0 $1F $1F $3F $C0 $3F $3F $3F $C0 $3F $3F
; Tile index $076
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $C0 $3F $C0 $C0 $E0 $1F $E0 $E0 $E0 $1F $E0 $E0 $FE $01 $FE $FE
; Tile index $077
.db $03 $FD $01 $00 $07 $FB $02 $01 $0F $F7 $04 $03 $1F $EF $08 $07 $3F $DF $10 $0F $7F $BF $20 $1F $FF $7F $40 $3F $FF $FF $80 $7F
; Tile index $078
.db $FF $FF $81 $7E $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $079
.db $80 $7F $00 $00 $C0 $BF $80 $00 $C3 $BC $80 $00 $CF $B3 $83 $00 $FF $8F $8C $03 $FF $DF $50 $8F $FF $FF $20 $DF $FF $FF $00 $FF
; Tile index $07A
.db $00 $FF $00 $00 $00 $FF $00 $00 $F0 $0F $00 $00 $FC $F3 $F0 $00 $FF $FC $0C $F0 $FF $FF $03 $FC $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $07B
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $C1 $BE $81 $01 $C3 $BC $83 $03
; Tile index $07C
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $01 $01 $37 $C8 $37 $37 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $07D
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $F0 $0F $F0 $F0 $F8 $07 $F8 $F8 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $07E
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $C0 $3F $C0 $C0 $E0 $1F $E0 $E0 $E0 $1F $E0 $E0
; Tile index $07F
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $03 $FC $00 $00 $1F $E3 $03 $00 $7F $9F $1C $03
; Tile index $080
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $3E $C1 $00 $00 $FF $3E $3E $00 $FF $FF $C1 $3E $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $081
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $C0 $BF $80 $00 $E0 $DF $40 $80 $F0 $CF $40 $80
; Tile index $082
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $07 $F8 $07 $07 $0F $F0 $0F $0F $1F $E0 $1F $1F
; Tile index $083
.db $07 $F8 $07 $07 $07 $F8 $07 $07 $3F $C0 $3F $3F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FE $FF $01 $FD $FC
; Tile index $084
.db $FF $00 $FE $FE $FF $00 $FE $FE $FF $01 $FD $FC $FF $01 $FC $FD $FF $01 $FC $FD $FF $03 $FA $F9 $FF $03 $00 $03 $FF $FF $FC $03
; Tile index $085
.db $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $086
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $087
.db $FF $F8 $0B $F3 $FF $F8 $08 $F0 $FF $FB $0B $F0 $FF $FF $04 $FB $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $088
.db $FF $37 $B0 $87 $FF $7F $48 $37 $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $089
.db $FF $00 $7F $7F $FF $80 $BC $3C $FF $C3 $4B $88 $FF $F7 $34 $C3 $FF $FF $08 $F7 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08A
.db $FF $00 $FF $FF $FF $00 $61 $61 $FF $9C $9C $00 $FF $FE $62 $9C $FF $FF $01 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08B
.db $E3 $1C $E3 $E3 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F0 $F0 $FF $0F $0F $00 $FF $BF $B1 $0E $FF $FF $40 $BF $FF $FF $00 $FF
; Tile index $08C
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $78 $78 $FF $07 $77 $70 $FF $8F $88 $07 $FF $FF $70 $8F
; Tile index $08D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $E0 $E0 $FF $1F $5F $40 $FF $BF $A0 $1F $FF $FF $40 $BF $FF $FF $00 $FF
; Tile index $08E
.db $01 $FE $00 $00 $81 $7E $80 $80 $EF $11 $E1 $E0 $FF $0F $CE $C1 $FF $3F $30 $0F $FF $FF $C0 $3F $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08F
.db $E3 $DC $43 $83 $F7 $E8 $26 $C6 $FF $F1 $11 $E0 $FF $FB $0A $F1 $FF $FF $04 $FB $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $090
.db $FF $00 $07 $07 $FF $F8 $F8 $00 $FF $FB $0B $F0 $FF $FF $04 $FB $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $091
.db $FF $00 $1F $1F $FF $E0 $EF $0F $FF $F0 $17 $E7 $FF $F8 $0B $F3 $FF $F8 $0B $F3 $FF $FC $05 $F9 $FF $FC $04 $F8 $FF $FF $03 $FC
; Tile index $092
.db $FE $01 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FA $FA $FF $05 $05 $00 $FF $FF $FA $05 $FF $FF $00 $FF
; Tile index $093
.db $01 $FE $00 $00 $0F $F1 $01 $00 $3F $CF $0E $01 $FF $3F $B0 $8F $FF $7F $40 $3F $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $094
.db $80 $7F $00 $00 $E1 $9E $80 $00 $F3 $ED $61 $80 $FF $F1 $10 $E1 $FF $F7 $16 $E1 $FF $FF $08 $F7 $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $095
.db $FF $7F $60 $1F $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $096
.db $F7 $E8 $20 $C0 $FF $E7 $27 $C0 $FF $FF $18 $E7 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $097
.db $9F $60 $03 $03 $FF $9C $9D $01 $FF $FE $62 $9C $FF $FF $01 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $098
.db $FF $03 $F8 $FB $FF $03 $F8 $FB $FF $03 $E0 $E3 $FF $1F $1C $03 $FF $FF $E0 $1F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $099
.db $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $09A
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
