; Tile index $060
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $061
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $00 $FC $FC $F3 $03 $F3
; Tile index $062
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $07 $FF $FF $F8
; Tile index $063
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $00 $3F $3F $C0 $C0 $C0
; Tile index $064
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FF $F9 $01 $F8 $FF $F7 $07 $F0 $FF $F7 $07 $F0 $FF $EF $0F $E0 $FF $DF $1F $C0
; Tile index $065
.db $F0 $C0 $00 $CF $C0 $00 $00 $3F $00 $00 $00 $FF $80 $80 $80 $7F $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F
; Tile index $066
.db $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $01 $FE $03 $03 $03 $FC $03 $03 $03 $FC $07 $07 $07 $F8
; Tile index $067
.db $01 $3E $3E $FE $00 $01 $01 $FF $00 $00 $00 $FF $00 $00 $00 $FF $E0 $E0 $E0 $1F $F0 $F0 $F0 $0F $F8 $F8 $F8 $07 $FC $FC $FC $03
; Tile index $068
.db $FF $3F $00 $3F $7F $8F $80 $8F $1F $63 $60 $E3 $07 $18 $18 $F8 $00 $07 $07 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF
; Tile index $069
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $00 $3F $3F $DF $C0 $DF $3F $27 $20 $C7 $3F $31 $30 $C1
; Tile index $06A
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FE $FD $00 $FC $FC $FA $00 $F9 $FC $FA $00 $F9 $FC $FA $00 $F9
; Tile index $06B
.db $FF $BF $3F $80 $FF $7F $7F $00 $FF $7F $7F $00 $3F $3F $3F $C0 $0F $0F $0F $F0 $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF
; Tile index $06C
.db $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F $80 $80 $80 $7F $80 $80 $80 $7F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF
; Tile index $06D
.db $FC $FC $FC $03 $FC $FC $FC $03 $F8 $F8 $F8 $07 $F0 $F0 $F0 $0F $00 $00 $00 $FF $00 $00 $00 $FF $00 $03 $00 $FC $03 $0C $00 $F0
; Tile index $06E
.db $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $1F $00 $E0 $1F $E0 $00 $00 $FF $00 $1F $1F
; Tile index $06F
.db $7F $7C $7C $80 $7F $7F $7F $80 $7F $7F $7F $80 $7F $7F $7F $80 $00 $3F $3F $C0 $3F $C0 $00 $00 $FF $00 $3F $3F $FF $00 $FF $FF
; Tile index $070
.db $FF $FF $00 $FF $FF $7F $00 $7F $FF $BF $80 $3F $FF $DF $C0 $1F $1F $EF $E0 $0F $FF $0F $00 $0F $FF $07 $F0 $F7 $FF $07 $F0 $F7
; Tile index $071
.db $F8 $F4 $00 $F3 $F0 $E8 $00 $E7 $F0 $E8 $00 $E7 $F0 $E8 $00 $E7 $F0 $E8 $00 $E7 $F1 $E9 $01 $E6 $F3 $EB $03 $E4 $F7 $EF $07 $E0
; Tile index $072
.db $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $80 $80 $80 $7F $E0 $E0 $E0 $1F $F0 $F0 $F0 $0F
; Tile index $073
.db $00 $00 $00 $FF $03 $03 $03 $FC $07 $07 $07 $F8 $0F $0F $0F $F0 $0F $0F $0F $F0 $1C $1F $1F $E0 $13 $1C $1C $E0 $0F $10 $13 $E3
; Tile index $074
.db $38 $38 $38 $C7 $FC $FF $FC $00 $E2 $FD $FC $00 $DF $E0 $E3 $03 $BF $C0 $DF $1F $7F $80 $BF $3F $FF $00 $7F $7F $FF $00 $FF $FF
; Tile index $075
.db $0F $70 $03 $83 $7F $80 $0F $0F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $076
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $077
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FC $FC
; Tile index $078
.db $FF $07 $F0 $F7 $FF $07 $F0 $F7 $FF $0F $E0 $EF $FF $1F $C0 $DF $FF $1F $C0 $DF $FF $3F $80 $BF $FF $7F $00 $7F $FF $FF $00 $FF
; Tile index $079
.db $E7 $D7 $07 $C8 $E7 $D7 $07 $C8 $EF $DF $0F $C0 $E7 $D7 $07 $C8 $E3 $D3 $03 $CC $E0 $D0 $00 $CF $E0 $D0 $00 $CF $E0 $D0 $00 $CF
; Tile index $07A
.db $F0 $F0 $F0 $0F $F8 $F9 $F8 $06 $F9 $FA $F8 $04 $F3 $F4 $F1 $09 $E7 $E8 $E3 $13 $CF $D0 $C7 $27 $1F $20 $0F $CF $3F $40 $1F $9F
; Tile index $07B
.db $3F $40 $07 $87 $7F $80 $1F $1F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $07C
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F8 $F8 $FF $00 $E7 $E7 $FF $00 $9F $9F $FF $00 $3F $3F
; Tile index $07D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $C0 $C0 $FF $00 $3F $3F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $07E
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F $FF $00 $9E $9E $FF $00 $E8 $E8 $FF $07 $F0 $F7 $FF $04 $F0 $F4
; Tile index $07F
.db $FF $03 $F8 $FB $FF $07 $F0 $F7 $FF $0F $C0 $CF $FF $3F $00 $3F $FF $FE $00 $FE $FE $F1 $01 $F1 $F0 $00 $00 $0F $00 $00 $00 $FF
; Tile index $080
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $1F $FF $FF $E0 $1F $1F $1F $E0 $1F $1F $1F $E0
; Tile index $081
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $1F $00 $1F $FF $E7 $E0 $07 $E7 $FB $F8 $1B $E3 $E5 $E4 $1D
; Tile index $082
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $00 $FF $FF $F0 $00 $FF
; Tile index $083
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $084
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $00 $FF $FF $07 $00 $FF $FF $01 $00 $FF
; Tile index $085
.db $E0 $D8 $00 $C7 $E0 $DF $00 $C0 $E1 $DE $00 $C0 $E3 $DC $01 $C1 $E7 $D8 $03 $C3 $FF $E0 $07 $E7 $FF $E0 $0F $EF $FF $E0 $0F $EF
; Tile index $086
.db $7F $80 $3F $3F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $087
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FE $FE
; Tile index $088
.db $FF $00 $7F $7F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FF $FF $FF $01 $FF $FF $FF $03 $FF $FF
; Tile index $089
.db $FF $07 $FF $FF $FF $1F $FF $FF $FF $3F $FF $FF $FF $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08A
.db $FE $C0 $F0 $F1 $FC $F8 $F8 $FB $FC $F8 $F8 $FB $FE $F9 $F8 $F8 $FE $FD $FC $FC $FE $FD $FC $FC $FF $FC $FC $FC $FF $FC $FD $FD
; Tile index $08B
.db $00 $00 $00 $FF $08 $08 $08 $F7 $3C $3C $3C $C3 $3C $3C $3C $C3 $00 $FF $3C $00 $FF $00 $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08C
.db $07 $07 $07 $F8 $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $E0 $00 $1F $E0 $1C $00 $03 $FC $03 $E0 $E0 $FF $00 $FC $FC
; Tile index $08D
.db $81 $82 $82 $7E $00 $01 $01 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $01 $FE $03 $03 $03 $FC $03 $C3 $03 $3C $82 $62 $02 $1D
; Tile index $08E
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F8 $07 $F8 $FF $E7 $1F $E0
; Tile index $08F
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E1 $1E $E1 $FF $1E $FF $00 $E1 $FF $E1 $1E $00 $FF $00 $FF
; Tile index $090
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $01 $FE $FF $41 $BF $40 $FE $BF $FE $01 $40 $FF $40 $BF
; Tile index $091
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $EE $10 $EF $FF $10 $F8 $07 $FF $F0 $FC $03 $0F $FC $0E $F1 $07 $FC $06 $F9
; Tile index $092
.db $FF $FE $00 $FF $FF $F0 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FC $03
; Tile index $093
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $094
.db $FF $7F $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $095
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $00 $FF $FF $0F $00 $FF $FF $03 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $096
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E0 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $097
.db $FF $FF $00 $FF $FF $FE $00 $FF $FF $F0 $00 $FF $FF $E0 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $098
.db $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $099
.db $FF $3F $00 $FF $FF $1F $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $09A
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FF $FF $F8 $00 $FF $FF $20 $00 $FF $FF $00 $00 $FF
; Tile index $09B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $09C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $00 $FF $FF $03 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $09D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $30 $00 $FF
; Tile index $09E
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FF $FF $F0 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF
; Tile index $09F
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $07 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A0
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7E $00 $FF $FF $18 $00 $FF
; Tile index $0A1
.db $FF $FF $00 $FF $FF $FE $00 $FF $FF $F8 $00 $FF $FF $E0 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A2
.db $FF $80 $07 $F7 $FF $00 $03 $FB $FF $00 $00 $FC $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A3
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7C $7C $FF $00 $00 $83 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A4
.db $FF $00 $FC $FC $FF $00 $E0 $E2 $FF $00 $00 $1E $FF $00 $00 $FE $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A5
.db $FF $03 $FF $FF $FF $03 $FF $FF $FF $07 $FF $FF $FF $07 $FF $FF $FF $07 $7F $7F $FF $07 $7F $7F $FF $07 $7F $7F $FF $07 $7F $7F
; Tile index $0A6
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0A7
.db $FF $FC $FC $FC $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE
; Tile index $0A8
.db $FF $00 $FF $FF $FF $00 $F0 $F0 $FF $00 $EF $EF $FF $00 $1F $1F $FF $C0 $1F $DF $FF $80 $1F $DF $FF $00 $3F $BF $FF $00 $3F $BF
; Tile index $0A9
.db $FF $00 $FF $FF $FF $00 $7F $7F $FF $00 $8F $8F $FF $00 $F7 $F7 $FF $00 $FB $FB $FF $00 $FD $FD $FF $00 $FD $FD $FF $00 $FE $FE
; Tile index $0AA
.db $E0 $10 $80 $8F $F0 $0C $E0 $E3 $F8 $06 $F0 $F1 $FC $02 $F8 $F9 $FE $01 $FC $FC $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $E0 $E1
; Tile index $0AB
.db $F8 $5F $B8 $47 $E0 $9F $E0 $1F $60 $FF $60 $9F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0AC
.db $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0AD
.db $07 $FE $07 $F8 $01 $FF $01 $FE $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0AE
.db $FF $F8 $FF $00 $07 $FF $07 $F8 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0AF
.db $FF $00 $C0 $3F $FF $C0 $FC $03 $3F $FC $3E $C1 $03 $FC $03 $FC $03 $FF $03 $FC $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0B0
.db $FF $00 $02 $FD $FF $02 $07 $F8 $FD $07 $7D $82 $F8 $7F $F8 $07 $80 $FF $80 $7F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0B1
.db $FF $00 $80 $7F $FF $80 $C0 $3F $7F $C0 $60 $9F $7F $C0 $71 $8E $3F $F1 $3F $C0 $0F $FF $0F $F0 $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0B2
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $80 $7F $FF $0F $F0 $00 $FF $F7 $F8 $00 $1F $F3 $1C $E0
; Tile index $0B3
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B4
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $01 $FE $FF $FD $03 $00 $FE $FD $02 $01 $FE $F3 $0E $01
; Tile index $0B5
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $03 $FC $FF $01 $03 $FC $FC $03 $8C $73 $FC $AF $DC $03 $70 $DF $70 $8F $20 $FF $20 $DF
; Tile index $0B6
.db $FF $07 $7F $7F $FF $07 $7F $7F $FF $07 $FF $7F $FF $07 $BF $3F $FF $87 $DF $1F $7F $C2 $6F $8E $3F $E1 $3F $C0 $1E $FF $1E $E1
; Tile index $0B7
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7C $FF $7C $FF $A3 $FF $20 $7C $DF $7C $83 $20 $FF $20 $DF
; Tile index $0B8
.db $FF $FE $FE $FE $FF $FE $FE $FE $FF $98 $FA $98 $FF $6B $FF $08 $BE $F3 $BE $41 $0C $FF $0C $F3 $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0B9
.db $FF $00 $3F $3F $FF $00 $FF $BF $FF $40 $FF $1F $FF $E0 $FF $00 $1F $FF $1F $E0 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $0BA
.db $FF $00 $FE $FE $FF $00 $FC $FD $FF $00 $F8 $F1 $FF $04 $FF $C0 $FF $38 $FF $07 $CC $F3 $CC $3F $30 $CF $30 $FF $60 $9F $60 $FF
; Tile index $0BB
.db $FF $00 $00 $1F $FF $00 $00 $FF $FF $00 $10 $EF $FF $10 $BC $C3 $EF $BC $EE $11 $43 $FE $43 $BC $01 $FF $01 $FE $00 $FF $00 $FF
; Tile index $0BC
.db $00 $FF $00 $FF $00 $FF $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0BD
.db $0F $FC $0F $F0 $03 $FF $03 $FC $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0BE
.db $FF $7F $80 $00 $FF $BF $C0 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0BF
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C0
.db $FC $E7 $1C $03 $F0 $EF $10 $0F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C1
.db $01 $FE $01 $FF $06 $F9 $06 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C2
.db $80 $7F $80 $FF $00 $FF $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C3
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
