; Tile index $060
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $061
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $0F $00 $F0 $F0 $3F $0F $C0 $C0 $7F $1F $80 $8F $7F $3F $80 $9F
; Tile index $062
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $E0 $00 $1F $1F $F8 $E0 $07 $07 $FF $E8 $00 $80 $FF $FF $00 $E0
; Tile index $063
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $3F $3F $F8 $80 $07 $07
; Tile index $064
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $03 $01 $FC $FD $07 $03 $F8 $FA $0F $07 $F0 $F5
; Tile index $065
.db $FF $7F $00 $5F $FF $7F $00 $0E $FF $7F $00 $08 $FF $3F $00 $03 $FF $FF $00 $BF $FF $FF $00 $3F $FF $FF $00 $7F $FF $FF $00 $FE
; Tile index $066
.db $FF $FF $00 $19 $FF $FF $00 $47 $FF $FF $00 $FB $FF $FF $00 $FC $FF $FF $00 $F2 $FF $FF $00 $E7 $FF $FF $00 $9F $FF $FF $00 $1F
; Tile index $067
.db $FF $F8 $00 $40 $FF $FF $00 $F0 $FF $FF $00 $FD $FF $FF $00 $E7 $FF $FF $00 $7F $FF $FF $00 $7F $FF $FF $00 $BF $FF $FF $00 $92
; Tile index $068
.db $80 $00 $7F $7F $80 $80 $7F $7F $C0 $80 $3F $3F $E0 $C0 $1F $1F $E0 $C0 $1F $9F $E0 $C0 $1F $1F $C0 $80 $3F $BF $80 $00 $7F $7F
; Tile index $069
.db $0F $07 $F0 $F3 $1F $0F $E0 $E3 $1F $0F $E0 $E7 $1F $0F $E0 $EF $3F $1F $C0 $CF $3E $1E $C1 $CC $7E $3C $81 $9C $7D $3C $82 $B1
; Tile index $06A
.db $FF $FF $00 $FC $FF $FE $00 $F1 $FF $E8 $00 $F7 $E7 $E0 $18 $87 $FB $C8 $0C $3B $FC $84 $07 $7C $FF $03 $03 $FF $FE $02 $03 $FE
; Tile index $06B
.db $FF $1F $00 $E7 $FF $0F $00 $F7 $EF $0F $10 $E3 $9F $07 $60 $83 $4F $03 $B0 $31 $87 $03 $78 $79 $47 $03 $B8 $39 $43 $01 $BC $3C
; Tile index $06C
.db $FF $FF $00 $DB $FF $FF $00 $EB $FF $FF $00 $EB $FF $FF $00 $EB $FF $FF $00 $EB $FF $FF $00 $E8 $FF $F1 $00 $E0 $F9 $F0 $06 $E6
; Tile index $06D
.db $C0 $80 $3F $3F $C0 $80 $3F $3F $C0 $80 $3F $3F $C0 $80 $3F $3F $C0 $80 $3F $3F $C0 $80 $3F $3F $C0 $80 $3F $BF $80 $00 $7F $7F
; Tile index $06E
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $1C $00 $E3 $E3
; Tile index $06F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $30 $00 $CF $CF
; Tile index $070
.db $F8 $70 $07 $10 $FB $73 $07 $23 $F7 $40 $08 $07 $57 $00 $A8 $A7 $21 $00 $DE $C1 $4E $0E $BF $8E $5F $01 $A1 $9F $5F $00 $A0 $9F
; Tile index $071
.db $39 $08 $CE $38 $C6 $C0 $F9 $C1 $F2 $30 $3D $F1 $F4 $10 $1B $F3 $E8 $20 $37 $E7 $D0 $40 $6F $CF $20 $00 $DF $1F $E0 $C0 $DF $DF
; Tile index $072
.db $83 $01 $7C $7C $01 $00 $FE $FE $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $073
.db $F8 $F0 $07 $F7 $F8 $F0 $07 $67 $F0 $60 $0F $4F $F0 $60 $0F $0F $70 $20 $8F $8F $70 $20 $8F $8F $20 $00 $DF $DF $00 $00 $FF $FF
; Tile index $074
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $0C $00 $F3 $F3 $1F $0C $EC $E0 $3F $1F $D3 $CC
; Tile index $075
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $03 $01 $FD $FC $07 $03 $FA $F9 $8F $07 $74 $73 $DF $8F $A8 $27
; Tile index $076
.db $00 $00 $FF $FF $00 $00 $FF $FF $7C $00 $83 $83 $FF $7C $7C $00 $FF $FF $83 $7C $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $077
.db $3E $1C $DD $C1 $7F $3E $A2 $9C $FF $7F $41 $3E $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $078
.db $F8 $30 $37 $07 $FC $F8 $CB $33 $FC $F8 $0B $F3 $FF $FC $04 $F8 $FF $FF $03 $FC $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $079
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $03 $01 $FD $FC $07 $03 $FA $F9 $3F $07 $C4 $C3
; Tile index $07A
.db $00 $00 $FF $FF $0F $00 $F0 $F0 $7F $0F $8F $80 $FF $7F $70 $0F $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $07B
.db $7F $0C $8C $80 $FF $7F $73 $0C $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $07C
.db $DF $00 $20 $1F $FF $81 $81 $1F $FE $E2 $63 $8E $FD $F4 $16 $E4 $FE $F8 $09 $F1 $FE $FC $05 $F9 $FF $FC $04 $F8 $FF $FF $03 $FC
; Tile index $07D
.db $A0 $80 $DF $9F $40 $00 $BF $3F $80 $00 $7F $7F $00 $00 $FF $FF $18 $00 $E7 $E7 $FC $18 $1B $03 $FE $FC $E5 $19 $FF $FE $02 $FC
; Tile index $07E
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $01 $00 $FE $FE $03 $01 $FD $FC
; Tile index $07F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $3C $00 $C3 $C3 $FF $3C $3C $00 $FF $FF $C3 $3C $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $080
.db $3F $1F $C0 $DF $7F $3F $A0 $9F $7F $3F $80 $BF $3F $1F $C0 $DF $1F $0F $E0 $EF $DF $07 $20 $27 $FF $DF $D8 $07 $FF $FF $20 $DF
; Tile index $081
.db $FF $CF $40 $8F $FF $FF $30 $CF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $082
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $083
.db $7F $3F $B8 $87 $FF $7F $40 $3F $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $084
.db $FF $FF $01 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $085
.db $80 $00 $7F $7F $C3 $80 $BC $3C $F7 $C3 $4B $88 $FF $F7 $34 $C3 $FF $FF $08 $F7 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $086
.db $00 $00 $FF $FF $9C $00 $63 $63 $FF $9C $9C $00 $FF $FF $63 $9C $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $087
.db $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $7F $7F $FF $80 $9F $1F $FF $E0 $67 $87 $FF $F8 $08 $F3 $FE $FD $04 $F9 $FF $FE $02 $FC
; Tile index $088
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $FF $00 $FF $80 $7F $00 $7F
; Tile index $089
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $08A
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $F8 $0F $F7 $07 $F0 $0F $F7 $00 $F7
; Tile index $08B
.db $07 $03 $FA $F9 $3F $07 $C4 $C3 $7F $3F $B8 $87 $FF $7F $40 $3F $FF $7F $00 $7F $FF $FF $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08C
.db $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $08D
.db $FF $FF $01 $FE $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $08E
.db $C0 $BF $80 $3F $E0 $DF $00 $1F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $08F
.db $00 $FF $00 $FF $00 $FF $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $090
.db $1F $EF $08 $E7 $1F $EF $00 $E0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $091
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
