; Tile index $060
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $061
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $062
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FF $FC $FC $FC $FF $FD $FD $FC $FF $FB $FB $F8 $FF $E7 $E7 $E0 $FF $DF $DF $C0
; Tile index $063
.db $FF $C0 $C0 $C0 $FF $3F $3F $00 $FF $7F $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $064
.db $FF $7F $7F $7F $FF $1F $1F $1F $FF $E7 $E7 $07 $FF $F3 $F3 $03 $FF $FC $FC $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $065
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F $FF $8F $8F $0F $FF $F3 $F3 $03 $FF $FC $FC $00
; Tile index $066
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FF $FC $FD $FC $FF $F0 $F3 $F0
; Tile index $067
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FF $FD $FD $FC $FF $F9 $F9 $F8 $FF $F0 $F0 $F0 $FF $E0 $EF $E0 $FF $C0 $DF $C0
; Tile index $068
.db $FF $BF $BF $80 $FF $7F $7F $00 $FF $F8 $F8 $00 $FF $C0 $C7 $00 $FF $00 $3F $00 $FF $00 $FF $00 $FF $00 $FF $00 $E0 $1F $FF $00
; Tile index $069
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $18 $18 $00 $FF $00 $C7 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $01 $FE $FF $00
; Tile index $06A
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $3F $3F $00 $FF $0F $CF $00 $FF $07 $F7 $00 $FF $03 $FB $00 $FF $00 $FC $00
; Tile index $06B
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $E0 $E2 $00 $FF $00 $1F $00
; Tile index $06C
.db $FF $0F $0F $0F $FF $E0 $E0 $00 $FF $FF $FF $00 $FF $FE $FE $00 $FF $F0 $F1 $00 $FF $C0 $CF $00 $FF $00 $3F $00 $F0 $0F $FF $00
; Tile index $06D
.db $FF $FF $FF $FF $FF $7F $7F $7F $FF $80 $80 $00 $FF $00 $3F $00 $FF $00 $FF $00 $C0 $3F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $06E
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $FF $3F $3F $3F $3F $DF $DF $1F $1F $E7 $E7 $07 $07 $F8 $F8 $00 $03 $FC $FF $00
; Tile index $06F
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F
; Tile index $070
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FC $FC $FE $F9 $F9 $F8
; Tile index $071
.db $FF $FF $FF $FF $FF $FC $FC $FC $FF $FB $FB $F8 $FF $F0 $F0 $F0 $FF $F0 $F7 $F0 $FF $00 $0F $00 $FC $03 $FF $00 $00 $FF $FF $00
; Tile index $072
.db $FF $0F $0F $0F $FF $F1 $F1 $01 $FF $FE $FE $00 $FF $3F $3F $00 $FF $1F $DF $00 $FF $0E $EE $00 $3F $C0 $F1 $00 $1F $E0 $FF $00
; Tile index $073
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F $FF $CF $CF $0F $FF $03 $13 $03 $FF $00 $F8 $00 $FF $00 $FF $00
; Tile index $074
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FC $FC $FF $F8 $FB $F8 $FF $E0 $E7 $E0 $FF $80 $9F $80 $FE $01 $7F $00
; Tile index $075
.db $FF $C0 $CF $C0 $FF $80 $BF $80 $FF $00 $7F $00 $FC $03 $FF $00 $F0 $0F $FF $00 $C0 $3F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $076
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FF $FC $FD $FC $FF $F8 $FB $F8 $FF $F0 $F7 $F0 $FC $E3 $EF $E0 $F0 $CF $DF $C0
; Tile index $077
.db $FF $80 $BF $80 $FE $01 $7F $00 $F8 $07 $FF $00 $F0 $0F $FF $00 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $078
.db $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $079
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07A
.db $FF $00 $FF $00 $3F $C0 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07B
.db $FE $01 $FF $00 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07C
.db $FF $0F $CF $0F $7F $87 $F7 $07 $3F $C1 $F1 $01 $1F $E0 $FE $00 $1F $E0 $FF $00 $07 $F8 $FF $00 $03 $FC $FF $00 $00 $FF $FF $00
; Tile index $07D
.db $FF $FF $FF $FF $FF $FC $FC $FC $FF $F8 $FB $F8 $FF $60 $67 $60 $FF $00 $1F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $07E
.db $FF $7F $7F $7F $FF $3F $BF $3F $FF $07 $C7 $07 $FF $01 $F9 $01 $FF $00 $FE $00 $FF $00 $FF $00 $FF $00 $FF $00 $87 $78 $FF $00
; Tile index $07F
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $FF $1F $9F $1F $FF $07 $E7 $07 $FF $00 $F8 $00
; Tile index $080
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00
; Tile index $081
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $60 $60 $60
; Tile index $082
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FC $FC $FC $F3 $F3 $F0 $F0 $8F $8F $80 $80 $7F $7F $00
; Tile index $083
.db $F8 $E7 $E7 $E0 $F0 $CF $CF $C0 $C0 $BF $BF $80 $80 $7F $7F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $084
.db $0F $F0 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $085
.db $FF $00 $FF $00 $3F $C0 $FF $00 $0F $F0 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $086
.db $FF $0F $CF $0F $FF $01 $F9 $01 $FF $00 $FE $00 $0F $F0 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $087
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F $FF $03 $C3 $03 $07 $F8 $F8 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $088
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $F8 $F8 $FF $C0 $C7 $C0 $C0 $3F $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $089
.db $FF $FC $FC $FC $FF $C0 $C1 $C0 $FF $00 $3F $00 $FF $00 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $08A
.db $FC $03 $FF $00 $F0 $0F $FF $00 $C0 $3F $FF $00 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $08B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $C1 $C1 $C1 $FF $80 $BE $80 $FF $00 $7F $00 $FF $00 $FF $00
; Tile index $08C
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $07 $07 $07 $FF $00 $F8 $00 $FF $00 $FF $00
; Tile index $08D
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $FF $0F $CF $0F
; Tile index $08E
.db $FF $FF $FF $FF $FF $FE $FE $FE $FE $FD $FD $FC $FC $FB $FB $F8 $F8 $E7 $E7 $E0 $E0 $DF $DF $C0 $C0 $BF $BF $80 $80 $7F $7F $00
; Tile index $08F
.db $C0 $3F $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $090
.db $FF $00 $FF $00 $FF $00 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $091
.db $FF $00 $8F $00 $FC $03 $FF $00 $70 $8F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $092
.db $FF $00 $FF $00 $F8 $07 $FF $00 $F0 $0F $FF $00 $E0 $1F $FF $00 $C0 $3F $FF $00 $C0 $3F $FF $00 $80 $7F $FF $00 $00 $FF $FF $00
; Tile index $093
.db $FF $00 $FF $00 $1F $E0 $FF $00 $01 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $094
.db $FF $07 $E7 $07 $FF $03 $F3 $03 $FF $01 $FD $01 $3F $C0 $FE $00 $1F $E0 $FF $00 $0F $F0 $FF $00 $03 $FC $FF $00 $00 $FF $FF $00
; Tile index $095
.db $FF $FC $FC $FC $FC $FB $FB $F8 $F8 $F7 $F7 $F0 $F0 $CF $CF $C0 $F8 $07 $3F $00 $E0 $1F $FF $00 $80 $7F $FF $00 $00 $FF $FF $00
; Tile index $096
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $0F $F0 $F0 $00 $3F $CF $C0 $00
; Tile index $097
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $1F $E0 $E0 $00 $FF $1F $00 $00 $FF $FF $00 $00
; Tile index $098
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $01 $FE $FE $00 $0F $F1 $F0 $00 $3F $CF $C0 $00
; Tile index $099
.db $00 $FF $FF $00 $00 $FF $FF $00 $0F $F0 $F0 $00 $3F $CF $C0 $00 $FF $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09A
.db $0F $F0 $F0 $00 $FF $0F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09B
.db $E0 $1F $1F $00 $FF $E0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09C
.db $00 $FF $FF $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09D
.db $00 $FF $FF $00 $F8 $07 $07 $00 $FF $F8 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09E
.db $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09F
.db $00 $FF $FF $00 $00 $FF $FF $00 $C0 $3F $3F $00 $FF $C0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A0
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FE $01 $01 $00 $FF $FE $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A1
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $07 $F8 $F8 $00 $FF $07 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A2
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $F0 $0F $0F $00 $FF $F0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A3
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $F8 $07 $07 $00 $FF $F8 $00 $00
; Tile index $0A4
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FE $01 $01 $00
; Tile index $0A5
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $0F $F0 $F0 $00
; Tile index $0A6
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $07 $F8 $F8 $00 $7F $87 $80 $00 $FF $7F $00 $00
; Tile index $0A7
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $01 $FE $FE $00 $FF $01 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A8
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A9
.db $01 $FE $FE $00 $FF $01 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0AA
.db $FF $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0AB
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0AC
.db $7F $BF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0AD
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0AE
.db $FF $FE $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0AF
.db $FC $03 $03 $00 $FF $FC $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B0
.db $00 $FF $FF $00 $E0 $1F $1F $00 $FF $C0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B1
.db $00 $FF $FF $00 $00 $FF $FF $00 $E0 $1F $1F $00 $FF $E0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B2
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B3
.db $00 $FF $FF $00 $07 $F8 $F8 $00 $3F $C7 $C0 $00 $FF $1F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B4
.db $FF $0F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B5
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0B6
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
