; Tile index $060
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $061
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $062
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FF $FF $F8 $FF $FF $FF $FC $FF $FF $FF
; Tile index $063
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $07 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $064
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $FF $FF $FF $3F $FF $FF $FF
; Tile index $065
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FF $FF $E0 $FF $FF $FF $C0 $FF $FF $FF
; Tile index $066
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $38 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $067
.db $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $068
.db $FF $FF $FF $FF $07 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $069
.db $FF $FF $FF $FF $FF $FF $FF $FF $7F $FF $FF $FF $07 $FF $FF $FF $01 $FF $FF $FF $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $06A
.db $E4 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF
; Tile index $06C
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $80 $FF $FF $FF $00 $FF $FF $FF
; Tile index $06D
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $FF $FF $FF $00 $FF $FF $FF
; Tile index $06E
.db $FF $FF $FF $FF $FF $FF $FF $FF $F0 $FF $FF $FF $E0 $FF $FF $FF $E1 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06F
.db $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $F0 $FF $FF $FF $FC $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $070
.db $FF $FF $FF $FF $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $3F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $071
.db $FF $FF $FF $FF $FF $FF $FF $FF $07 $FF $FF $FF $03 $FF $FF $FF $0F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $072
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $F8 $FF $FF $FF
; Tile index $073
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $FF $FF $FF $01 $FF $FF $FF
; Tile index $074
.db $E0 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $075
.db $00 $FF $FF $FF $F0 $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $076
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $077
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $03 $FF $FF $FF
; Tile index $078
.db $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $079
.db $FF $FF $FF $FF $7F $FF $FF $FF $3F $FF $FF $FF $1F $FF $FF $FF $0F $FF $FF $FF $0F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $07A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $FC $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF
; Tile index $07B
.db $E0 $FF $FF $FF $C0 $FF $FF $FF $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $07C
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FF $FF $FF
; Tile index $07D
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $7F $FF $FF $FF $FF $FF $FF $FF
; Tile index $07E
.db $3F $FF $FF $FF $03 $FF $FF $FF $01 $FF $FF $FF $01 $FF $FF $FF $01 $FF $FF $FF $03 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $07F
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $FF $FF $FF $F0 $FF $FF $FF $F0 $FF $FF $FF $E0 $FF $FF $FF
; Tile index $080
.db $FF $FF $FF $FF $F0 $FF $FF $FF $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $081
.db $FF $FF $FF $FF $70 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $082
.db $4F $FF $FF $FF $04 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $083
.db $F0 $FF $FF $FF $FC $FF $FF $FF $7F $FF $FF $FF $1F $FF $FF $FF $1F $FF $FF $FF $03 $FF $FF $FF $03 $FF $FF $FF $07 $FF $FF $FF
; Tile index $084
.db $01 $FF $FF $FF $0F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $085
.db $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF
; Tile index $086
.db $0F $FF $FF $FF $3F $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $FC $FF $FF $FF $FC $FF $FF $FF $F8 $FF $FF $FF $00 $FF $FF $FF
; Tile index $087
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $088
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $FF $FF $FF $1F $FF $FF $FF $07 $FF $FF $FF $3F $FF $FF $FF
; Tile index $089
.db $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08A
.db $E0 $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08B
.db $00 $FF $FF $FF $00 $FF $FF $FF $FC $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08C
.db $00 $FF $FF $FF $00 $FF $FF $FF $30 $FF $FF $FF $F8 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08D
.db $00 $FF $FF $FF $00 $FF $FF $FF $0F $FF $FF $FF $1F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08E
.db $00 $FF $FF $FF $61 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08F
.db $1F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $090
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $EF $EF $EF
; Tile index $091
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FF $FC $FC $FC $FF $FC $FC $FC $FC $FB $FB $FB $FE $FD $FD $FD $FF $FE $FE $FE
; Tile index $092
.db $FF $C7 $C7 $C7 $EF $D7 $D7 $D7 $CF $F7 $F7 $F7 $DF $2F $2F $2F $BF $5F $5F $5F $BF $5F $5F $5F $7F $9F $9F $9F $9F $6F $0F $0F
; Tile index $093
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FE $F9 $F8 $F8 $FE $C9 $C8 $C8
; Tile index $094
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $7F $9E $1E $1E $1F $EE $0E $0E
; Tile index $095
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $DF $DF $DF $FF $0F $0F $0F $FF $06 $66 $66
; Tile index $096
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $F8 $F8 $FF $E0 $E0 $E0 $FF $80 $80 $80 $BC $53 $13 $13
; Tile index $097
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $87 $87 $87 $9F $67 $67 $67 $3F $DF $DF $DF $FF $3F $3F $3F $FF $FF $FF $FF $FF $7F $7F $7F
; Tile index $098
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FE $FD $FC $FC
; Tile index $099
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $DF $DF $DF $FF $07 $07 $07 $8F $77 $67 $67 $3F $CF $4F $4F $7F $BF $3F $3F
; Tile index $09A
.db $FF $81 $81 $81 $DB $E4 $C8 $C8 $E3 $DC $C0 $C0 $E3 $9C $80 $80 $C0 $BF $80 $80 $C0 $BF $80 $80 $C0 $BF $80 $80 $C5 $BA $80 $80
; Tile index $09B
.db $FF $80 $80 $80 $FF $00 $00 $00 $FF $00 $00 $00 $FA $05 $00 $00 $70 $8F $00 $00 $80 $7F $00 $00 $C0 $3F $00 $00 $80 $7F $00 $00
; Tile index $09C
.db $EE $11 $00 $00 $FE $01 $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $09D
.db $36 $C9 $21 $21 $34 $CB $23 $23 $31 $CE $26 $26 $03 $FC $00 $00 $0F $F1 $05 $05 $1F $E1 $15 $15 $1B $E5 $03 $03 $77 $89 $45 $45
; Tile index $09E
.db $7C $BB $BB $BB $FE $7D $7D $7D $FF $7E $7E $7E $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $09F
.db $7F $BF $BF $BF $7F $BF $BF $BF $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FE $F9 $F8 $F8
; Tile index $0A0
.db $FD $FA $F9 $F9 $FF $F8 $FA $FA $F3 $FC $F0 $F0 $F6 $E9 $E0 $E0 $E3 $DC $C0 $C0 $C7 $B9 $85 $85 $87 $79 $05 $05 $07 $F9 $05 $05
; Tile index $0A1
.db $FF $7F $7F $7F $FF $78 $78 $78 $FB $04 $00 $00 $0F $F3 $03 $03 $FF $0F $0F $0F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0A2
.db $FF $F0 $F0 $F0 $F1 $0E $0E $0E $3F $C0 $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0A3
.db $FF $FF $FF $FF $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0A4
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $EF $EF $EF $EF $D7 $C7 $C7 $E7 $98 $80 $80 $E0 $DF $C0 $C0 $E0 $DF $C0 $C0 $F0 $EF $E0 $E0
; Tile index $0A5
.db $C2 $BD $80 $80 $E6 $99 $80 $80 $FC $03 $00 $00 $A0 $5F $00 $00 $A0 $5F $00 $00 $A0 $5F $00 $00 $40 $BF $00 $00 $40 $BF $00 $00
; Tile index $0A6
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0A7
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $0B $F4 $00 $00 $1E $E1 $00 $00
; Tile index $0A8
.db $2F $D1 $29 $29 $07 $F9 $05 $05 $07 $F9 $05 $05 $07 $F9 $05 $05 $03 $FD $01 $01 $3F $C0 $00 $00 $C0 $3F $00 $00 $00 $FF $00 $00
; Tile index $0A9
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FC $FC $FE $F1 $F0 $F0 $F0 $0F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0AA
.db $F8 $E7 $E0 $E0 $E0 $9F $80 $80 $80 $7F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0AB
.db $07 $F9 $05 $05 $07 $F9 $05 $05 $07 $F9 $05 $05 $07 $F9 $05 $05 $07 $F9 $05 $05 $07 $F9 $01 $01 $0F $F3 $0B $0B $0F $F3 $0B $0B
; Tile index $0AC
.db $FF $FF $FF $FF $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0AD
.db $FF $7F $7F $7F $7F $BF $BF $BF $7F $BF $BF $BF $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0AE
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $C7 $C7 $C7 $E7 $DB $DB $DB $C7 $BB $BB $BB $E7 $DB $DB $DB
; Tile index $0AF
.db $F0 $EF $E0 $E0 $E0 $9F $80 $80 $8C $73 $70 $70 $FE $89 $88 $88 $FE $FD $FC $FC $FE $FD $FC $FC $FE $FD $FC $FC $FF $FE $FE $FE
; Tile index $0B0
.db $40 $BF $00 $00 $40 $BF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $40 $BF $00 $00 $C0 $3F $00 $00 $C0 $3F $00 $00 $C0 $3F $00 $00
; Tile index $0B1
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00 $01 $FE $00 $00 $01 $FE $00 $00
; Tile index $0B2
.db $20 $DF $00 $00 $40 $BF $00 $00 $40 $BF $00 $00 $80 $7F $00 $00 $80 $7F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B3
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $01 $01 $01 $FE $01 $01 $03 $FC $02 $02 $03 $FD $01 $01
; Tile index $0B4
.db $3F $C7 $17 $17 $7F $8F $4F $4F $7F $8F $0F $0F $FF $3F $BF $BF $FF $7F $FF $FF $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0B5
.db $FF $E7 $E7 $E7 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0B6
.db $FF $FE $FE $FE $FF $FE $FE $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $EE $EE $EE
; Tile index $0B7
.db $C0 $3F $00 $00 $C0 $3F $00 $00 $C0 $3F $00 $00 $C0 $BF $80 $80 $C0 $BF $80 $80 $80 $7F $00 $00 $80 $7F $00 $00 $80 $7F $00 $00
; Tile index $0B8
.db $01 $FE $00 $00 $01 $FE $00 $00 $01 $FE $00 $00 $01 $FE $00 $00 $01 $FE $00 $00 $01 $FE $00 $00 $01 $FE $00 $00 $01 $FE $00 $00
; Tile index $0B9
.db $03 $FC $00 $00 $1F $E0 $03 $03 $7F $80 $00 $00 $E0 $1F $00 $00 $40 $BF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00 $01 $FE $00 $00
; Tile index $0BA
.db $C7 $3B $03 $03 $EF $17 $C7 $C7 $3F $CF $2F $2F $FF $07 $17 $17 $7F $81 $09 $09 $FB $64 $62 $62 $E7 $D8 $D8 $D8 $FF $E7 $E7 $E7
; Tile index $0BB
.db $FF $FF $FF $FF $FF $F3 $F3 $F3 $FF $F3 $F3 $F3 $F7 $EB $EB $EB $E7 $DB $DB $DB $9F $67 $07 $07 $1F $E0 $00 $00 $FF $00 $00 $00
; Tile index $0BC
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $F3 $F3 $F3 $FF $C3 $C3 $C3 $DF $AF $AF $AF $9F $6F $6F $6F $FF $1F $1F $1F $FF $7F $7F $7F
; Tile index $0BD
.db $EF $D7 $D7 $D7 $CF $B7 $B7 $B7 $C7 $BA $9A $9A $C3 $FC $D0 $D0 $C8 $37 $20 $20 $9F $60 $60 $60 $3F $C7 $C7 $C7 $FF $3E $3E $3E
; Tile index $0BE
.db $80 $7F $00 $00 $80 $7F $00 $00 $80 $7F $00 $00 $F0 $0F $00 $00 $7C $83 $70 $70 $8E $71 $0C $0C $83 $7C $02 $02 $01 $FE $01 $01
; Tile index $0BF
.db $01 $FE $01 $01 $01 $FE $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00
; Tile index $0C0
.db $80 $7F $00 $00 $80 $7F $00 $00 $C0 $3F $80 $80 $C0 $3F $80 $80 $60 $9F $40 $40 $30 $CF $20 $20 $18 $E7 $10 $10 $0E $F1 $08 $08
; Tile index $0C1
.db $03 $FD $01 $01 $07 $FB $03 $03 $0F $F7 $07 $07 $1F $EF $0F $0F $1F $EF $0F $0F $3F $DF $1F $1F $3F $DF $1F $1F $7F $9F $1F $1F
; Tile index $0C2
.db $9F $6F $6F $6F $9F $67 $67 $67 $FF $8F $8F $8F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0C3
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FE $FC $FC $FD
; Tile index $0C4
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $C0 $C0 $C0 $C0 $80 $80 $BF $BF $00 $3F $7F $7F $00 $7F $FF $FF $00 $FF $FF
; Tile index $0C5
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $1F $0F $0F $EF $EF $01 $E1 $F1 $F1 $00 $F0 $FE $FE $00 $FE $FF
; Tile index $0C6
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $0F $0F $1F $07 $07 $E7
; Tile index $0C7
.db $FF $FE $FE $FE $FF $FE $FE $FE $FE $FD $FC $FC $FE $FD $FC $FC $FE $FD $FC $FC $FC $FB $F8 $F8 $FC $FB $F8 $F8 $F8 $F7 $F0 $F0
; Tile index $0C8
.db $C0 $3F $80 $80 $C0 $3F $80 $80 $E0 $1F $80 $80 $60 $9F $60 $60 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0C9
.db $07 $F8 $04 $04 $03 $FC $03 $03 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0CA
.db $80 $7F $00 $00 $FF $00 $80 $80 $7F $80 $7F $7F $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0CB
.db $FF $1F $5F $5F $FF $1F $5F $5F $FF $0F $CF $CF $3F $C7 $27 $27 $3F $C3 $23 $23 $1F $E3 $13 $13 $0F $F3 $0F $0F $07 $F9 $05 $05
; Tile index $0CC
.db $FD $F8 $F9 $FB $FB $F0 $F3 $F7 $FB $F0 $F3 $F7 $FB $F0 $F3 $F7 $F7 $E0 $E7 $EF $F7 $E0 $E7 $EF $EF $C0 $CF $DF $DF $80 $9F $BF
; Tile index $0CD
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CE
.db $E7 $00 $E0 $F8 $F8 $00 $F8 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CF
.db $FF $FF $FF $FF $FF $7F $7F $7F $7F $1F $1F $9F $9F $0F $8F $EF $DF $0F $CF $EF $EF $07 $E7 $F7 $F7 $00 $F0 $F8 $F8 $00 $F8 $FF
; Tile index $0D0
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F
; Tile index $0D1
.db $F8 $F7 $F0 $F0 $F0 $EF $E0 $E0 $F0 $EF $E0 $E0 $E0 $DF $C0 $C0 $FF $C0 $C0 $C0 $C1 $BE $81 $81 $C0 $3F $00 $00 $80 $7F $00 $00
; Tile index $0D2
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $C0 $3F $00 $00 $70 $8F $40 $40 $1C $E3 $10 $10
; Tile index $0D3
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00
; Tile index $0D4
.db $0B $F5 $01 $01 $0B $F4 $02 $02 $01 $FE $01 $01 $05 $FA $01 $01 $02 $FD $00 $00 $07 $F8 $00 $00 $3F $C0 $06 $06 $C1 $3E $01 $01
; Tile index $0D5
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $FF $7F $7F $7F $FF $3F $BF $BF $7F $9F $5F $5F $FF $0F $0F $0F $3F $C7 $37 $37
; Tile index $0D6
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FC $FC
; Tile index $0D7
.db $FF $FF $FF $FF $FF $FC $FC $FC $FC $F8 $F8 $FB $FB $F0 $F3 $F7 $F7 $C0 $C7 $CF $CF $80 $8F $BF $DF $00 $1F $3F $3F $00 $3F $FF
; Tile index $0D8
.db $BF $00 $3F $7F $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0D9
.db $18 $07 $00 $E0 $E4 $03 $E0 $F8 $FA $01 $F8 $FC $FD $00 $FC $FE $FF $00 $FE $FE $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0DA
.db $07 $F8 $04 $04 $01 $FE $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0DB
.db $00 $FF $00 $00 $80 $7F $00 $00 $C0 $3F $80 $80 $60 $9F $40 $40 $60 $9F $40 $40 $60 $9F $40 $40 $60 $9F $40 $40 $3D $C2 $00 $00
; Tile index $0DC
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $C0 $3F $00 $00
; Tile index $0DD
.db $01 $FE $00 $00 $02 $FD $00 $00 $04 $FB $00 $00 $04 $FB $00 $00 $04 $FB $00 $00 $08 $F7 $00 $00 $08 $F7 $00 $00 $04 $FB $00 $00
; Tile index $0DE
.db $01 $FE $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0DF
.db $BF $43 $03 $03 $EF $11 $81 $81 $67 $98 $42 $42 $3F $C0 $20 $20 $1F $E0 $1F $1F $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0E0
.db $FF $FF $FF $FF $FF $7F $7F $7F $FF $07 $07 $07 $FF $00 $C0 $C0 $9F $60 $18 $18 $87 $78 $87 $87 $C0 $3F $80 $80 $60 $9F $40 $40
; Tile index $0E1
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F1 $0F $01 $01 $0C $F3 $00 $00 $FF $00 $00 $00 $7F $80 $7C $7C $03 $FC $03 $03
; Tile index $0E2
.db $FF $FF $FF $FF $FF $FF $FF $FF $F8 $FF $F8 $F8 $80 $FF $80 $80 $00 $FF $00 $00 $00 $FF $00 $00 $C0 $3F $00 $00 $F0 $0F $00 $00
; Tile index $0E3
.db $FF $FF $FF $FF $FF $FF $FF $FF $01 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00 $FE $00 $00 $01
; Tile index $0E4
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $FF $0F $0F $01 $FF $01 $01 $01 $FE $00 $00 $FE $00 $00 $01 $01 $00 $01 $FF
; Tile index $0E5
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $00 $00 $00 $FF $FF $00 $FF $FF
; Tile index $0E6
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $03 $00 $00 $03 $00 $00 $FC $FC $00 $FC $FF
; Tile index $0E7
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $03 $FF $03 $03 $E0 $1F $00 $00 $1E $01 $00 $E0
; Tile index $0E8
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FE $FE $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0E9
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $E0 $FF $E0 $E0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0EA
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00
; Tile index $0EB
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $FF $0F $0F $01 $FE $00 $00 $0E $F0 $00 $01 $F1 $00 $01 $0F
; Tile index $0EC
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FE $FE $80 $FF $80 $80 $FF $00 $00 $00 $00 $00 $00 $FF $FF $00 $FF $FF
; Tile index $0ED
.db $FF $FF $FF $FF $E0 $FF $E0 $E0 $80 $FF $80 $80 $00 $FF $00 $00 $01 $FE $00 $00 $82 $7C $00 $01 $7A $04 $00 $81 $85 $00 $81 $FB
; Tile index $0EE
.db $FF $FF $FF $FF $01 $FF $01 $01 $0F $F0 $00 $00 $70 $80 $00 $0F $8F $00 $0F $7F $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0EF
.db $FC $E0 $E0 $E3 $E3 $00 $03 $1F $1F $00 $1F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0F0
.db $00 $FF $00 $00 $00 $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F1
.db $1A $E5 $10 $10 $3E $C1 $20 $20 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F2
.db $40 $BF $40 $40 $3C $C3 $20 $20 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F3
.db $02 $FD $00 $00 $01 $FE $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F4
.db $38 $C7 $20 $20 $38 $C7 $20 $20 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F5
.db $7F $80 $70 $70 $0B $F0 $08 $0C $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F6
.db $01 $00 $01 $FF $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F7
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F8
.db $E1 $00 $E0 $FE $FE $00 $FE $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0F9
.db $E0 $1F $00 $00 $10 $0F $00 $E0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0FA
.db $0E $F0 $00 $01 $11 $E0 $01 $0F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0FB
.db $0F $00 $0F $FF $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0FC
.db $FB $00 $FB $FF $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0FD
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
