; Tile index $060
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $061
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FF $FF $F8 $FF $FF $FF $FC $FF $FF $FF
; Tile index $062
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $07 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $063
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $FF $FF $FF $3F $FF $FF $FF
; Tile index $064
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FF $FF $E0 $FF $FF $FF $C0 $FF $FF $FF
; Tile index $065
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $38 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $066
.db $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FF $FF $E0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $067
.db $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $068
.db $FF $FF $FF $FF $07 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $069
.db $FF $FF $FF $FF $FF $FF $FF $FF $7F $FF $FF $FF $07 $FF $FF $FF $01 $FF $FF $FF $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $06A
.db $E4 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF
; Tile index $06C
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $80 $FF $FF $FF $00 $FF $FF $FF
; Tile index $06D
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $FF $FF $FF $00 $FF $FF $FF
; Tile index $06E
.db $FF $FF $FF $FF $FF $FF $FF $FF $F0 $FF $FF $FF $E0 $FF $FF $FF $E1 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06F
.db $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $F0 $FF $FF $FF $FC $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $070
.db $FF $FF $FF $FF $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $3F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $071
.db $FF $FF $FF $FF $FF $FF $FF $FF $07 $FF $FF $FF $03 $FF $FF $FF $0F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $072
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $F8 $FF $FF $FF
; Tile index $073
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $FF $FF $FF $01 $FF $FF $FF
; Tile index $074
.db $E0 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $075
.db $00 $FF $FF $FF $F0 $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $076
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $077
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $03 $FF $FF $FF
; Tile index $078
.db $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $079
.db $FF $FF $FF $FF $7F $FF $FF $FF $3F $FF $FF $FF $1F $FF $FF $FF $0F $FF $FF $FF $0F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $07A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $FC $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF
; Tile index $07B
.db $E0 $FF $FF $FF $C0 $FF $FF $FF $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $07C
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FF $FF $FF
; Tile index $07D
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $7F $FF $FF $FF $FF $FF $FF $FF
; Tile index $07E
.db $3F $FF $FF $FF $03 $FF $FF $FF $01 $FF $FF $FF $01 $FF $FF $FF $01 $FF $FF $FF $03 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $07F
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $FF $FF $FF $F0 $FF $FF $FF $F0 $FF $FF $FF $E0 $FF $FF $FF
; Tile index $080
.db $FF $FF $FF $FF $F0 $FF $FF $FF $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $081
.db $FF $FF $FF $FF $70 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $082
.db $4F $FF $FF $FF $04 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $083
.db $F0 $FF $FF $FF $FC $FF $FF $FF $7F $FF $FF $FF $1F $FF $FF $FF $1F $FF $FF $FF $03 $FF $FF $FF $03 $FF $FF $FF $07 $FF $FF $FF
; Tile index $084
.db $01 $FF $FF $FF $0F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $085
.db $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $086
.db $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF
; Tile index $087
.db $0F $FF $FF $FF $3F $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $FC $FF $FF $FF $FC $FF $FF $FF $F8 $FF $FF $FF $00 $FF $FF $FF
; Tile index $088
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $089
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $FF $FF $FF $1F $FF $FF $FF $07 $FF $FF $FF $3F $FF $FF $FF
; Tile index $08A
.db $E0 $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08B
.db $00 $FF $FF $FF $00 $FF $FF $FF $FC $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08C
.db $00 $FF $FF $FF $00 $FF $FF $FF $30 $FF $FF $FF $F8 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08D
.db $00 $FF $FF $FF $00 $FF $FF $FF $0F $FF $FF $FF $1F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08E
.db $00 $FF $FF $FF $61 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $08F
.db $1F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $090
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FD $FD $FD $FD $F8 $F8 $FA $F9 $F0 $F0 $F6
; Tile index $091
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $EE $EE $EE $FE $C4 $C4 $C5 $DE $8C $8C $AD $FE $1C $1C $1D $9D $08 $08 $6A
; Tile index $092
.db $FF $FF $FF $FF $FF $EF $EF $EF $EF $83 $83 $93 $83 $01 $01 $7D $33 $01 $21 $CD $7F $10 $50 $90 $FD $00 $60 $02 $46 $00 $40 $B9
; Tile index $093
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $CF $CF $CF $CF $07 $07 $37
; Tile index $094
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FE $FC $FC $FD $FF $FC $FC $FC $FF $FE $FE $FE $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $095
.db $FF $B8 $B8 $B8 $BF $18 $18 $58 $3A $10 $12 $D5 $71 $00 $01 $8E $B1 $00 $01 $4E $B3 $00 $01 $4C $DA $80 $80 $A5 $83 $00 $00 $7C
; Tile index $096
.db $B9 $00 $00 $46 $61 $00 $01 $9E $80 $00 $00 $7F $87 $00 $03 $78 $CC $00 $84 $33 $79 $00 $41 $86 $32 $00 $22 $CD $F9 $00 $39 $06
; Tile index $097
.db $8C $00 $80 $73 $2B $00 $00 $D4 $13 $00 $00 $EC $3E $00 $00 $C1 $7E $14 $14 $95 $75 $00 $60 $8A $F0 $00 $C0 $0F $65 $00 $40 $9A
; Tile index $098
.db $9F $07 $07 $67 $07 $03 $03 $FB $37 $03 $03 $CB $27 $02 $02 $DA $22 $00 $00 $DD $4C $00 $00 $B3 $00 $00 $00 $FF $83 $00 $02 $7C
; Tile index $099
.db $FF $FB $FB $FB $FB $91 $91 $95 $9B $01 $01 $65 $B3 $00 $00 $4C $F7 $20 $23 $28 $0F $00 $03 $F0 $66 $00 $02 $99 $61 $00 $00 $9E
; Tile index $09A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F $3F $1F $1F $DF $FF $1F $1F $1F $9F $0F $0F $6F $3F $1F $1F $DF
; Tile index $09B
.db $FF $FE $FE $FE $FE $FC $FC $FD $FD $F8 $F8 $FA $FC $F0 $F0 $F3 $F3 $E0 $E0 $EC $F3 $E0 $E0 $EC $F9 $F0 $F0 $F6 $FE $F8 $F8 $F9
; Tile index $09C
.db $FB $C0 $C0 $C4 $C2 $00 $00 $3D $41 $00 $01 $BE $39 $00 $00 $C6 $A2 $00 $02 $5D $C3 $00 $83 $3C $69 $00 $41 $96 $4F $00 $4B $B0
; Tile index $09D
.db $34 $00 $34 $CB $F0 $00 $70 $0F $66 $00 $26 $99 $1F $00 $1E $E0 $3F $00 $3C $C0 $66 $00 $64 $99 $64 $00 $64 $9B $6C $00 $68 $93
; Tile index $09E
.db $67 $00 $60 $98 $39 $00 $00 $C6 $03 $00 $00 $FC $32 $00 $02 $CD $37 $00 $24 $C8 $6A $00 $68 $95 $CB $00 $CB $34 $B7 $00 $16 $48
; Tile index $09F
.db $A7 $00 $06 $58 $87 $00 $06 $78 $0F $00 $0D $F0 $7E $00 $1C $81 $2E $00 $0E $D1 $84 $00 $04 $7B $81 $00 $01 $7E $93 $00 $12 $6C
; Tile index $0A0
.db $03 $01 $01 $FD $3F $00 $38 $C0 $3C $00 $30 $C3 $B9 $00 $A0 $46 $F1 $00 $C0 $0E $E7 $01 $C1 $19 $EF $07 $87 $17 $DF $07 $07 $27
; Tile index $0A1
.db $9F $0F $0F $6F $3F $1F $1F $DF $FF $3F $3F $3F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0A2
.db $F9 $F0 $F0 $F6 $F9 $F0 $F0 $F6 $F9 $F0 $F0 $F6 $FF $F8 $F8 $F8 $FD $F0 $F0 $F2 $F2 $E0 $E2 $ED $E4 $C0 $C0 $DB $F4 $E0 $E0 $EB
; Tile index $0A3
.db $8E $00 $82 $71 $9C $00 $80 $63 $B8 $00 $20 $47 $90 $00 $10 $6F $B8 $00 $38 $47 $91 $00 $10 $6E $CF $00 $48 $30 $CC $00 $4C $33
; Tile index $0A4
.db $6D $00 $60 $92 $4E $00 $40 $B1 $E2 $00 $E0 $1D $44 $00 $40 $BB $DE $00 $5E $21 $1F $00 $1D $E0 $6A $00 $6A $95 $47 $00 $06 $B8
; Tile index $0A5
.db $4F $00 $0F $B0 $A7 $00 $27 $58 $66 $00 $20 $99 $CC $00 $88 $33 $FD $00 $21 $02 $7F $00 $61 $80 $68 $00 $60 $97 $D2 $00 $12 $2D
; Tile index $0A6
.db $26 $00 $24 $D9 $6E $00 $68 $91 $6C $00 $68 $93 $D0 $00 $D0 $2F $C1 $00 $C0 $3E $E7 $00 $E0 $18 $7B $01 $61 $85 $93 $00 $80 $6C
; Tile index $0A7
.db $37 $03 $03 $CB $6F $07 $07 $97 $1F $0F $0F $EF $3F $1F $1F $DF $7F $3F $3F $BF $7F $3F $3F $BF $BF $1F $1F $5F $FF $BF $BF $BF
; Tile index $0A8
.db $FB $F0 $F1 $F4 $FF $F8 $F8 $F8 $FF $FE $FE $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0A9
.db $C8 $00 $48 $37 $22 $00 $22 $DD $EE $00 $EE $11 $CE $00 $4E $31 $E7 $80 $A7 $98 $CB $80 $8B $B4 $F6 $C0 $C4 $C9 $E4 $C0 $C0 $DB
; Tile index $0AA
.db $88 $00 $08 $77 $A0 $00 $20 $5F $7E $00 $5E $81 $DD $00 $DD $22 $89 $00 $89 $76 $3F $00 $3F $C0 $F8 $00 $F8 $07 $F1 $00 $71 $0E
; Tile index $0AB
.db $17 $00 $07 $E8 $FF $00 $1F $00 $DE $00 $DE $21 $A8 $00 $A8 $57 $9E $00 $9E $61 $13 $00 $12 $EC $F3 $00 $F3 $0C $E7 $00 $E6 $18
; Tile index $0AC
.db $B0 $00 $80 $4F $61 $00 $40 $9E $B9 $00 $80 $46 $6F $01 $01 $91 $DB $01 $41 $25 $D7 $03 $83 $2B $87 $03 $03 $7B $1F $0F $0F $EF
; Tile index $0AD
.db $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0AE
.db $E8 $C0 $C0 $D7 $FB $E0 $E0 $E4 $FF $FB $FB $FB $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0AF
.db $C3 $00 $C3 $3C $87 $00 $07 $78 $9F $00 $1F $60 $FF $80 $9F $80 $FF $C0 $DF $C0 $FF $C0 $DF $C0 $FF $C0 $DF $C0 $FF $C0 $DF $C0
; Tile index $0B0
.db $A6 $00 $A4 $59 $7C $00 $7C $83 $7F $00 $78 $80 $7F $03 $7B $83 $FF $03 $FB $03 $FF $03 $FB $03 $FF $07 $F7 $07 $FF $07 $F7 $07
; Tile index $0B1
.db $7F $1F $1F $9F $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $0B2
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FE $FC $FC $FD
; Tile index $0B3
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $C0 $C0 $C0 $C0 $80 $80 $BF $BF $00 $3F $7F $7F $00 $7F $FF $FF $00 $FF $FF
; Tile index $0B4
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $1F $0F $0F $EF $EF $01 $E1 $F1 $F1 $00 $F0 $FE $FE $00 $FE $FF
; Tile index $0B5
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $0F $0F $1F $07 $07 $E7
; Tile index $0B6
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $80 $80 $80 $81 $00 $00 $7E $7E $00 $7E $FF
; Tile index $0B7
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $3F $00 $00 $C0
; Tile index $0B8
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $80 $80 $80 $80 $00 $00 $7F
; Tile index $0B9
.db $FF $80 $BF $80 $FF $80 $BF $80 $FF $C0 $DF $C0 $FF $C0 $DF $C0 $FF $C0 $DF $C0 $FF $C0 $DF $C0 $FF $C0 $DF $C0 $FF $00 $1F $00
; Tile index $0BA
.db $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $07 $F7 $07
; Tile index $0BB
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $D7 $D7 $D7 $D7 $83 $83 $AB
; Tile index $0BC
.db $FD $F8 $F9 $FB $FB $F0 $F3 $F7 $FB $F0 $F3 $F7 $FB $F0 $F3 $F7 $F7 $E0 $E7 $EF $F7 $E0 $E7 $EF $EF $C0 $CF $DF $DF $80 $9F $BF
; Tile index $0BD
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BE
.db $E7 $00 $E0 $F8 $F8 $00 $F8 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BF
.db $FF $FF $FF $FF $FF $7F $7F $7F $7F $1F $1F $9F $9F $0F $8F $EF $DF $0F $CF $EF $EF $07 $E7 $F7 $F7 $00 $F0 $F8 $F8 $00 $F8 $FF
; Tile index $0C0
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F
; Tile index $0C1
.db $C0 $00 $C0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C2
.db $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C3
.db $3F $00 $1F $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0
; Tile index $0C4
.db $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $07 $F7 $07 $FF $01 $F1 $01 $F9 $00 $F0 $06 $FE $00 $F6 $07 $FF $00 $F7 $07 $FF $00 $F7 $07
; Tile index $0C5
.db $FF $FF $FF $FF $FF $FC $FC $FC $FD $F8 $F8 $FA $FC $F8 $F8 $FB $FD $78 $78 $7A $7F $1C $1C $9C $9F $03 $83 $E3 $E3 $00 $E0 $FC
; Tile index $0C6
.db $A7 $03 $03 $5B $E7 $03 $83 $1B $FF $07 $57 $07 $FF $07 $57 $07 $BF $0F $0F $4F $3F $0F $2F $CF $FF $0F $6F $0F $FF $0F $2F $0F
; Tile index $0C7
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FC $FC
; Tile index $0C8
.db $FF $FF $FF $FF $FF $FC $FC $FC $FC $F8 $F8 $FB $FB $F0 $F3 $F7 $F7 $C0 $C7 $CF $CF $80 $8F $BF $DF $00 $1F $3F $3F $00 $3F $FF
; Tile index $0C9
.db $BF $00 $3F $7F $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CA
.db $18 $07 $00 $E0 $E4 $03 $E0 $F8 $FA $01 $F8 $FC $FD $00 $FC $FE $FF $00 $FE $FE $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CB
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F8 $F8 $FF $07 $07 $07
; Tile index $0CC
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F9 $F9 $FF $06 $C6 $C6 $F9 $3F $3F $3F $C0 $FF $FF $FF $00 $FF $FF $FF
; Tile index $0CD
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $E1 $E1 $FF $1C $9C $9C $E3 $7F $7F $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $0CE
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F $FF $80 $BF $BF $FF $C0 $C3 $C3 $3F $FC $FC $FC $03 $FF $FF $FF
; Tile index $0CF
.db $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $DF $C0 $FF $00 $17 $00 $FF $C8 $CB $C8 $07 $F8 $FA $F8
; Tile index $0D0
.db $FF $00 $F7 $07 $FF $00 $F7 $07 $FF $00 $FB $03 $FF $00 $FB $03 $FF $00 $FB $03 $FF $00 $DB $03 $FF $30 $BB $33 $87 $7C $7D $7D
; Tile index $0D1
.db $FC $00 $FC $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F0 $F0 $FF $0F $CF $CF $F0 $3F $BF $BF
; Tile index $0D2
.db $7F $07 $27 $87 $F7 $00 $A0 $88 $F8 $00 $B0 $87 $FF $00 $B7 $87 $FF $00 $B7 $87 $FF $00 $2F $0F $FF $00 $2F $0F $FF $C0 $C8 $C8
; Tile index $0D3
.db $FF $FF $FF $FF $FF $3F $3F $3F $3F $00 $00 $C0 $C0 $00 $C0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0D4
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $7D $03 $01 $81 $83 $00 $80 $FC $FC $00 $FC $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0D5
.db $FF $FF $FF $FF $FF $FF $FF $FF $F8 $FF $F8 $F8 $80 $FF $80 $80 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $E0 $1F $00 $00
; Tile index $0D6
.db $FF $FF $FF $FF $FF $FF $FF $FF $01 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00 $FE $00 $00 $01
; Tile index $0D7
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $FF $0F $0F $01 $FF $01 $01 $01 $FE $00 $00 $FE $00 $00 $01 $01 $00 $01 $FF
; Tile index $0D8
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $00 $00 $00 $FF $FF $00 $FF $FF
; Tile index $0D9
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $03 $00 $00 $03 $00 $00 $FC $FC $00 $FC $FF
; Tile index $0DA
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $03 $FF $03 $03 $E0 $1F $00 $00 $1E $01 $00 $E0
; Tile index $0DB
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FE $FE $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0DC
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $E0 $FF $E0 $E0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0DD
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00
; Tile index $0DE
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $0F $FF $0F $0F $01 $FE $00 $00 $0E $F0 $00 $01 $F1 $00 $01 $0F
; Tile index $0DF
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FE $FE $80 $FF $80 $80 $FF $00 $00 $00 $00 $00 $00 $FF $FF $00 $FF $FF
; Tile index $0E0
.db $FF $FF $FF $FF $E0 $FF $E0 $E0 $80 $FF $80 $80 $00 $FF $00 $00 $01 $FE $00 $00 $82 $7C $00 $01 $7A $04 $00 $81 $85 $00 $81 $FB
; Tile index $0E1
.db $FF $FF $FF $FF $01 $FF $01 $01 $0F $F0 $00 $00 $70 $80 $00 $0F $8F $00 $0F $7F $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0E2
.db $FC $E0 $E0 $E3 $E3 $00 $03 $1F $1F $00 $1F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0E3
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F9 $F9
; Tile index $0E4
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $CE $CE
; Tile index $0E5
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FC $FC $FF $03 $FB $FB $FC $03 $83 $83 $F8 $3F $3F $3F
; Tile index $0E6
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F1 $F1 $FF $0E $0E $0E $E0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $0E7
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $03 $03 $FF $FC $FC $FC $03 $FE $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF
; Tile index $0E8
.db $F8 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0E9
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0EA
.db $02 $FD $FD $FD $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0EB
.db $03 $FE $FE $FE $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0EC
.db $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0ED
.db $3F $EF $EF $EF $18 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0EE
.db $FF $00 $7F $7F $FF $80 $BF $BF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0EF
.db $FF $00 $FF $FF $FF $00 $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F0
.db $1F $00 $00 $E0 $E0 $00 $E0 $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F1
.db $01 $00 $01 $FF $FF $00 $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F2
.db $E1 $00 $E0 $FE $FE $00 $FE $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F3
.db $E0 $1F $00 $00 $10 $0F $00 $E0 $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F4
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F5
.db $0E $F0 $00 $01 $11 $E0 $01 $0F $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F6
.db $0F $00 $0F $FF $FF $00 $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F7
.db $FB $00 $FB $FF $FF $00 $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F8
.db $FF $06 $F6 $F6 $F8 $0F $CF $CF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0F9
.db $EF $31 $31 $31 $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0FA
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
