; Tile index $060
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $061
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $062
.db $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $03 $00 $FC $FC $03 $01 $FD $FC $07 $03 $FB $F8 $1F $07 $E7 $E0 $3F $1F $DF $C0
; Tile index $063
.db $3F $00 $C0 $C0 $FF $3F $3F $00 $FF $7F $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $064
.db $80 $00 $7F $7F $E0 $00 $1F $1F $F8 $E0 $E7 $07 $FC $F0 $F3 $03 $FF $FC $FC $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $065
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $3F $3F $F0 $80 $8F $0F $FC $F0 $F3 $03 $FF $FC $FC $00
; Tile index $066
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $02 $01 $FD $FC $0C $03 $F3 $F0
; Tile index $067
.db $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $03 $01 $FD $FC $07 $01 $F9 $F8 $0F $00 $F0 $F0 $10 $0F $EF $E0 $20 $1F $DF $C0
; Tile index $068
.db $7F $3F $BF $80 $FF $7F $7F $00 $FF $F8 $F8 $00 $F8 $C7 $C7 $00 $C0 $3F $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $1F $E0 $FF $00
; Tile index $069
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $18 $18 $00 $38 $C7 $C7 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FE $01 $FF $00
; Tile index $06A
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $3F $3F $00 $3F $CF $CF $00 $0F $F7 $F7 $00 $07 $FB $FB $00 $03 $FC $FC $00
; Tile index $06B
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FD $E2 $E2 $00 $E0 $1F $1F $00
; Tile index $06C
.db $F0 $00 $0F $0F $FF $E0 $E0 $00 $FF $FF $FF $00 $FF $FE $FE $00 $FE $F1 $F1 $00 $F0 $CF $CF $00 $C0 $3F $3F $00 $0F $F0 $FF $00
; Tile index $06D
.db $00 $00 $FF $FF $80 $00 $7F $7F $FF $80 $80 $00 $C0 $3F $3F $00 $00 $FF $FF $00 $3F $C0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $06E
.db $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $7F $7F $C0 $00 $3F $3F $E0 $00 $DF $1F $F8 $00 $E7 $07 $FF $00 $F8 $00 $FF $00 $FF $00
; Tile index $06F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $3F $3F
; Tile index $070
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $00 $FC $FC $07 $00 $F9 $F8
; Tile index $071
.db $00 $00 $FF $FF $03 $00 $FC $FC $07 $03 $FB $F8 $0F $00 $F0 $F0 $08 $07 $F7 $F0 $F0 $0F $0F $00 $03 $FC $FF $00 $FF $00 $FF $00
; Tile index $072
.db $F0 $00 $0F $0F $FE $F0 $F1 $01 $FF $FE $FE $00 $FF $3F $3F $00 $3F $DF $DF $00 $1F $EE $EE $00 $CE $31 $F1 $00 $E0 $1F $FF $00
; Tile index $073
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $3F $3F $F0 $C0 $CF $0F $EC $10 $13 $03 $07 $F8 $F8 $00 $00 $FF $FF $00
; Tile index $074
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $00 $FC $FC $04 $03 $FB $F8 $18 $07 $E7 $E0 $60 $1F $9F $80 $81 $7E $7F $00
; Tile index $075
.db $30 $0F $CF $C0 $40 $3F $BF $80 $80 $7F $7F $00 $03 $FC $FF $00 $0F $F0 $FF $00 $3F $C0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $076
.db $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $02 $01 $FD $FC $04 $03 $FB $F8 $08 $07 $F7 $F0 $13 $0C $EF $E0 $3F $00 $DF $C0
; Tile index $077
.db $40 $3F $BF $80 $81 $7E $7F $00 $07 $F8 $FF $00 $0F $F0 $FF $00 $7F $80 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $078
.db $7F $80 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $079
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $07A
.db $00 $FF $FF $00 $C0 $3F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $07B
.db $01 $FE $FF $00 $7F $80 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $07C
.db $30 $C0 $CF $0F $88 $70 $F7 $07 $CE $30 $F1 $01 $E1 $1E $FE $00 $E0 $1F $FF $00 $F8 $07 $FF $00 $FC $03 $FF $00 $FF $00 $FF $00
; Tile index $07D
.db $00 $00 $FF $FF $03 $00 $FC $FC $04 $03 $FB $F8 $98 $07 $67 $60 $E0 $1F $1F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07E
.db $80 $00 $7F $7F $40 $80 $BF $3F $38 $C0 $C7 $07 $06 $F8 $F9 $01 $01 $FE $FE $00 $00 $FF $FF $00 $00 $FF $FF $00 $78 $87 $FF $00
; Tile index $07F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $7F $7F $60 $80 $9F $1F $18 $E0 $E7 $07 $07 $F8 $F8 $00
; Tile index $080
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $00 $00
; Tile index $081
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $9F $00 $60 $60
; Tile index $082
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $00 $FC $FC $0F $00 $F3 $F0 $7F $00 $8F $80 $FF $00 $7F $00
; Tile index $083
.db $1F $00 $E7 $E0 $3F $00 $CF $C0 $7F $00 $BF $80 $FF $00 $7F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $084
.db $F0 $0F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $085
.db $00 $FF $FF $00 $C0 $3F $FF $00 $F0 $0F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $086
.db $30 $C0 $CF $0F $06 $F8 $F9 $01 $01 $FE $FE $00 $F0 $0F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $087
.db $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $3F $3F $3C $C0 $C3 $03 $FF $00 $F8 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $088
.db $00 $00 $FF $FF $00 $00 $FF $FF $07 $00 $F8 $F8 $38 $07 $C7 $C0 $FF $00 $3F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $089
.db $03 $00 $FC $FC $3E $01 $C1 $C0 $C0 $3F $3F $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $08A
.db $03 $FC $FF $00 $0F $F0 $FF $00 $3F $C0 $FF $00 $7F $80 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $08B
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $3E $00 $C1 $C1 $41 $3E $BE $80 $80 $7F $7F $00 $00 $FF $FF $00
; Tile index $08C
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $F8 $00 $07 $07 $07 $F8 $F8 $00 $00 $FF $FF $00
; Tile index $08D
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $E0 $00 $1F $1F $30 $C0 $CF $0F
; Tile index $08E
.db $00 $00 $FF $FF $01 $00 $FE $FE $03 $00 $FD $FC $07 $00 $FB $F8 $1F $00 $E7 $E0 $3F $00 $DF $C0 $7F $00 $BF $80 $FF $00 $7F $00
; Tile index $08F
.db $FF $00 $3F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $090
.db $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $091
.db $70 $8F $8F $00 $03 $FC $FF $00 $8F $70 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $092
.db $00 $FF $FF $00 $07 $F8 $FF $00 $0F $F0 $FF $00 $1F $E0 $FF $00 $3F $C0 $FF $00 $3F $C0 $FF $00 $7F $80 $FF $00 $FF $00 $FF $00
; Tile index $093
.db $00 $FF $FF $00 $E0 $1F $FF $00 $FE $01 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $094
.db $18 $E0 $E7 $07 $0C $F0 $F3 $03 $02 $FC $FD $01 $C1 $3E $FE $00 $E0 $1F $FF $00 $F0 $0F $FF $00 $FC $03 $FF $00 $FF $00 $FF $00
; Tile index $095
.db $03 $00 $FC $FC $07 $00 $FB $F8 $0F $00 $F7 $F0 $3F $00 $CF $C0 $C7 $38 $3F $00 $1F $E0 $FF $00 $7F $80 $FF $00 $FF $00 $FF $00
; Tile index $096
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $C0 $00
; Tile index $097
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $7F $00
; Tile index $098
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $F0 $00 $FF $00 $00 $00
; Tile index $099
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $F0 $00 $FF $0F $C0 $00
; Tile index $09A
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $E0 $00 $FF $1F $00 $00 $FF $FF $00 $00
; Tile index $09B
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3F $00 $FF $00 $0F $00 $FF $00 $02 $00 $FF $01 $00 $00 $FF $0F $00 $00
; Tile index $09C
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $F0 $00 $FF $0F $C0 $00 $FF $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09D
.db $FF $00 $F0 $00 $FF $0F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09E
.db $FF $00 $1F $00 $FF $E0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09F
.db $FF $00 $FF $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A0
.db $FF $00 $FF $00 $FF $00 $07 $00 $FF $F8 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A1
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A2
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3F $00 $FF $C0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A3
.db $FF $00 $FF $00 $FF $00 $FC $00 $FF $00 $80 $00 $FF $00 $00 $00 $FF $FE $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A4
.db $FF $00 $F0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $07 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A5
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $E0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A6
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $F0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A7
.db $FF $00 $FF $00 $FF $00 $07 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $F8 $00 $00
; Tile index $0A8
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3F $00 $FF $00 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A9
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $0F $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0AA
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3F $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0AB
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $E0 $00 $FF $00 $00 $00
; Tile index $0AC
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $80 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0AD
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3F $00 $FF $00 $00 $00 $FF $07 $00 $00 $FF $7F $00 $00
; Tile index $0AE
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $F0 $00 $FF $0F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0AF
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FE $00 $FF $01 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B0
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FC $00 $FF $00 $C0 $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B1
.db $FF $00 $FC $00 $FF $00 $E0 $00 $FF $00 $00 $00 $FF $03 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B2
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $1F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B3
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B4
.db $FF $00 $02 $00 $FF $01 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B5
.db $FF $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B6
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B7
.db $FF $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B8
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0B9
.db $FF $FE $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0BA
.db $FF $00 $00 $00 $FF $FC $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0BB
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $C0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0BC
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $E0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0BD
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0BE
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $07 $00 $00 $FF $1F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0BF
.db $FF $0F $00 $00 $FF $7F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF
; Tile index $0C0
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0C1
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
