; Tile index $060
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $061
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $062
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $03 $FF $FF $00 $07 $FF $FF $00 $0F $FF $FF $00
; Tile index $063
.db $00 $FF $FF $00 $00 $FF $FF $00 $0F $FF $FF $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $064
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $01 $FF $FF $00 $0F $FF $FF $00
; Tile index $065
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $1F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $066
.db $00 $FF $FF $00 $00 $FF $FF $00 $03 $FF $FF $00 $07 $FF $FF $00 $0F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $067
.db $3F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $068
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $069
.db $00 $FF $FF $00 $00 $FF $FF $00 $01 $FF $FF $00 $01 $FF $FF $00 $03 $FF $FF $00 $07 $FF $FF $00 $1F $FF $FF $00 $7F $FF $FF $00
; Tile index $06A
.db $3F $FF $FF $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $06B
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $7F $FF $00 $7F $BF $FF $00 $3F $C7 $FF $00 $07 $F8 $FF $00
; Tile index $06C
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $7F $FF $00
; Tile index $06D
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $03 $FF $FF $00 $0F $FF $FF $00 $3F $FF $FF $00 $7F $FF $FF $00
; Tile index $06E
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $0F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $06F
.db $00 $FF $FF $00 $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $070
.db $00 $FF $FF $00 $00 $FF $FF $00 $C0 $FF $FF $00 $F8 $FF $FF $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $071
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $80 $FF $FF $00 $80 $FF $FF $00 $80 $FF $FF $00
; Tile index $072
.db $7F $BF $FF $00 $3F $CF $FF $00 $0F $F7 $FF $00 $07 $F9 $FF $00 $01 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $073
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $7F $FF $00 $7F $9F $FF $00 $1F $E7 $FF $00
; Tile index $074
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $F0 $FF $00
; Tile index $075
.db $7F $BF $FF $00 $3F $C0 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $076
.db $FF $FF $FF $00 $FF $7F $FF $00 $7F $81 $FF $00 $01 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $077
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FE $FF $00 $FE $39 $FF $00 $38 $C7 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $078
.db $FF $FE $FF $00 $FE $81 $FF $00 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $079
.db $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07A
.db $07 $F8 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07B
.db $F0 $0F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07C
.db $07 $F9 $FF $00 $01 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07D
.db $FF $FF $FF $00 $FF $3F $FF $00 $3F $CF $FF $00 $0F $F3 $FF $00 $03 $FC $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07E
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07F
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $3C $FF $00 $3C $C3 $FF $00 $00 $FF $FF $00
; Tile index $080
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $081
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF $FF $FF $00 $FF $FE $FE $00 $FF $F8 $F8 $00 $FF $F7 $F0 $07 $FF $EF $E0 $08
; Tile index $082
.db $00 $FF $FF $00 $00 $FF $FF $00 $7F $80 $80 $00 $FF $7F $00 $7F $FF $FF $00 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $083
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FC $FC $00 $FF $FB $F8 $03 $FF $07 $00 $04 $FF $FF $00 $F8 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $084
.db $FF $E7 $E7 $00 $FF $19 $01 $18 $FF $FE $00 $E6 $FF $FF $00 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $085
.db $FF $FF $FF $00 $FF $E1 $E1 $00 $FF $DE $C0 $1E $FF $3F $00 $21 $FF $FF $00 $C0 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $086
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $7F $7F $00 $FF $BF $3F $80 $FF $C8 $08 $40 $FF $F7 $00 $37 $FF $FF $00 $08 $FF $FF $00 $00
; Tile index $087
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $7F $7F $00 $FF $BF $3F $80 $FF $DF $1F $40 $FF $DF $1F $40
; Tile index $088
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $F8 $F8 $00 $FF $E7 $E0 $07 $FF $DF $C0 $10
; Tile index $089
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $E0 $E0 $00 $FF $DF $C0 $1F $FF $BF $80 $20 $FF $7F $00 $40 $FF $FF $00 $80 $FF $FF $00 $00
; Tile index $08A
.db $FF $EF $E0 $00 $FF $DF $C0 $10 $FF $3F $00 $20 $FF $FF $00 $C0 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $08B
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $08C
.db $FF $EF $0F $20 $FF $EC $0C $20 $FF $F3 $00 $13 $FF $FF $00 $0C $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $08D
.db $FF $0F $0F $00 $FF $EF $0F $E0 $FF $F4 $04 $10 $FF $F3 $00 $13 $FF $FF $00 $0C $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $08E
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $07 $07 $00 $FF $FB $03 $F8 $FE $FD $00 $04 $FF $FE $00 $02 $FF $FE $00 $02 $FF $FF $00 $01
; Tile index $08F
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $00 $18 $E7 $00 $00 $3C $DB $00 $18 $FF $3C $00 $24
; Tile index $090
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $C0 $BF $00 $80
; Tile index $091
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $092
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $E6 $FF $E6 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $093
.db $FF $FF $FF $00 $FF $FF $FF $00 $8F $FF $8F $00 $8F $FF $8F $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $094
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $00 $09 $F6 $00 $00 $3F $C9 $00 $09 $FF $3F $00 $36
; Tile index $095
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $E1 $E1 $00 $FF $1E $00 $1E $FF $FF $00 $E1 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $096
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $07 $07 $00 $FC $FB $00 $F8 $FF $FC $00 $04 $FF $FF $00 $03 $FF $FF $00 $00
; Tile index $097
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $70 $8F $00 $00 $FF $70 $00 $70 $FF $FF $00 $8F $FF $FF $00 $00
; Tile index $098
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $00 $C0 $3F $00 $00 $F0 $CF $00 $C0 $FF $F0 $00 $30
; Tile index $099
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $E0 $1F $00 $00
; Tile index $09A
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $3F $FF $3F $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $09B
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FF $FE $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $09C
.db $FF $FF $FF $00 $FF $FF $FF $00 $04 $FF $04 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $09D
.db $FF $FF $FF $00 $FF $FF $FF $00 $CC $FF $CC $00 $C0 $FF $C0 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $09E
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $F0 $F0 $00 $FF $EF $E0 $0F $3F $DF $00 $10 $7F $BF $00 $20 $7F $BF $00 $00 $FF $7F $00 $40
; Tile index $09F
.db $FF $BF $80 $20 $FF $7F $00 $40 $FF $7F $00 $00 $FF $FF $00 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A0
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A1
.db $FF $FF $00 $C3 $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A2
.db $F0 $CF $00 $40 $F8 $F7 $00 $30 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A3
.db $00 $FF $00 $00 $00 $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A4
.db $3F $C0 $00 $00 $7F $BF $00 $3F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A5
.db $FF $FF $00 $C0 $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A6
.db $FF $FF $00 $0F $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A7
.db $FF $E0 $00 $E0 $FF $FF $00 $1F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A8
.db $00 $FF $00 $00 $80 $7F $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A9
.db $07 $F8 $00 $00 $0F $F7 $00 $07 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0AA
.db $FF $7F $00 $00 $FF $FF $00 $80 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0AB
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
