; Tile index $060
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $061
.db $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $062
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $0F
; Tile index $063
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $064
.db $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $C0 $00 $FF $FF $C0 $00 $FF $FF $E0 $00 $FF $FF $E0 $00 $FF $FF $E0
; Tile index $065
.db $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F
; Tile index $066
.db $00 $FF $FF $E0 $00 $FF $FF $C0 $00 $FF $FF $C0 $00 $FF $FF $C0 $00 $FF $FF $C0 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80
; Tile index $067
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $C0 $00 $FF $FF $F0 $00 $FF $FF $F8
; Tile index $068
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $3F $00 $FF $FF $1F
; Tile index $069
.db $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC
; Tile index $06A
.db $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $03
; Tile index $06B
.db $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $06C
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $03
; Tile index $06D
.db $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $06E
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $FF $FF $E0 $00 $FF $FF $F8 $00 $FF $FF $FC $00 $FF $FF $FE $00 $FF $FF $FF
; Tile index $06F
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80
; Tile index $070
.db $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $071
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $3F $00 $FF $FF $1F
; Tile index $072
.db $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $073
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $C0
; Tile index $074
.db $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $00
; Tile index $075
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FE
; Tile index $076
.db $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $3F $00 $FF $FF $3F
; Tile index $077
.db $00 $FF $FF $C0 $00 $FF $FF $E0 $00 $FF $FF $F8 $00 $FF $FF $FC $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $078
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $C0 $00 $FF $FF $F0
; Tile index $079
.db $00 $FF $FF $1F $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $07A
.db $00 $FF $FF $C0 $00 $FF $FF $E0 $00 $FF $FF $E0 $00 $FF $FF $E0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F8 $00 $FF $FF $F8
; Tile index $07B
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $3F
; Tile index $07C
.db $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC
; Tile index $07D
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $03
; Tile index $07E
.db $00 $FF $FF $F8 $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $07F
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $C0 $00 $FF $FF $F0 $00 $FF $FF $FC $00 $FF $FF $FE $00 $FF $FF $FF
; Tile index $080
.db $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $01
; Tile index $081
.db $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $082
.db $00 $FF $FF $3F $00 $FF $FF $3F $00 $FF $FF $3F $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $1F
; Tile index $083
.db $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC
; Tile index $084
.db $00 $FF $FF $03 $00 $FF $FF $07 $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $1F
; Tile index $085
.db $00 $FF $FF $C0 $00 $FF $FF $F0 $00 $FF $FF $F8 $00 $FF $FF $FC $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $086
.db $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $3F $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $03
; Tile index $087
.db $00 $FF $FF $80 $00 $FF $FF $C0 $00 $FF $FF $C0 $00 $FF $FF $E0 $00 $FF $FF $E0 $00 $FF $FF $E0 $00 $FF $FF $F0 $00 $FF $FF $F0
; Tile index $088
.db $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $07
; Tile index $089
.db $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F8
; Tile index $08A
.db $00 $FF $FF $3F $00 $FF $FF $3F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $08B
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $E0 $00 $FF $FF $F0
; Tile index $08C
.db $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $08D
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $3F $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $0F
; Tile index $08E
.db $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $FC $00 $FF $FF $FC $00 $FF $FF $FE $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $08F
.db $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $03
; Tile index $090
.db $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F8
; Tile index $091
.db $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $0F
; Tile index $092
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $C0 $00 $FF $FF $F0 $00 $FF $FF $F8 $00 $FF $FF $FE
; Tile index $093
.db $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $094
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $3F
; Tile index $095
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $03 $FC $FF $FF
; Tile index $096
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $38 $C7 $FF $FF $F8 $07 $FF $FF $FC $03 $FF $FF
; Tile index $097
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $03 $FC $FF $FF $0F $F0 $FF $FF $1F $E0 $FF $FF $3F $C0 $FF $FF
; Tile index $098
.db $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $FF $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $099
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $E0 $E0 $1F $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $09A
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $7F $FF $C0 $C0 $3F $FF $F0 $F0 $0F $FF $F8
; Tile index $09B
.db $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $01
; Tile index $09C
.db $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0
; Tile index $09D
.db $00 $FF $FF $0F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $3F $00 $FF $FF $3F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $FF
; Tile index $09E
.db $00 $FF $FF $80 $00 $FF $FF $E0 $00 $FF $FF $F0 $00 $FF $FF $FC $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $09F
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $FF $FF $F0 $00 $FF $FF $FC
; Tile index $0A0
.db $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $00
; Tile index $0A1
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FF $FF $03 $FC $FF $FF $07 $F8 $FF $FF
; Tile index $0A2
.db $07 $F8 $FF $FF $0F $F0 $FF $FF $3F $C0 $FF $FF $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A3
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A4
.db $F8 $07 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A5
.db $00 $FF $FF $00 $00 $FF $FF $80 $80 $7F $FF $C0 $C0 $3F $FF $F0 $F0 $0F $FF $F8 $F8 $07 $FF $FC $FC $03 $FF $FF $FF $00 $FF $FF
; Tile index $0A6
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF $FF
; Tile index $0A7
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $01 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $07
; Tile index $0A8
.db $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F0 $00 $FF $FF $E0 $00 $FF $FF $C0 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $0A9
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $9F $00 $FF $FF $83 $00 $FF $FF $00
; Tile index $0AA
.db $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $C0 $00 $FF $FF $F0 $00 $FF $FF $F8 $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $0AB
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0
; Tile index $0AC
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FE $FF $03 $03 $FC $FF $07
; Tile index $0AD
.db $0F $F0 $FF $7F $1F $E0 $FF $7F $1F $E0 $FF $3F $3F $C0 $FF $7F $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AE
.db $80 $7F $FF $FF $C0 $3F $FF $FF $F0 $0F $FF $FF $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AF
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $E0 $1F $FF $FF $F8 $07 $FF $FF $FE $01 $FF $FF $FF $00 $FF $FF
; Tile index $0B0
.db $00 $FF $FF $07 $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $1F $00 $FF $FF $3F $00 $FF $FF $3F
; Tile index $0B1
.db $00 $FF $FF $FE $00 $FF $FF $FC $00 $FF $FF $F8 $00 $FF $FF $F8 $00 $FF $FF $F0 $00 $FF $FF $E0 $00 $FF $FF $C0 $00 $FF $FF $C0
; Tile index $0B2
.db $00 $FF $FF $1F $00 $FF $FF $07 $00 $FF $FF $01 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01
; Tile index $0B3
.db $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FF $FF $07 $F8 $FF $3F $1F $E0 $FF $3F $3F $C0 $FF $7F $7F $80 $FF $FF $FF $00 $FF $FF
; Tile index $0B4
.db $00 $FF $FF $FF $00 $FF $FF $FF $80 $7F $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B5
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $80 $7F $FF $FF $F8 $07 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B6
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $F8 $07 $FF $FF $FC $03 $FF $FF $FF $00 $FF $FF
; Tile index $0B7
.db $00 $FF $FF $E0 $00 $FF $FF $F8 $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $0B8
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $FF $FF $E0 $00 $FF $FF $F8 $00 $FF $FF $FC
; Tile index $0B9
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FE $FF $03 $03 $FC $FF $07 $07 $F8 $FF $1F
; Tile index $0BA
.db $07 $F8 $FF $0F $0F $F0 $FF $1F $1F $E0 $FF $3F $3F $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BB
.db $C0 $3F $FF $F0 $E0 $1F $FF $F8 $F8 $07 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BC
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $C0 $3F $FF $F1 $F0 $0F $FF $FD $FC $03 $FF $FF $FF $00 $FF $FF
; Tile index $0BD
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FF $FF $FC $00 $FF $FF $F8 $00 $FF $FF $F0 $00 $FF $FF $F0
; Tile index $0BE
.db $01 $FE $FF $03 $03 $FC $FF $07 $07 $F8 $FF $0F $07 $F8 $FF $0F $0F $F0 $FF $1F $1F $E0 $FF $3F $3F $C0 $FF $7F $3F $C0 $FF $7F
; Tile index $0BF
.db $80 $7F $FF $FF $C0 $3F $FF $FF $F0 $0F $FF $FF $F8 $07 $FF $FF $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C0
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $1F $E0 $FF $FF
; Tile index $0C1
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FF $FF $03 $FC $FF $FF $07 $F8 $FF $FF $1F $E0 $FF $FF $FF $00 $FF $FF
; Tile index $0C2
.db $1F $E0 $FF $3F $3F $C0 $FF $FF $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C3
.db $C0 $3F $FF $FF $E0 $1F $FF $FF $F8 $07 $FF $FF $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C4
.db $00 $FF $FF $E0 $00 $FF $FF $E0 $00 $FF $FF $C0 $00 $FF $FF $C0 $C0 $3F $FF $F8 $F8 $07 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF
; Tile index $0C5
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $83
; Tile index $0C6
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FF $FF $07 $00 $FF $FF $1F $00 $FF $FF $7F $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $0C7
.db $00 $FF $FF $00 $00 $FF $FF $01 $00 $FF $FF $01 $01 $FE $FF $03 $03 $FC $FF $07 $03 $FC $FF $07 $03 $FC $FF $07 $07 $F8 $FF $0F
; Tile index $0C8
.db $3F $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C9
.db $F0 $0F $FF $FF $FC $03 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CA
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $80 $7F $FF $FF $C0 $3F $FF $FF $FC $03 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CB
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $80 $7F $FF $FF $FF $00 $FF $FF
; Tile index $0CC
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FF $FF $07 $F8 $FF $FF $7F $80 $FF $FF $FF $00 $FF $FF
; Tile index $0CD
.db $00 $FF $FF $FF $03 $FC $FF $FF $0F $F0 $FF $FF $3F $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0CE
.db $80 $7F $FF $CF $C0 $3F $FF $FF $E0 $1F $FF $FF $F0 $0F $FF $FF $F8 $07 $FF $FF $FC $03 $FF $FF $FC $03 $FF $FF $FE $01 $FF $FF
; Tile index $0CF
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC
; Tile index $0D0
.db $0F $F0 $FF $1F $1F $E0 $FF $3F $1F $E0 $FF $3F $3F $C0 $FF $3F $3F $C0 $FF $7F $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF
; Tile index $0D1
.db $80 $7F $FF $F8 $F8 $07 $FF $FC $FC $03 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0D2
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $0D3
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
