; Tile index $060
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $061
.db $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF
; Tile index $062
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $063
.db $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF
; Tile index $064
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F8 $F8 $F8 $07 $C7 $C7
; Tile index $065
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $00 $20 $DF $DF $DF
; Tile index $066
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $1F $1F $1F $E0 $E1 $E1
; Tile index $067
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FE $F9 $00 $F8 $F8 $E7 $00 $E0
; Tile index $068
.db $FF $FE $01 $FF $FF $FC $00 $FC $FC $F3 $00 $F0 $F0 $CF $00 $C0 $C0 $3F $00 $00 $00 $FF $00 $00 $03 $FC $00 $00 $0F $F1 $01 $00
; Tile index $069
.db $C0 $3F $30 $30 $00 $FF $C0 $C0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $7C $83 $00 $00 $FE $7D $7C $00 $FF $FE $FE $00
; Tile index $06A
.db $10 $EF $20 $20 $08 $F7 $10 $10 $06 $F9 $08 $08 $01 $FE $06 $06 $00 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $06B
.db $01 $FE $1E $1E $00 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $40 $BF $80 $80 $20 $DF $40 $40 $10 $EF $20 $20
; Tile index $06C
.db $FF $00 $3F $3F $3F $C0 $C7 $C7 $07 $F8 $38 $38 $00 $FF $07 $07 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $06D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F $7F $80 $BF $BF $7F $80 $BF $BF $3F $C0 $5F $5F $3F $C0 $5F $5F
; Tile index $06E
.db $FF $03 $FC $FF $FF $03 $FC $FF $FF $00 $FC $FC $FC $03 $F8 $F8 $F8 $07 $F0 $F0 $F0 $0F $C0 $C0 $C1 $3E $80 $80 $83 $7D $01 $00
; Tile index $06F
.db $E0 $DF $00 $C0 $C0 $3F $00 $00 $01 $FE $00 $00 $07 $F9 $01 $00 $1F $E3 $03 $00 $7F $8F $0F $00 $FF $7F $7F $00 $FF $FF $FF $00
; Tile index $070
.db $3F $C7 $07 $00 $7F $9F $1F $00 $FF $7F $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $071
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $072
.db $80 $7F $00 $00 $C0 $BF $80 $00 $E0 $DF $C0 $00 $F0 $EF $E0 $00 $F8 $F7 $F0 $00 $FC $FB $F8 $00 $FE $FD $FC $00 $FF $FE $FE $00
; Tile index $073
.db $08 $F7 $10 $10 $08 $F7 $10 $10 $04 $FB $08 $08 $02 $FD $04 $04 $02 $FD $04 $04 $01 $FE $02 $02 $00 $FF $01 $01 $00 $FF $00 $00
; Tile index $074
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $40 $BF $80 $80
; Tile index $075
.db $3F $C0 $5F $5F $1F $E0 $2F $2F $1F $E0 $2F $2F $0F $F0 $17 $17 $0F $F0 $17 $17 $07 $F8 $0B $0B $07 $F8 $0B $0B $07 $F8 $0A $0A
; Tile index $076
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F3 $F3 $FF $00 $CD $CD $FF $00 $BE $BE $FF $00 $7E $7E $FF $00 $FF $FF
; Tile index $077
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F
; Tile index $078
.db $FF $00 $FC $FC $FC $03 $F8 $F8 $F8 $07 $F0 $F0 $F0 $0F $E0 $E0 $F3 $0C $E0 $E0 $E7 $19 $C1 $C0 $EF $13 $C3 $C0 $EB $17 $C7 $C0
; Tile index $079
.db $0F $F3 $03 $00 $3F $CF $0F $00 $7F $BF $3F $00 $FF $7F $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $07A
.db $FF $FE $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $07B
.db $00 $FF $00 $00 $80 $7F $00 $00 $C0 $BF $80 $00 $C0 $BF $80 $00 $E0 $DF $C0 $00 $F0 $EF $E0 $00 $F0 $EF $E0 $00 $F8 $F7 $F0 $00
; Tile index $07C
.db $40 $BF $80 $80 $20 $DF $40 $40 $10 $EF $20 $20 $10 $EF $20 $20 $08 $F7 $10 $10 $08 $F7 $10 $10 $04 $FB $08 $08 $02 $FD $04 $04
; Tile index $07D
.db $03 $FC $05 $05 $03 $FC $05 $05 $03 $FC $05 $05 $03 $FC $05 $05 $03 $FC $05 $05 $03 $FC $05 $05 $03 $FC $05 $05 $03 $FC $05 $05
; Tile index $07E
.db $FF $00 $7F $7F $FF $00 $BF $BF $FF $00 $BF $BF $FF $00 $BF $BF $FF $00 $DF $DF $FF $00 $DE $DE $FF $00 $ED $ED $FF $00 $E3 $E3
; Tile index $07F
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $E3 $E3 $FF $00 $99 $99 $FF $00 $7E $7E $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $080
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F $FF $00 $BF $BF
; Tile index $081
.db $EB $17 $C7 $C0 $EB $17 $C7 $C0 $EB $17 $C7 $C0 $EB $17 $C7 $C0 $EB $17 $C7 $C0 $EB $17 $C7 $C0 $F5 $0B $E3 $E0 $F5 $0B $E3 $E0
; Tile index $082
.db $F8 $F7 $F0 $00 $F8 $F7 $F0 $00 $FC $FB $F8 $00 $FC $FB $F8 $00 $FC $FB $F8 $00 $FE $FD $FC $00 $FE $FD $FC $00 $FE $FD $FC $00
; Tile index $083
.db $02 $FD $04 $04 $01 $FE $02 $02 $01 $FE $02 $02 $00 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $084
.db $03 $FC $05 $05 $03 $FC $05 $05 $03 $FC $05 $05 $83 $7C $05 $05 $47 $B8 $8B $8B $47 $B8 $8B $8B $4F $B0 $97 $97 $3F $C0 $4F $4F
; Tile index $085
.db $FF $00 $C4 $C4 $FE $01 $F9 $F9 $FC $03 $F8 $F8 $F8 $07 $F0 $F0 $F0 $0F $E0 $E0 $F8 $07 $F0 $F0 $FE $01 $F8 $F8 $FF $00 $FE $FE
; Tile index $086
.db $FF $00 $7F $7F $FF $00 $7F $7F $7F $80 $BF $BF $3F $C0 $5F $5F $3F $C0 $5F $5F $3F $C0 $4F $4F $7F $80 $37 $37 $FF $00 $3B $3B
; Tile index $087
.db $F5 $0B $E3 $E0 $F5 $0B $E3 $E0 $F2 $0D $E1 $E0 $FA $05 $F1 $F0 $FA $05 $F1 $F0 $F9 $06 $F0 $F0 $FD $02 $F8 $F8 $FD $02 $F8 $F8
; Tile index $088
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $FF $FF $00 $7F $FF $FF $00 $7F $FF $FF $00
; Tile index $089
.db $FE $FD $FC $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FF $FF $00 $FD $FE $FE $00
; Tile index $08A
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $81 $7E $00 $00 $83 $7C $01 $01 $87 $78 $03 $03 $0F $F0 $07 $07
; Tile index $08B
.db $1F $E0 $2F $2F $3F $C0 $5F $5F $7F $80 $BF $BF $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08C
.db $FF $00 $DF $DF $FF $00 $EF $EF $FF $00 $F7 $F7 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08D
.db $FC $03 $F8 $F8 $FE $01 $FC $FC $FE $01 $FC $FC $FE $01 $FC $FC $FF $00 $FE $FE $FF $00 $FE $FE $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08E
.db $BF $7F $7F $00 $BF $7F $7F $00 $4F $BF $3F $00 $4F $BF $3F $00 $27 $DF $1F $00 $27 $DF $1F $00 $91 $6F $0F $00 $89 $77 $07 $00
; Tile index $08F
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FC $FF $FF $00 $F1 $FE $FE $00
; Tile index $090
.db $F9 $FE $FE $00 $F2 $FD $FC $00 $E4 $FB $F8 $00 $C8 $F7 $F0 $00 $91 $EE $E0 $00 $63 $9C $81 $01 $87 $78 $03 $03 $0F $F0 $07 $07
; Tile index $091
.db $1F $E0 $0F $0F $3F $C0 $1F $1F $7F $80 $3F $3F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $092
.db $C4 $3B $83 $80 $E6 $19 $C1 $C0 $E3 $1C $C0 $C0 $F0 $0F $E0 $E0 $F8 $07 $F0 $F0 $FC $03 $F8 $F8 $FC $03 $F8 $F8 $FE $01 $FC $FC
; Tile index $093
.db $7F $FF $FF $00 $3F $FF $FF $00 $1F $FF $FF $00 $8F $7F $7F $00 $87 $7F $7F $00 $40 $BF $3F $00 $30 $CF $0F $00 $08 $F7 $07 $00
; Tile index $094
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FC $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $095
.db $FF $FF $FF $00 $FF $FF $FF $00 $F8 $FF $FF $00 $F0 $FF $FF $00 $83 $FC $FC $00 $0C $F3 $F0 $00 $30 $CF $C0 $00 $C0 $3F $00 $00
; Tile index $096
.db $C6 $F9 $F8 $00 $08 $F7 $F0 $00 $30 $CF $C0 $00 $C1 $3E $00 $00 $07 $F8 $01 $01 $0F $F0 $07 $07 $3F $C0 $0F $0F $7F $80 $3F $3F
; Tile index $097
.db $3F $C0 $0F $0F $7F $80 $3F $3F $FF $00 $7F $7F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $098
.db $FF $02 $FC $FE $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF
; Tile index $099
.db $04 $FB $03 $00 $83 $7C $00 $00 $C0 $BF $00 $80 $F0 $CF $00 $C0 $FC $F3 $00 $F0 $FF $FC $00 $FC $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $09A
.db $03 $FC $FC $00 $FC $03 $00 $00 $00 $FF $00 $00 $03 $FC $00 $00 $7F $82 $01 $03 $FF $7E $01 $7F $FF $FE $01 $FF $FF $FE $01 $FF
; Tile index $09B
.db $01 $FE $00 $00 $0F $F0 $01 $01 $3F $C0 $0F $0F $FF $00 $3F $3F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $09C
.db $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $00 $F8 $F8 $FF $00 $C0 $C0 $FF $00 $E0 $E0
; Tile index $09D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $C0 $00 $C0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $09E
.db $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $09F
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A0
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F $FF $00 $1F $1F $FF $00 $07 $07 $FF $00 $07 $07
; Tile index $0A1
.db $FF $00 $F0 $F0 $FF $02 $FC $FE $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $03 $FC $FF
; Tile index $0A2
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $E0 $00 $E0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A3
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FE $01 $FF
; Tile index $0A4
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $0F $0F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A5
.db $FF $00 $0F $0F $FF $00 $3F $3F $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
