; Tile index $060
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $061
.db $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF
; Tile index $062
.db $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $063
.db $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF
; Tile index $064
.db $DF $FF $DF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $065
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FE
; Tile index $066
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $FF $3F $FF $3F $FF $3F
; Tile index $067
.db $FF $FE $FF $FE $FF $FE $FF $FE $FF $FC $FF $FC $FF $FD $FF $FD $FF $FB $FF $FB $FF $F7 $FF $F7 $FF $EF $FF $EF $FF $DF $FF $DF
; Tile index $068
.db $FF $BF $FF $BF $FF $7F $FF $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $069
.db $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FF $01 $FE $01 $FE $03 $FD $03 $FD $05 $FB $05 $FB $09 $F7 $09 $F7 $09 $F7 $09 $F7
; Tile index $06A
.db $FF $BF $FF $BF $FF $BF $FF $BF $FF $7F $FF $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FC $FF $FA $FF $FA $FF $F8 $FF $F8 $FF $FB $FF $FB $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06C
.db $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $07 $FC $07 $FF $F8 $FF $F8 $FC $FF $FC $FF $FC $FF $FC $FF
; Tile index $06D
.db $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $81 $7E $81 $7E $79 $86 $79 $86 $00 $FF $00 $FF
; Tile index $06E
.db $11 $EF $11 $EF $21 $DF $21 $DF $41 $BF $41 $BF $40 $BE $41 $BE $81 $79 $87 $79 $81 $77 $89 $77 $01 $CF $31 $CF $00 $38 $C7 $38
; Tile index $06F
.db $FF $FF $FF $FF $EF $EF $FF $EF $8F $8F $FF $8F $7F $7F $FF $7F $FC $FC $FF $FC $E0 $E0 $FF $E0 $09 $09 $FF $09 $87 $87 $FF $07
; Tile index $070
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $87 $87 $FF $87 $13 $13 $FF $13 $29 $29 $FF $29 $99 $99 $FF $99 $34 $34 $FF $34
; Tile index $071
.db $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FC $FF $FC $F8 $F8 $FF $F8 $FC $FC $FF $FC
; Tile index $072
.db $00 $FC $03 $FC $00 $FB $04 $FB $00 $E4 $1B $E4 $01 $81 $7F $80 $03 $43 $BF $40 $07 $87 $7F $80 $1F $1F $FF $00 $7F $7F $FF $00
; Tile index $073
.db $01 $E1 $1F $E0 $0F $0F $FF $00 $7C $7C $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $074
.db $8E $8E $FF $0E $9C $9C $FF $1C $0E $0E $FF $0E $C4 $C4 $FF $04 $E1 $E1 $FF $01 $E2 $E2 $FF $02 $F0 $F0 $FF $00 $F5 $F5 $FF $05
; Tile index $075
.db $66 $66 $FF $66 $88 $88 $FF $88 $53 $53 $FF $53 $A6 $A6 $FF $A6 $4D $4D $FF $4D $1B $1B $FF $1B $42 $42 $FF $42 $95 $95 $FF $95
; Tile index $076
.db $7F $7F $FF $7F $7F $7F $FF $7F $3F $3F $FF $3F $3F $3F $FF $3F $BF $BF $FF $BF $1F $1F $FF $1F $DF $DF $FF $DF $8F $8F $FF $8F
; Tile index $077
.db $F9 $F9 $FF $F8 $F3 $F3 $FF $F0 $E7 $E7 $FF $E0 $EF $EF $FF $E0 $E7 $E7 $FF $E0 $EF $EF $FF $E0 $EF $EF $FF $E0 $EF $EF $FF $E0
; Tile index $078
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $079
.db $F2 $F2 $FF $02 $FA $FA $FF $02 $F8 $F8 $FF $00 $FD $FD $FF $01 $FD $FD $FF $01 $FC $FC $FF $00 $FE $FE $FF $00 $FE $FE $FF $00
; Tile index $07A
.db $23 $23 $FF $23 $46 $46 $FF $46 $09 $09 $FF $09 $25 $25 $FF $25 $0A $0A $FF $0A $94 $94 $FF $94 $81 $81 $FF $81 $4A $4A $FF $4A
; Tile index $07B
.db $6F $6F $FF $6F $CF $CF $FF $CF $B7 $B7 $FF $B7 $27 $27 $FF $27 $47 $47 $FF $47 $9B $9B $FF $9B $33 $33 $FF $33 $A9 $A9 $FF $A9
; Tile index $07C
.db $EF $EF $FF $E0 $EF $EF $FF $E0 $EF $EF $FF $E0 $E7 $E7 $FF $E0 $E7 $E7 $FF $E0 $EB $EB $FF $E8 $EB $EB $FF $E8 $F3 $F3 $FF $F0
; Tile index $07D
.db $45 $45 $FF $45 $22 $22 $FF $22 $A5 $A5 $FF $25 $80 $80 $FF $00 $90 $90 $FF $10 $C0 $C0 $FF $00 $C1 $C1 $FF $01 $E0 $E0 $FF $00
; Tile index $07E
.db $59 $59 $FF $59 $94 $94 $FF $94 $04 $04 $FF $04 $2C $2C $FF $2C $58 $58 $FF $58 $A6 $A6 $FF $A6 $4C $4C $FF $4C $19 $19 $FF $19
; Tile index $07F
.db $F5 $F5 $FF $F4 $F5 $F5 $FF $F4 $F4 $F6 $FD $F6 $F8 $FA $FD $FA $F8 $FB $FC $FB $F8 $FB $FC $FB $FC $FD $FE $FD $FC $FD $FE $FD
; Tile index $080
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $7F $FF $00 $7F $7F $FF $00 $3F $BF $7F $80 $3F $BF $7F $80
; Tile index $081
.db $E0 $E0 $FF $00 $F1 $F1 $FF $01 $F8 $F8 $FF $00 $F1 $F1 $FF $01 $E8 $E8 $FF $08 $DD $DD $FF $1D $B3 $B3 $FF $33 $6F $6F $FF $6F
; Tile index $082
.db $B3 $B3 $FF $B3 $4F $4F $FF $4F $1F $1F $FF $1F $BF $BF $FF $BF $7F $7F $FF $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $083
.db $FC $FE $FD $FE $FC $FE $FD $FE $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF $FC $FF
; Tile index $084
.db $1F $DF $3F $C0 $1F $DF $3F $C0 $0F $6F $9F $60 $07 $27 $DF $20 $07 $37 $CF $30 $07 $F7 $0F $F0 $00 $E0 $1F $E0 $00 $F8 $07 $F8
; Tile index $085
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FC $FC $FF $00 $F8 $F8 $FF $00 $01 $07 $F9 $07 $01 $1F $E1 $1F
; Tile index $086
.db $FC $FC $FF $00 $F8 $F8 $FF $00 $E3 $E3 $FF $03 $0F $0F $FF $0F $3F $3F $FF $3F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $087
.db $9F $9F $FF $9F $7F $7F $FF $7F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $088
.db $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $01 $FE $00 $FE $03 $FC $00 $FC $03 $FC $00 $FC $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $089
.db $01 $FF $01 $FF $0F $F0 $00 $F0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $0F $F0 $00 $F0 $01 $FF $01 $FF
; Tile index $08A
.db $FF $FF $FF $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $03 $03 $03 $FF $FF $FF $FF
; Tile index $08B
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F $FF $0F $0F $0F $FF $07 $07 $07 $FF $7F $7F $7F $FF $FF $FF $FF $FF $FF $FF $FF
