; Tile index $060
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $061
.db $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF
; Tile index $062
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $063
.db $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF
; Tile index $064
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $02 $00 $FD $FD $0C $00 $F3 $F3
; Tile index $065
.db $00 $00 $FF $FF $0C $00 $F3 $F3 $1E $00 $E1 $E1 $3E $00 $C1 $C1 $40 $00 $BF $BF $80 $00 $7F $7F $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $066
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FE $02 $00 $FD $FD $04 $00 $FB $FB $08 $00 $F7 $F7
; Tile index $067
.db $00 $00 $FF $FF $00 $00 $FF $FF $0E $00 $F1 $F1 $1E $00 $E1 $E1 $1F $00 $E0 $E0 $0C $00 $F3 $F3 $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $068
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $F0 $00 $0F $0F $0F $00 $F0 $F0 $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $069
.db $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $83 $03 $7C $7F $73 $03 $8C $8F $0F $03 $F0 $F3
; Tile index $06A
.db $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FF $FE $00 $FE $FE $FC $01 $FD
; Tile index $06B
.db $10 $00 $EF $EF $10 $00 $EF $EF $20 $00 $DF $DF $40 $00 $BF $BF $80 $00 $7F $7F $80 $00 $7F $7F $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $06C
.db $03 $00 $FC $FC $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF
; Tile index $06D
.db $FF $FF $00 $FF $FF $3F $00 $3F $FF $CF $00 $CF $FF $F7 $00 $F7 $FF $F9 $00 $F9 $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $06E
.db $FE $FC $01 $FD $FE $FA $01 $FB $FE $FA $01 $FB $FE $F6 $01 $F7 $FE $EE $01 $EF $FE $EE $01 $EF $FE $6E $01 $6F $FE $6E $01 $6F
; Tile index $06F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $07 $00 $F8 $F8 $38 $07 $C7 $C7
; Tile index $070
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $00 $00 $20 $DF $DF $DF
; Tile index $071
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $E0 $00 $1F $1F $1E $E0 $E1 $E1
; Tile index $072
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FE $F9 $00 $F8 $F8 $E7 $00 $E0
; Tile index $073
.db $FE $AC $01 $AD $FF $C8 $00 $C8 $FC $E3 $00 $E0 $F0 $CF $00 $C0 $C0 $3F $00 $00 $00 $FF $00 $00 $03 $FC $00 $00 $0F $F1 $01 $00
; Tile index $074
.db $C0 $3F $30 $30 $00 $FF $C0 $C0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $7C $83 $00 $00 $FE $7D $7C $00 $FF $FE $FE $00
; Tile index $075
.db $10 $EF $20 $20 $08 $F7 $10 $10 $06 $F9 $08 $08 $01 $FE $06 $06 $00 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $076
.db $01 $FE $1E $1E $00 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $40 $BF $80 $80 $20 $DF $40 $40 $10 $EF $20 $20
; Tile index $077
.db $C0 $00 $3F $3F $38 $C0 $C7 $C7 $07 $F8 $38 $38 $00 $FF $07 $07 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $078
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $7F $7F $40 $80 $BF $BF $40 $80 $BF $BF $20 $C0 $5F $5F $20 $C0 $5F $5F
; Tile index $079
.db $03 $03 $FC $FF $03 $03 $FC $FF $03 $00 $FC $FC $04 $03 $F8 $F8 $08 $07 $F0 $F0 $30 $0F $C0 $C0 $41 $3E $80 $80 $83 $7D $01 $00
; Tile index $07A
.db $E0 $DF $00 $C0 $C0 $3F $00 $00 $01 $FE $00 $00 $07 $F9 $01 $00 $1F $E3 $03 $00 $7F $8F $0F $00 $FF $7F $7F $00 $FF $FF $FF $00
; Tile index $07B
.db $3F $C7 $07 $00 $7F $9F $1F $00 $FF $7F $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $07C
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $07D
.db $80 $7F $00 $00 $C0 $BF $80 $00 $E0 $DF $C0 $00 $F0 $EF $E0 $00 $F8 $F7 $F0 $00 $FC $FB $F8 $00 $FE $FD $FC $00 $FF $FE $FE $00
; Tile index $07E
.db $08 $F7 $10 $10 $08 $F7 $10 $10 $04 $FB $08 $08 $02 $FD $04 $04 $02 $FD $04 $04 $01 $FE $02 $02 $00 $FF $01 $01 $00 $FF $00 $00
; Tile index $07F
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00 $40 $BF $80 $80
; Tile index $080
.db $20 $C0 $5F $5F $10 $E0 $2F $2F $10 $E0 $2F $2F $08 $F0 $17 $17 $08 $F0 $17 $17 $04 $F8 $0B $0B $04 $F8 $0B $0B $05 $F8 $0A $0A
; Tile index $081
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $0C $00 $F3 $F3 $32 $00 $CD $CD $41 $00 $BE $BE $81 $00 $7E $7E $00 $00 $FF $FF
; Tile index $082
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $7F $7F
; Tile index $083
.db $03 $00 $FC $FC $04 $03 $F8 $F8 $08 $07 $F0 $F0 $10 $0F $E0 $E0 $13 $0C $E0 $E0 $27 $19 $C1 $C0 $2F $13 $C3 $C0 $2B $17 $C7 $C0
; Tile index $084
.db $0F $F3 $03 $00 $3F $CF $0F $00 $7F $BF $3F $00 $FF $7F $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $085
.db $FF $FE $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $086
.db $00 $FF $00 $00 $80 $7F $00 $00 $C0 $BF $80 $00 $C0 $BF $80 $00 $E0 $DF $C0 $00 $F0 $EF $E0 $00 $F0 $EF $E0 $00 $F8 $F7 $F0 $00
; Tile index $087
.db $40 $BF $80 $80 $20 $DF $40 $40 $10 $EF $20 $20 $10 $EF $20 $20 $08 $F7 $10 $10 $08 $F7 $10 $10 $04 $FB $08 $08 $02 $FD $04 $04
; Tile index $088
.db $02 $FC $05 $05 $02 $FC $05 $05 $02 $FC $05 $05 $02 $FC $05 $05 $02 $FC $05 $05 $02 $FC $05 $05 $02 $FC $05 $05 $02 $FC $05 $05
; Tile index $089
.db $80 $00 $7F $7F $40 $00 $BF $BF $40 $00 $BF $BF $40 $00 $BF $BF $20 $00 $DF $DF $21 $00 $DE $DE $12 $00 $ED $ED $1C $00 $E3 $E3
; Tile index $08A
.db $00 $00 $FF $FF $00 $00 $FF $FF $1C $00 $E3 $E3 $66 $00 $99 $99 $81 $00 $7E $7E $01 $00 $FE $FE $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $08B
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $7F $7F $40 $00 $BF $BF
; Tile index $08C
.db $2B $17 $C7 $C0 $2B $17 $C7 $C0 $2B $17 $C7 $C0 $2B $17 $C7 $C0 $2B $17 $C7 $C0 $2B $17 $C7 $C0 $15 $0B $E3 $E0 $15 $0B $E3 $E0
; Tile index $08D
.db $F8 $F7 $F0 $00 $F8 $F7 $F0 $00 $FC $FB $F8 $00 $FC $FB $F8 $00 $FC $FB $F8 $00 $FE $FD $FC $00 $FE $FD $FC $00 $FE $FD $FC $00
; Tile index $08E
.db $02 $FD $04 $04 $01 $FE $02 $02 $01 $FE $02 $02 $00 $FF $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $08F
.db $02 $FC $05 $05 $02 $FC $05 $05 $02 $FC $05 $05 $82 $7C $05 $05 $44 $B8 $8B $8B $44 $B8 $8B $8B $48 $B0 $97 $97 $30 $C0 $4F $4F
; Tile index $090
.db $3B $00 $C4 $C4 $06 $01 $F9 $F9 $04 $03 $F8 $F8 $08 $07 $F0 $F0 $10 $0F $E0 $E0 $08 $07 $F0 $F0 $06 $01 $F8 $F8 $01 $00 $FE $FE
; Tile index $091
.db $80 $00 $7F $7F $80 $00 $7F $7F $40 $80 $BF $BF $20 $C0 $5F $5F $20 $C0 $5F $5F $30 $C0 $4F $4F $48 $80 $37 $37 $C4 $00 $3B $3B
; Tile index $092
.db $15 $0B $E3 $E0 $15 $0B $E3 $E0 $12 $0D $E1 $E0 $0A $05 $F1 $F0 $0A $05 $F1 $F0 $09 $06 $F0 $F0 $05 $02 $F8 $F8 $05 $02 $F8 $F8
; Tile index $093
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $FF $FF $00 $7F $FF $FF $00 $7F $FF $FF $00
; Tile index $094
.db $FE $FD $FC $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FF $FF $00 $FD $FE $FE $00
; Tile index $095
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $81 $7E $00 $00 $82 $7C $01 $01 $84 $78 $03 $03 $08 $F0 $07 $07
; Tile index $096
.db $10 $E0 $2F $2F $20 $C0 $5F $5F $40 $80 $BF $BF $80 $00 $7F $7F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $097
.db $20 $00 $DF $DF $10 $00 $EF $EF $08 $00 $F7 $F7 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $098
.db $04 $03 $F8 $F8 $02 $01 $FC $FC $02 $01 $FC $FC $02 $01 $FC $FC $01 $00 $FE $FE $01 $00 $FE $FE $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $099
.db $BF $7F $7F $00 $BF $7F $7F $00 $4F $BF $3F $00 $4F $BF $3F $00 $27 $DF $1F $00 $23 $DF $1F $00 $91 $6F $0F $00 $88 $77 $07 $00
; Tile index $09A
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FF $FF $00 $F8 $FF $FF $00 $E1 $FE $FE $00
; Tile index $09B
.db $F9 $FE $FE $00 $F2 $FD $FC $00 $E4 $FB $F8 $00 $C8 $F7 $F0 $00 $11 $EE $E0 $00 $62 $9C $81 $01 $84 $78 $03 $03 $08 $F0 $07 $07
; Tile index $09C
.db $10 $E0 $0F $0F $20 $C0 $1F $1F $40 $80 $3F $3F $80 $00 $7F $7F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $09D
.db $44 $3B $83 $80 $26 $19 $C1 $C0 $23 $1C $C0 $C0 $10 $0F $E0 $E0 $08 $07 $F0 $F0 $04 $03 $F8 $F8 $04 $03 $F8 $F8 $02 $01 $FC $FC
; Tile index $09E
.db $7F $FF $FF $00 $3F $FF $FF $00 $0F $FF $FF $00 $80 $7F $7F $00 $80 $7F $7F $00 $40 $BF $3F $00 $30 $CF $0F $00 $08 $F7 $07 $00
; Tile index $09F
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $0A0
.db $FF $FF $FF $00 $FE $FF $FF $00 $C0 $FF $FF $00 $00 $FF $FF $00 $03 $FC $FC $00 $0C $F3 $F0 $00 $30 $CF $C0 $00 $C0 $3F $00 $00
; Tile index $0A1
.db $86 $F9 $F8 $00 $08 $F7 $F0 $00 $30 $CF $C0 $00 $C1 $3E $00 $00 $06 $F8 $01 $01 $08 $F0 $07 $07 $30 $C0 $0F $0F $40 $80 $3F $3F
; Tile index $0A2
.db $30 $C0 $0F $0F $40 $80 $3F $3F $80 $00 $7F $7F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $0A3
.db $03 $02 $FC $FE $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF
; Tile index $0A4
.db $04 $FB $03 $00 $83 $7C $00 $00 $C0 $BF $00 $80 $F0 $CF $00 $C0 $FC $F3 $00 $F0 $FF $FC $00 $FC $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A5
.db $03 $FC $FC $00 $FC $03 $00 $00 $00 $FF $00 $00 $03 $FC $00 $00 $7E $82 $01 $03 $FE $7E $01 $7F $FE $FE $01 $FF $FE $FE $01 $FF
; Tile index $0A6
.db $01 $FE $00 $00 $0E $F0 $01 $01 $30 $C0 $0F $0F $C0 $00 $3F $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $0A7
.db $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $07 $00 $F8 $F8 $3F $00 $C0 $C0 $1F $00 $E0 $E0
; Tile index $0A8
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $C0 $00 $C0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A9
.db $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0AA
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0AB
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $7F $7F $E0 $00 $1F $1F $F8 $00 $07 $07 $F8 $00 $07 $07
; Tile index $0AC
.db $0F $00 $F0 $F0 $03 $02 $FC $FE $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF $03 $03 $FC $FF
; Tile index $0AD
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $E0 $00 $E0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AE
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF
; Tile index $0AF
.db $FF $00 $00 $00 $FF $00 $00 $00 $F0 $00 $0F $0F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $0B0
.db $F0 $00 $0F $0F $C0 $00 $3F $3F $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
