; Tile index $060
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $061
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $062
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FF $FF $FF $F8 $FF $FF $FF $F0 $FF $FF $FF $E0
; Tile index $063
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $E0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $064
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $03 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $065
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $066
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $067
.db $FF $FF $FF $FF $FF $FF $FF $E1 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $068
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $FF $FF $FF $3F $FF $FF $FF $07 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $069
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $9F $FF $FF $FF $03 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $06A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $FF $FF $FF $1F
; Tile index $06B
.db $FF $FF $FF $C0 $FF $FF $FF $C0 $FF $FF $FF $C0 $FF $FF $FF $E0 $FF $FF $FF $F0 $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06C
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $06D
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $80 $FF $FF $FF $C0
; Tile index $06E
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $06F
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $03 $FF $FF $FF $3F
; Tile index $070
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FF $FF $FF $07 $FF $FF $FF $3F $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $071
.db $FF $FF $FF $1F $FF $FF $FF $3F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F0 $FF $FF $FF $80
; Tile index $072
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $07 $FF $FF $FF $07
; Tile index $073
.db $FF $FF $FF $F8 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $074
.db $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $075
.db $FF $FF $FF $07 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $076
.db $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $077
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $078
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FC $FF $FF $FF $F0 $FF $FF $FF $E0 $FF $FF $FF $E0
; Tile index $079
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $07A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $BF $FF $FF $FF $37
; Tile index $07B
.db $FF $FF $FF $E0 $FF $FF $FF $F0 $FF $FF $FF $F0 $FF $FF $FF $F8 $FF $FF $FF $FC $FF $FF $FF $F8 $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $07C
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $07D
.db $FF $FF $FF $60 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $07E
.db $FF $FF $FF $3F $FF $FF $FF $1C $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $07F
.db $FF $FF $FF $FF $FF $FF $FF $0F $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01
; Tile index $080
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $FF $FF $FF $3F $FF $FF $FF $7F $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $081
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FC $FF $FF $FF $FE $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $082
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FF $FF $FF $87 $FF $FF $FF $FF
; Tile index $083
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $F0 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $084
.db $FF $FF $FF $07 $FF $FF $FF $0F $FF $FF $FF $1F $FF $FF $FF $3F $FF $FF $FF $3F $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $085
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $EF $EF $EF
; Tile index $086
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $CF $CF $CF $DF $A7 $A7 $87 $DF $B7 $B7 $87 $9F $77 $77 $07
; Tile index $087
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F0 $F0 $F0 $F0 $EF $EF $EF $E0 $DF $C0 $C0 $C3 $BC $80 $80
; Tile index $088
.db $FF $E7 $E7 $E7 $FF $EB $EB $E3 $F7 $EC $EC $E0 $FB $F7 $F7 $F0 $FF $11 $11 $10 $1C $E3 $E3 $E3 $E0 $1F $02 $02 $F8 $C7 $C0 $00
; Tile index $089
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $30 $30 $30 $F0 $0F $00 $00 $0E $F1 $F0 $F0 $00 $FF $0E $0E $00 $FF $00 $00
; Tile index $08A
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $08B
.db $FF $FE $FE $FE $FE $FD $FD $FC $FC $03 $03 $00 $07 $F8 $F8 $F8 $00 $FF $07 $07 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $08C
.db $1F $F7 $F7 $07 $3F $EF $EF $0F $3F $EF $EF $0F $BF $6F $6F $0F $BF $6C $6C $0C $3C $E3 $E3 $C3 $D8 $27 $00 $00 $03 $FC $40 $40
; Tile index $08D
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $C3 $C3 $C3 $C3 $3C $3C $3C $00 $FF $C3 $C3 $7C $83 $00 $00 $FE $39 $38 $00
; Tile index $08E
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $7F $BF $BF $BF $3F $DF $5F $5F $3F $DF $5F $5F
; Tile index $08F
.db $FF $FF $FF $FF $FF $FE $FE $FE $FF $FE $FE $FE $FE $FD $FC $FC $FE $FD $FC $FC $FC $FB $F8 $F8 $FC $FB $F8 $F8 $FC $FB $F8 $F8
; Tile index $090
.db $8F $73 $03 $00 $1F $EF $0F $00 $3F $D0 $10 $00 $3F $C1 $01 $00 $7F $80 $00 $00 $7F $80 $00 $00 $7F $80 $00 $00 $FF $00 $00 $00
; Tile index $091
.db $F8 $F7 $F0 $00 $FC $F3 $F0 $00 $FC $33 $30 $00 $F8 $17 $10 $00 $F0 $0F $00 $00 $E0 $1F $00 $00 $C0 $3F $00 $00 $80 $7F $00 $00
; Tile index $092
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $01 $FE $00 $00 $06 $F9 $01 $00 $19 $E7 $07 $00 $7E $81 $01 $00 $FE $01 $01 $00
; Tile index $093
.db $00 $FF $00 $00 $07 $F8 $00 $00 $3F $C7 $07 $00 $FF $3E $3E $00 $FF $FE $FE $00 $FF $FC $FC $00 $FF $FC $FC $00 $FF $FC $FC $00
; Tile index $094
.db $00 $FF $00 $00 $FE $01 $00 $00 $F9 $06 $06 $00 $FD $03 $03 $00 $FE $01 $01 $00 $FE $01 $01 $00 $FE $01 $01 $00 $FE $01 $01 $00
; Tile index $095
.db $00 $FF $00 $00 $00 $FF $00 $00 $C0 $3F $00 $00 $F0 $CF $C0 $00 $F8 $F7 $F0 $00 $FE $F9 $F8 $00 $FF $F8 $F8 $00 $FF $F8 $F8 $00
; Tile index $096
.db $07 $F9 $09 $08 $0F $F0 $10 $10 $1F $E0 $20 $20 $1F $E0 $20 $20 $1F $E0 $20 $20 $0F $F0 $10 $10 $07 $F8 $00 $00 $03 $FC $00 $00
; Tile index $097
.db $FE $FD $FC $00 $FF $1E $1E $00 $FF $0E $0E $00 $FF $4F $4F $00 $FF $06 $06 $00 $FF $06 $06 $00 $FF $06 $06 $00 $FF $06 $06 $00
; Tile index $098
.db $1F $EF $2F $2F $1F $EF $2F $2F $1F $EF $2F $2F $9F $6F $2F $2F $9F $6F $2F $2F $1F $EF $2F $2F $1F $EF $2F $2F $1F $FF $1F $1F
; Tile index $099
.db $FC $FB $F9 $F9 $FC $FB $F9 $F9 $FC $FB $F9 $F9 $FC $FB $F8 $F8 $FC $FB $F8 $F8 $FC $FB $F8 $F8 $FC $FB $F8 $F8 $FC $FB $F8 $F8
; Tile index $09A
.db $FF $00 $00 $00 $FE $01 $00 $00 $FC $03 $00 $00 $7C $A3 $A0 $80 $78 $B7 $B0 $80 $30 $CF $40 $40 $30 $CF $40 $40 $20 $DF $50 $50
; Tile index $09B
.db $01 $FE $00 $00 $07 $F8 $00 $00 $0F $F6 $06 $00 $1F $EE $0E $00 $3F $DE $1E $00 $5F $BE $3E $00 $DF $3E $3E $00 $BF $7E $7E $00
; Tile index $09C
.db $FE $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $09D
.db $FF $FC $FC $00 $7F $FC $FC $00 $7F $FC $FC $00 $7F $FC $FC $00 $BF $7C $7C $00 $B3 $7C $7C $00 $CF $30 $30 $00 $FF $00 $00 $00
; Tile index $09E
.db $FE $01 $01 $00 $FE $01 $01 $00 $FE $01 $01 $00 $FE $01 $01 $00 $FE $01 $01 $00 $FE $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $09F
.db $FF $F8 $F8 $00 $FF $F8 $F8 $00 $FF $F8 $F8 $00 $FF $F8 $F8 $00 $FF $F8 $F8 $00 $FF $F0 $F0 $00 $1F $E0 $E0 $00 $FF $00 $00 $00
; Tile index $0A0
.db $83 $7C $00 $00 $C0 $3F $00 $00 $E0 $1F $00 $00 $E0 $1F $00 $00 $F0 $2F $20 $00 $F0 $2F $20 $00 $F8 $37 $30 $00 $F8 $77 $70 $00
; Tile index $0A1
.db $FE $05 $04 $00 $FE $1D $1C $00 $7C $9B $18 $00 $78 $B7 $30 $00 $78 $A7 $20 $00 $31 $CE $00 $00 $03 $FC $00 $00 $06 $F9 $01 $01
; Tile index $0A2
.db $3F $DF $1F $1F $7F $BF $3F $3F $7F $BF $3F $3F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $3F $3F $3F $FF $3F $3F $3F
; Tile index $0A3
.db $FF $FC $FC $FC $FF $F8 $F8 $F8 $FB $F4 $F0 $F0 $FB $F4 $F0 $F0 $F1 $EE $E0 $E0 $F1 $EE $E0 $E0 $F1 $EE $E0 $E0 $F1 $EE $E0 $E0
; Tile index $0A4
.db $01 $FE $20 $20 $01 $FE $00 $00 $03 $FC $00 $00 $03 $FC $00 $00 $03 $FC $00 $00 $83 $7C $00 $00 $83 $7C $00 $00 $47 $B8 $00 $00
; Tile index $0A5
.db $BF $7E $7E $00 $BF $7E $7E $00 $BF $7E $7E $00 $DF $3E $3E $00 $DF $3E $3E $00 $E1 $1E $1E $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A6
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0A7
.db $FC $7B $78 $00 $FC $7B $78 $00 $FC $7B $78 $00 $FC $73 $70 $00 $FC $F3 $F0 $00 $FE $F1 $F0 $00 $FE $E1 $E0 $00 $FF $00 $00 $00
; Tile index $0A8
.db $06 $F9 $00 $00 $04 $FB $00 $00 $09 $F6 $00 $00 $0F $F1 $01 $01 $0F $F0 $00 $00 $1C $E3 $00 $00 $1D $E2 $00 $00 $EF $11 $00 $01
; Tile index $0A9
.db $7F $BF $BF $BF $FF $7F $7F $7F $FF $FF $FF $FF $FF $C0 $C0 $C0 $C0 $3F $00 $00 $7F $80 $00 $00 $FF $7F $00 $7F $FF $FF $00 $FF
; Tile index $0AA
.db $FF $FE $FE $FE $FE $E1 $E1 $E1 $FC $03 $00 $00 $20 $DF $40 $40 $40 $BF $80 $80 $FF $00 $00 $00 $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AB
.db $FF $0F $0F $0F $0F $F3 $F3 $F3 $03 $FD $0D $0D $0F $F0 $00 $00 $09 $F6 $02 $02 $82 $7D $04 $04 $F4 $0B $08 $08 $FE $F1 $00 $F0
; Tile index $0AC
.db $FF $FF $FF $FF $FF $F0 $F0 $F0 $F9 $E6 $E6 $E6 $EF $10 $10 $10 $80 $7F $6F $6F $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0AD
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $00 $80 $7F $7F $7F $30 $CF $40 $40 $3C $C3 $80 $80 $0B $F4 $14 $14 $08 $F7 $13 $13
; Tile index $0AE
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $1F $E0 $E0 $E0 $00 $FF $1F $1F $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00
; Tile index $0AF
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $7F $BF $BF $BF $3F $DF $5F $5F $1F $EF $2F $2F $0F $F7 $17 $17
; Tile index $0B0
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FE $FE $FE $FE $FD $FC $FC
; Tile index $0B1
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $F8 $F8 $F8 $C7 $C0 $C0 $C0 $3F $00 $00 $00 $FF $00 $00
; Tile index $0B2
.db $F3 $EC $E0 $E0 $FF $F0 $F0 $F0 $FF $F0 $F0 $F0 $F0 $8F $80 $80 $80 $7F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B3
.db $A7 $58 $08 $08 $E7 $18 $08 $08 $A7 $58 $08 $08 $A7 $58 $08 $08 $67 $98 $08 $08 $47 $B8 $08 $08 $47 $B8 $08 $08 $47 $B8 $08 $08
; Tile index $0B4
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $00 $FF $01 $01 $00
; Tile index $0B5
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $C0 $C0 $00 $FF $E0 $E0 $00
; Tile index $0B6
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $1C $1C $00
; Tile index $0B7
.db $FF $00 $00 $00 $FE $01 $00 $00 $FE $01 $00 $00 $FE $01 $00 $00 $FF $00 $00 $00 $FF $03 $00 $03 $FF $0F $00 $0F $FF $3F $00 $3F
; Tile index $0B8
.db $9F $63 $00 $03 $1F $EF $00 $0F $7F $9F $00 $1F $7F $FF $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0B9
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0BA
.db $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0BB
.db $C0 $3F $00 $00 $E0 $DF $00 $C0 $F8 $E7 $00 $E0 $FE $F9 $00 $F8 $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0BC
.db $0A $F5 $10 $10 $0D $F2 $10 $10 $0E $F1 $10 $10 $1D $E2 $00 $00 $8B $74 $10 $10 $EE $91 $10 $90 $FC $E3 $00 $E0 $FF $F8 $00 $F8
; Tile index $0BD
.db $7C $83 $80 $80 $C2 $3D $3C $3C $81 $7E $02 $02 $80 $7F $01 $01 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $80 $7F $00 $00
; Tile index $0BE
.db $0F $F7 $17 $17 $0F $F7 $17 $17 $8F $77 $17 $17 $4F $B7 $97 $97 $6F $97 $97 $97 $3F $C7 $47 $47 $1F $E7 $27 $27 $1F $E7 $27 $27
; Tile index $0BF
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $F8 $F8 $F8
; Tile index $0C0
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $01 $01 $01
; Tile index $0C1
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $E6 $E6 $E6 $E7 $18 $00 $00 $06 $F9 $00 $00 $00 $FF $00 $00
; Tile index $0C2
.db $FC $E3 $E0 $E0 $E0 $DF $C0 $C0 $C0 $BF $80 $80 $80 $7F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0C3
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0C4
.db $47 $B8 $08 $08 $43 $BC $04 $04 $43 $BC $04 $04 $43 $BC $04 $04 $23 $DC $04 $04 $23 $DC $04 $04 $23 $DC $04 $04 $33 $CC $04 $04
; Tile index $0C5
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $00 $FF $01 $01 $00 $FD $03 $03 $00
; Tile index $0C6
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $E0 $E0 $00 $FF $E0 $E0 $00 $FF $F0 $F0 $00 $FF $F1 $F0 $01
; Tile index $0C7
.db $FF $01 $01 $00 $FF $C0 $C0 $00 $FF $C1 $C0 $01 $FF $C7 $C0 $07 $7F $BF $80 $3F $FF $7F $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0C8
.db $FF $C0 $C0 $00 $FF $3E $00 $3E $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0C9
.db $FF $1E $1E $00 $FF $01 $00 $01 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0CA
.db $E0 $9F $00 $80 $FC $F3 $00 $F0 $FF $FC $00 $FC $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0CB
.db $1F $E7 $27 $27 $1F $E8 $28 $28 $FF $07 $00 $07 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0CC
.db $FF $07 $00 $07 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0CD
.db $FF $1F $1F $1F $FF $E1 $01 $E1 $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0CE
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $1F $1F $1F $FF $E1 $01 $E1 $FF $FE $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0CF
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $7F $7F $7F $FF $8F $0F $8F $FF $F1 $01 $F1 $FF $FE $00 $FE
; Tile index $0D0
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $3F $3F $3F
; Tile index $0D1
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D2
.db $FC $FB $F8 $F8 $F8 $F7 $F0 $F0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D3
.db $00 $FF $00 $00 $00 $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D4
.db $13 $EC $04 $04 $1B $E4 $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D5
.db $FC $03 $03 $00 $FF $00 $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D6
.db $1F $E7 $E0 $07 $FF $1F $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D7
.db $FF $FF $00 $FF $FF $FF $00 $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0D8
.db $FF $C3 $03 $C3 $FF $FD $01 $01 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
