; Tile index $060
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $061
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $062
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $00 $FF $FF $0C $00 $FF $FF $0C $00 $FF $FF $08 $00 $FF $FF
; Tile index $063
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $00 $FF $FF $03 $00 $FF $FF $02 $00 $FF $FF
; Tile index $064
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $00 $FF $FF $0F $00 $FF $FF $FF $00 $FF $FF
; Tile index $065
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $E0 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $066
.db $00 $00 $FF $FF $01 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $01 $00 $FF $FF $03 $00 $FF $FF $9F $00 $FF $FF $FF $00 $FF $FF
; Tile index $067
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $9F $00 $FF $FF $FF $00 $FF $FF
; Tile index $068
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $069
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $F8 $00 $FF $FF $FF $00 $FF $FF
; Tile index $06A
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF
; Tile index $06B
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $07 $00 $FF $FF
; Tile index $06C
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FF $FF $DF $00 $FF $FF $FF $00 $FF $FF
; Tile index $06D
.db $00 $00 $FF $FF $40 $00 $FF $FF $E0 $00 $FF $FF $E4 $00 $FF $FF $EC $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $06E
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $06F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $FF
; Tile index $070
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $00 $FF $FF $1C $00 $FF $FF $0C $00 $FF $FF $0C $00 $FF $FF $04 $00 $FF $FF
; Tile index $071
.db $18 $00 $FF $FF $0C $00 $FF $FF $0C $00 $FF $FF $3E $00 $FF $FF $7F $00 $FF $FF $1B $00 $FF $FF $7B $00 $FF $FF $3A $00 $FF $FF
; Tile index $072
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $073
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $00 $FF $FF $30 $00 $FF $FF $59 $00 $FF $FF $E9 $00 $FF $FF $F9 $00 $FF $FF
; Tile index $074
.db $40 $00 $FF $FF $60 $00 $FF $FF $60 $00 $FF $FF $E0 $00 $FF $FF $60 $00 $FF $FF $E0 $00 $FF $FF $F0 $00 $FF $FF $FF $00 $FF $FF
; Tile index $075
.db $0D $00 $FF $FF $0F $00 $FF $FF $01 $00 $FF $FF $03 $00 $FF $FF $0F $00 $FF $FF $07 $00 $FF $FF $0B $00 $FF $FF $0F $00 $FF $FF
; Tile index $076
.db $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $02 $00 $FF $FF $83 $00 $FF $FF $43 $00 $FF $FF $C7 $00 $FF $FF $0F $00 $FF $FF
; Tile index $077
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF
; Tile index $078
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $7F $00 $FF $FF
; Tile index $079
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $00 $FF $FF $10 $00 $FF $FF $D8 $00 $FF $FF
; Tile index $07A
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $0C $00 $F3 $F3 $12 $0C $ED $E1
; Tile index $07B
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $C0 $C0 $D0 $0E $BF $80 $FC $02 $7F $00 $4D $02 $FF $00 $5E $00 $FF $00
; Tile index $07C
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $61 $61 $61 $00 $9E $00 $00 $00 $FF $00 $70 $0F $FF $00 $7E $01 $FF $00
; Tile index $07D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F8 $F8 $FC $00 $C7 $C0 $FC $03 $3F $00 $3E $01 $FF $00 $3F $00 $FF $00 $3F $00 $FF $00
; Tile index $07E
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $07 $07 $3F $00 $F8 $00 $62 $80 $FF $00 $4E $81 $FF $00 $8E $01 $FF $00
; Tile index $07F
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $63 $63 $63 $00 $9C $00 $00 $0C $FF $00 $3C $82 $FF $00
; Tile index $080
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $9F $9F $9F $00 $6F $0F $0F $00 $F7 $07 $8F $40 $F1 $01
; Tile index $081
.db $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $3C $C3 $FF $FF $FF $00 $FF
; Tile index $082
.db $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $F7 $08 $FF
; Tile index $083
.db $3F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $084
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $085
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $C3 $C3 $C3 $38 $BD $81
; Tile index $086
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $C1 $C1 $E3 $1C $BC $80 $FC $02 $7F $00
; Tile index $087
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $23 $23
; Tile index $088
.db $FD $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $089
.db $80 $00 $FF $FF $70 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08A
.db $01 $00 $FF $FF $3F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $7C $83 $FF
; Tile index $08B
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $60 $9F $FF
; Tile index $08C
.db $18 $00 $FF $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $01 $FE $FF $FF $0F $F0 $FF
; Tile index $08D
.db $00 $00 $FF $FF $30 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $C0 $3F $FF $FF $E0 $1F $FF $FF $F0 $0F $FF
; Tile index $08E
.db $2F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08F
.db $9F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $090
.db $C0 $00 $FF $FF $C0 $00 $FF $FF $FD $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $091
.db $00 $00 $FF $FF $00 $00 $FF $FF $FB $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $07 $F8 $FF $FF $7F $80 $FF $FF $7F $80 $FF
; Tile index $092
.db $0F $00 $FF $FF $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $03 $FC $FF $FF $E7 $18 $FF $FF $FE $00 $FE $FF $FC $01 $FC
; Tile index $093
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $C0 $31 $F1 $F9 $E6 $0E $E0 $FE $C1 $1F $C0 $FE $01 $1F $00 $BF $40 $DF $00
; Tile index $094
.db $F8 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FE $FF $00 $FD $FC $FE $01 $7D $7C $FF $38 $43 $78 $7E $80 $87 $00
; Tile index $095
.db $3A $04 $CD $C1 $7D $02 $BE $80 $FE $01 $7F $00 $EF $10 $7F $00 $F7 $08 $FF $00 $FF $00 $FF $00 $4F $80 $FF $00 $04 $00 $FF $00
; Tile index $096
.db $E1 $1E $FF $00 $FE $01 $FF $00 $FF $00 $FF $00 $FE $00 $FF $00 $78 $00 $FF $00 $1F $00 $E0 $1F $7F $00 $80 $7F $FF $00 $00 $FF
; Tile index $097
.db $FE $00 $FF $00 $7F $00 $FF $00 $3B $00 $FF $00 $0B $00 $FF $00 $03 $00 $FF $00 $F9 $00 $07 $F8 $FE $00 $01 $FE $FF $00 $00 $FF
; Tile index $098
.db $3E $00 $FF $00 $81 $70 $FF $00 $F3 $08 $FF $00 $F3 $08 $FF $00 $F3 $00 $FF $00 $DF $00 $E0 $1F $3F $00 $C0 $3F $FF $00 $00 $FF
; Tile index $099
.db $0F $70 $FF $00 $F7 $08 $FF $00 $F3 $08 $FF $00 $FE $01 $FF $00 $F3 $00 $FF $00 $53 $00 $EF $10 $98 $00 $67 $98 $FF $00 $00 $FF
; Tile index $09A
.db $BE $40 $FF $00 $FC $00 $FF $00 $FD $02 $FF $00 $66 $01 $FF $00 $47 $80 $FF $00 $A7 $00 $DF $20 $7F $00 $80 $7F $FF $00 $00 $FF
; Tile index $09B
.db $C1 $30 $FE $00 $F0 $0C $FF $00 $FC $02 $FF $00 $5E $80 $FF $00 $9A $00 $FF $00 $8B $00 $FC $03 $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $09C
.db $FF $FF $00 $FF $FF $3F $00 $3F $3F $1F $C0 $1F $3F $1F $C0 $1F $3F $1F $C0 $1F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $09D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $09E
.db $FF $80 $7F $FF $FF $C0 $3F $FF $FF $F7 $08 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $09F
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $1E $E1 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A0
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $60 $9F $FF $FF $F0 $08 $F8 $F8 $F0 $07 $F0 $F4 $00 $0B $F4 $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A1
.db $FF $00 $E1 $E1 $F1 $08 $DE $C0 $F8 $04 $BF $80 $FF $00 $3F $00 $0E $00 $FF $00 $01 $00 $FE $01 $C7 $00 $38 $C7 $FF $00 $00 $FF
; Tile index $0A2
.db $F1 $08 $7E $00 $F8 $04 $FF $00 $F8 $00 $FF $00 $F3 $00 $FF $00 $7F $00 $FF $00 $57 $00 $EF $10 $FD $00 $07 $F8 $FF $00 $00 $FF
; Tile index $0A3
.db $FF $00 $FF $00 $F9 $06 $FF $00 $3E $01 $FF $00 $3F $80 $FF $00 $9F $40 $FF $00 $DC $00 $E3 $1C $FF $00 $80 $7F $FF $00 $00 $FF
; Tile index $0A4
.db $27 $18 $DB $03 $FB $04 $FC $00 $F0 $08 $FF $00 $72 $81 $FF $00 $9F $40 $FF $00 $7F $00 $87 $78 $FE $00 $01 $FE $FF $00 $00 $FF
; Tile index $0A5
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $1F $1F $1F $8F $E0 $0F $0F $C7 $F0 $07 $9F $40 $E0 $1F $3F $00 $C0 $3F $FF $00 $00 $FF
; Tile index $0A6
.db $FF $01 $FE $FF $FF $07 $F8 $FF $FF $1F $E0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A7
.db $FF $FA $05 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A8
.db $FF $00 $FF $FF $FF $80 $7F $FF $FF $80 $7F $FF $FF $F8 $07 $FF $FF $FD $02 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A9
.db $FF $00 $FF $FF $FF $07 $F8 $FF $FF $1F $E0 $FF $FF $3F $C0 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0AA
.db $FF $3F $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0AB
.db $FF $F8 $07 $FF $FF $FC $03 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0AC
.db $FF $00 $FF $FF $FF $38 $C7 $FF $FF $FD $02 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0AD
.db $FF $06 $F9 $FF $FF $07 $F8 $FF $FF $9F $60 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0AE
.db $FF $03 $FC $FF $FF $9F $60 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0AF
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FE $FE $FC $01 $FC $FC $F8 $03 $F8 $FC $00 $03 $FC $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B0
.db $FF $80 $41 $C0 $E0 $12 $9F $80 $E6 $11 $7F $00 $F7 $08 $FF $00 $F8 $00 $FF $00 $3F $00 $C0 $3F $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B1
.db $9B $04 $FF $00 $7D $02 $FF $00 $5E $00 $FF $00 $38 $00 $FF $00 $FD $00 $FF $00 $F9 $00 $07 $F8 $FF $00 $01 $FE $FD $00 $02 $FD
; Tile index $0B2
.db $8E $00 $FF $00 $FF $00 $FF $00 $E3 $10 $FF $00 $F1 $08 $FF $00 $B9 $44 $FF $00 $FC $00 $FF $00 $FE $00 $F1 $0E $FF $00 $00 $FF
; Tile index $0B3
.db $94 $08 $FF $00 $F8 $04 $FF $00 $FA $01 $FF $00 $83 $60 $FF $00 $E5 $12 $FF $00 $FE $01 $FF $00 $3E $01 $FF $00 $BF $00 $7F $80
; Tile index $0B4
.db $FF $00 $00 $FF $FF $00 $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0B5
.db $F8 $00 $07 $F8 $FF $00 $03 $FC $00 $FF $00 $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $0B6
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
