; Tile index $060
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $061
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E7 $18 $E7 $FF $DB $3C $C3 $E7
; Tile index $062
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FB $04 $FB $FF $F5 $0E $F1 $FB $EE $1F $E0 $F5
; Tile index $063
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $01 $FE $FF $FD $03 $FC $FE $FB $07 $F8 $FD $37 $CB $30 $F9
; Tile index $064
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $C0 $3F $FF $DF $E0 $1F $3F $EF $F0 $0F $DF $F4 $FB $04 $EF
; Tile index $065
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $CF $30 $CF $FF $37 $F8 $07 $CF
; Tile index $066
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $01 $FE $FF $FD $03 $FC $FE
; Tile index $067
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $BF $40 $BF $FF $5F $E0 $1F $BF $E8 $F7 $08 $5F
; Tile index $068
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $03 $FC $03 $FF $FD $FE $01 $03
; Tile index $069
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E3 $1C $E3 $FF $DC $3F $C0 $E3 $BF $7F $80 $DC $7F $FF $00 $BF
; Tile index $06A
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $80 $7F $FF $BE $C1 $3E $7F
; Tile index $06B
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $3F $C0 $3F $FF
; Tile index $06C
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $03 $FC $FF $FB $07 $F8 $FC
; Tile index $06D
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $80 $7F $FF
; Tile index $06E
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $03 $FC $FF $FB $07 $F8 $FC $F7 $0F $F0 $FB $EF $1F $E0 $F7 $DF $3F $C0 $EC
; Tile index $06F
.db $FF $00 $FF $FF $FF $00 $FF $FF $8F $70 $8F $FF $73 $FC $03 $8F $FD $FE $01 $73 $FE $FF $00 $FD $FF $FF $00 $FE $FF $FF $00 $1F
; Tile index $070
.db $FF $00 $FF $FF $FF $00 $FF $FF $FE $01 $FE $FF $FD $02 $FC $FE $FB $04 $F8 $FC $FB $04 $F8 $FC $7B $84 $78 $FC $BB $C4 $38 $7C
; Tile index $071
.db $BD $7E $81 $DB $7E $FF $00 $BD $FE $FF $00 $7D $FE $FF $00 $7D $FE $FF $00 $7D $FD $FE $01 $7B $FD $FE $01 $7B $FD $FE $01 $7B
; Tile index $072
.db $FF $00 $FF $FF $FF $00 $FF $FF $FE $01 $FE $FF $FD $03 $FC $FE $FB $07 $F8 $FD $F7 $0F $F0 $FB $EF $17 $E0 $F3 $DF $2F $C0 $E7
; Tile index $073
.db $FF $00 $FF $FF $81 $7E $81 $FF $7E $FF $00 $81 $FF $FF $00 $7E $FF $FF $00 $F3 $FF $F3 $00 $E1 $FF $F1 $00 $E0 $EF $F0 $00 $D0
; Tile index $074
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $80 $7F $FF $BF $C0 $3F $7F $DF $E0 $1F $BF $EF $F0 $0F $DF $F7 $F8 $07 $6F
; Tile index $075
.db $D7 $2F $C0 $EA $BB $47 $80 $C5 $DF $21 $C0 $E0 $EF $10 $E0 $F0 $F7 $0B $F0 $F8 $EF $1F $E0 $F3 $DF $3F $C0 $EF $BF $7F $80 $DC
; Tile index $076
.db $CF $F1 $00 $30 $FF $FF $00 $C0 $FF $FF $00 $3F $FF $3F $00 $00 $FF $C0 $00 $00 $FF $F0 $00 $C0 $FB $FC $00 $34 $F3 $3C $00 $0C
; Tile index $077
.db $F3 $FF $00 $EC $FF $FF $00 $63 $FF $FF $00 $FC $FF $FC $00 $60 $FF $F0 $00 $60 $F0 $FF $00 $6F $F7 $F8 $07 $6F $F7 $F8 $07 $6F
; Tile index $078
.db $F8 $FF $00 $37 $FF $FF $00 $C0 $FF $FF $00 $1E $FF $1F $00 $0E $FF $1F $00 $0F $7F $8F $00 $87 $7F $8F $00 $87 $BF $47 $80 $C3
; Tile index $079
.db $FB $07 $F8 $FD $77 $8F $70 $FB $6F $9F $60 $F7 $5F $BF $40 $EC $BF $FC $00 $58 $FC $FB $00 $33 $F1 $FE $00 $2E $F5 $FA $04 $6E
; Tile index $07A
.db $E7 $FF $00 $D8 $EF $FF $00 $D7 $DF $FF $00 $2F $BF $7F $00 $5C $7F $FC $00 $B8 $FC $7F $00 $3B $FB $FC $03 $77 $FB $FC $03 $77
; Tile index $07B
.db $FE $FF $00 $FD $FF $FF $00 $FE $FF $FF $00 $0F $FF $1F $00 $0F $FF $0F $00 $07 $7F $8F $00 $87 $BF $4F $80 $C7 $BF $4F $80 $C7
; Tile index $07C
.db $FE $01 $FE $FF $7D $83 $7C $FE $BB $C7 $38 $7D $D7 $EB $10 $B9 $EF $F3 $00 $D1 $EF $F1 $00 $D0 $EF $F0 $00 $D0 $E7 $F8 $00 $D8
; Tile index $07D
.db $FF $FF $00 $47 $FF $C7 $00 $83 $FF $C7 $00 $83 $9F $E3 $00 $61 $DF $E1 $00 $A0 $EF $F1 $00 $D0 $FF $F8 $00 $60 $FF $7E $00 $38
; Tile index $07E
.db $DD $E3 $1C $BE $DB $E7 $18 $BD $E7 $FB $00 $D9 $FF $F7 $00 $E3 $FF $F7 $00 $E3 $FF $FF $00 $F3 $FF $FF $00 $73 $FF $77 $00 $03
; Tile index $07F
.db $DF $E0 $1F $3F $EF $F0 $0F $DF $F7 $F8 $07 $EF $FB $FC $03 $F7 $FB $FC $03 $F7 $FA $FD $02 $F7 $F1 $FF $00 $EE $F3 $FD $00 $EC
; Tile index $080
.db $F7 $0F $F0 $FB $EF $1F $E0 $F7 $DF $2F $C0 $E7 $BF $47 $80 $C3 $7F $C7 $00 $83 $FF $E7 $00 $43 $FF $E7 $00 $C3 $FF $E7 $00 $C3
; Tile index $081
.db $BF $C0 $3F $7F $DF $E0 $1F $BF $EE $F1 $0E $DF $ED $F2 $0C $DE $F3 $FC $00 $EC $F3 $FC $00 $EC $F5 $FA $04 $EE $F6 $F9 $06 $EF
; Tile index $082
.db $BF $7C $80 $D0 $7F $F0 $00 $A0 $F0 $EF $00 $4F $F7 $F8 $07 $6F $EF $70 $0F $1F $DF $20 $1F $3F $BF $40 $3F $7F $00 $FF $00 $FF
; Tile index $083
.db $FF $3F $00 $1F $FF $1F $00 $0F $FF $1F $00 $0F $7F $9F $00 $8F $7F $9F $00 $8F $7F $9F $00 $8F $7F $9F $00 $8F $7F $9F $00 $8F
; Tile index $084
.db $BB $C4 $38 $7C $BB $C4 $38 $7C $BB $C4 $38 $7C $BB $C4 $38 $7C $BB $C4 $38 $7C $BB $C4 $38 $7C $BB $C4 $38 $7C $BB $C4 $38 $7C
; Tile index $085
.db $FD $FE $01 $7B $FB $FC $03 $77 $FB $FC $03 $77 $FB $FC $03 $77 $F8 $FF $00 $77 $F1 $FF $00 $6E $F7 $FF $00 $69 $FF $FF $00 $66
; Tile index $086
.db $FF $00 $FF $FF $FF $00 $FF $FF $F0 $0F $F0 $FF $8F $7F $80 $F0 $7F $FF $00 $8F $FF $FF $00 $78 $FF $F8 $00 $E0 $FF $E0 $00 $40
; Tile index $087
.db $FF $00 $FF $FF $FF $00 $FF $FF $03 $FC $03 $FF $FC $FF $00 $03 $FF $FF $00 $FC $FF $FF $00 $7F $FF $7F $00 $1F $FF $1F $00 $0F
; Tile index $088
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $80 $7F $FF $BF $C0 $3F $7F $C0 $FF $00 $BF $E7 $F8 $07 $DF $F0 $FF $00 $EF
; Tile index $089
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $FF $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08A
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $2F $D0 $2F $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $08B
.db $DF $2F $C0 $E7 $BF $47 $80 $C0 $BF $40 $80 $C0 $DE $21 $C0 $E1 $E0 $1F $E0 $FF $FD $03 $FC $FE $FB $07 $F8 $FD $F7 $0B $F0 $F9
; Tile index $08C
.db $D7 $E8 $10 $B8 $A3 $DF $20 $7C $1F $FF $00 $E3 $7F $FF $00 $9C $FF $FC $00 $60 $FF $E0 $00 $80 $F3 $8C $00 $0C $8C $F3 $0C $7F
; Tile index $08D
.db $F7 $F8 $07 $6F $FA $7D $02 $37 $FC $FF $00 $1B $FC $FF $00 $FB $FE $FF $00 $1D $FE $1F $00 $0D $FE $1F $00 $0D $7F $9F $00 $8E
; Tile index $08E
.db $7F $BE $00 $9C $FE $3F $00 $1D $FF $3F $00 $1C $FF $1F $00 $0F $FF $0F $00 $03 $7F $81 $00 $80 $3F $C0 $00 $C0 $8F $F8 $00 $70
; Tile index $08F
.db $EB $14 $08 $1C $DB $24 $18 $3C $1B $E4 $18 $FC $E3 $FC $00 $1C $FF $FC $00 $E0 $FF $FE $00 $7C $FF $7E $00 $3C $FF $3E $00 $1C
; Tile index $090
.db $F7 $F8 $07 $6F $F7 $F8 $07 $6F $F6 $F9 $06 $6F $F5 $FA $04 $6E $F3 $FC $00 $6C $FB $FD $00 $74 $FB $7D $00 $34 $FF $7B $00 $31
; Tile index $091
.db $BF $47 $80 $C3 $7F $FF $00 $83 $FF $FF $00 $7B $FF $FB $00 $71 $FF $FB $00 $71 $FF $F3 $00 $E1 $EF $F3 $00 $D1 $CF $F3 $00 $B1
; Tile index $092
.db $EB $F4 $08 $5C $EB $F4 $08 $DC $EB $F5 $08 $DC $DB $E5 $18 $BC $D7 $E9 $10 $B8 $D7 $E9 $10 $B8 $D7 $E9 $10 $B8 $D7 $E8 $10 $B8
; Tile index $093
.db $FB $FC $03 $77 $FB $FC $03 $77 $FB $FC $03 $F7 $FB $FC $03 $F7 $FB $FC $03 $F7 $FB $FC $03 $F7 $FD $FE $01 $FB $FD $FE $01 $7B
; Tile index $094
.db $BF $4F $80 $C7 $BF $4F $80 $C7 $BF $4F $80 $C7 $BF $4F $80 $C7 $BF $4F $80 $C7 $BF $4F $80 $C7 $BF $4F $80 $C6 $BE $4F $80 $C5
; Tile index $095
.db $EB $F4 $08 $DC $E9 $F6 $08 $DE $EB $F7 $08 $DC $C7 $FF $00 $BB $CF $FF $00 $B7 $9F $EF $00 $67 $3F $CF $00 $C7 $BF $4F $80 $C7
; Tile index $096
.db $FF $3F $00 $1E $FF $1F $00 $0F $FF $8F $00 $07 $FF $CF $00 $87 $FF $C7 $00 $83 $FF $C7 $00 $83 $DF $E7 $00 $A3 $DF $E7 $00 $A3
; Tile index $097
.db $FF $07 $00 $03 $DF $E7 $00 $23 $FF $E7 $00 $C3 $FF $F7 $00 $E3 $FF $F7 $00 $E3 $FF $FB $00 $F1 $FF $FB $00 $F1 $FF $FB $00 $F1
; Tile index $098
.db $E7 $FB $00 $D9 $E7 $FB $00 $D9 $EF $F7 $00 $D3 $EF $F7 $00 $D3 $DF $EF $00 $A7 $DF $EF $00 $A4 $DF $FE $00 $AC $FF $FC $00 $98
; Tile index $099
.db $FF $E3 $00 $C1 $FF $E3 $00 $C1 $EF $F3 $00 $D1 $EF $F3 $00 $D1 $EF $F3 $00 $D1 $EF $F3 $00 $51 $FF $F7 $00 $63 $FF $7F $00 $27
; Tile index $09A
.db $F6 $F9 $06 $EF $F1 $FF $00 $EE $F7 $FF $00 $E9 $EF $FF $00 $D7 $FF $FF $00 $CF $FF $FF $00 $CF $FF $FF $00 $CF $FF $DF $00 $8F
; Tile index $09B
.db $7F $FF $00 $80 $FF $FF $00 $7F $FF $FF $00 $F0 $FF $F0 $00 $C0 $FF $C0 $00 $80 $C3 $FC $00 $BC $D3 $EC $10 $BC $EF $FF $00 $D0
; Tile index $09C
.db $7F $9F $00 $8F $FF $FF $00 $0F $FF $FF $00 $EF $FF $FF $00 $6E $FF $FF $00 $7E $FF $FF $00 $7E $FF $FF $00 $7E $FF $FF $00 $EE
; Tile index $09D
.db $BB $C5 $38 $7C $BB $C5 $38 $7C $B7 $C9 $30 $78 $77 $89 $70 $F8 $77 $8B $70 $F9 $77 $8B $70 $F9 $6F $93 $60 $F1 $6F $97 $60 $F3
; Tile index $09E
.db $FF $FE $00 $E8 $FF $F8 $00 $F0 $F9 $F6 $00 $E6 $E6 $F9 $06 $DF $EF $F0 $0F $DF $DF $E0 $1F $BF $DF $E0 $1F $BF $BF $C0 $3F $7F
; Tile index $09F
.db $E1 $5E $00 $1E $9E $61 $1E $7F $7F $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A0
.db $FF $0F $00 $07 $7F $8F $00 $87 $BF $47 $80 $C3 $BF $47 $80 $C3 $DF $27 $C0 $E3 $DF $23 $C0 $E1 $DF $23 $C0 $E1 $EF $13 $E0 $F1
; Tile index $0A1
.db $F0 $FF $00 $FF $FD $FE $01 $FB $FD $FE $01 $FB $FE $FF $00 $FD $FE $FF $00 $FD $FE $FF $00 $FD $FE $FF $00 $FD $FD $FE $01 $FB
; Tile index $0A2
.db $00 $FF $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0A3
.db $EF $13 $E0 $F1 $EF $17 $E0 $F3 $EF $17 $E0 $F3 $DF $27 $C0 $E3 $DF $27 $C0 $E3 $DF $27 $C0 $E3 $DF $27 $C0 $E3 $DF $27 $C0 $E3
; Tile index $0A4
.db $BF $C0 $3F $7F $BF $C0 $3F $7F $BF $C0 $3F $7F $BF $C0 $3F $7F $DF $E0 $1F $BF $DC $E3 $1C $BF $E3 $FF $00 $DC $FF $FF $00 $E3
; Tile index $0A5
.db $7F $9F $00 $8F $7F $9F $00 $8F $7F $9F $00 $8F $7F $9F $00 $8C $7E $FD $00 $99 $FD $FA $01 $63 $F3 $EC $03 $CF $EF $D0 $0F $9F
; Tile index $0A6
.db $DD $FE $00 $AA $FC $DF $00 $8B $FD $9E $00 $0A $7F $9F $00 $88 $7F $8F $00 $87 $7F $87 $00 $82 $BF $42 $80 $C0 $DE $21 $C0 $E1
; Tile index $0A7
.db $FF $7E $00 $3C $FD $7E $00 $3A $F9 $FE $00 $76 $F6 $F9 $06 $6F $EF $F0 $0F $9F $DF $A0 $1F $3F $BF $40 $3F $7F $7F $80 $7F $FF
; Tile index $0A8
.db $FF $7F $00 $33 $FF $3F $00 $0E $FE $1F $00 $0D $FD $0E $01 $03 $7B $84 $03 $87 $B7 $48 $87 $CF $CF $30 $CF $FF $FF $00 $FF $FF
; Tile index $0A9
.db $AF $D3 $20 $71 $6F $91 $60 $F0 $EF $10 $E0 $F0 $F7 $08 $F0 $F8 $FA $05 $F8 $FD $FD $02 $FD $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AA
.db $D7 $E8 $10 $B8 $DB $E4 $18 $BC $BB $C4 $38 $7C $7D $82 $7C $FE $FE $01 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AB
.db $FC $FF $00 $7B $FF $7F $00 $38 $FF $3F $00 $1F $FF $1F $00 $00 $FF $00 $00 $00 $7F $80 $00 $80 $80 $7F $80 $FF $FF $00 $FF $FF
; Tile index $0AC
.db $3D $FE $01 $CB $FB $FC $03 $37 $F7 $F8 $07 $CF $EF $D0 $0F $1F $DF $20 $1F $3F $3F $C0 $3F $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0AD
.db $BF $47 $80 $C3 $BF $47 $80 $C3 $DF $23 $C0 $E1 $DF $23 $C0 $E1 $EF $11 $E0 $F0 $EF $10 $E0 $F0 $F7 $08 $F0 $F8 $F9 $06 $F8 $FE
; Tile index $0AE
.db $DF $E7 $00 $A3 $DF $E7 $00 $A3 $FF $FF $00 $C7 $FF $FF $00 $FC $FF $FC $00 $78 $FE $79 $00 $01 $F1 $0E $01 $0F $EF $10 $0F $1F
; Tile index $0AF
.db $FF $F3 $00 $E1 $EF $F3 $00 $D1 $CF $F1 $00 $B0 $AF $D0 $20 $70 $77 $88 $70 $F8 $FB $04 $F8 $FC $FC $03 $FC $FF $FF $00 $FF $FF
; Tile index $0B0
.db $FB $FC $00 $D4 $F5 $FA $04 $EE $ED $F2 $0C $DE $DE $E1 $1E $3F $BF $40 $3F $7F $7F $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B1
.db $FF $7F $00 $3F $FF $3F $00 $1F $FF $1F $00 $0E $FE $0F $00 $01 $7D $82 $01 $83 $BB $44 $83 $C7 $C7 $38 $C7 $FF $FF $00 $FF $FF
; Tile index $0B2
.db $FF $8F $00 $07 $FF $87 $00 $03 $3F $C3 $00 $C0 $5F $A0 $40 $E0 $EF $10 $E0 $F0 $F0 $0F $F0 $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B3
.db $FF $FF $00 $CF $FF $FF $00 $F0 $FF $F0 $00 $00 $FC $03 $00 $03 $C3 $3C $03 $3F $3F $C0 $3F $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0B4
.db $FF $FF $00 $0E $FE $0F $00 $05 $FE $0F $00 $05 $3E $CF $00 $C5 $BD $46 $81 $C3 $BB $44 $83 $C7 $D6 $29 $C6 $EF $EF $10 $EF $FF
; Tile index $0B5
.db $6F $97 $60 $F3 $DF $2F $C0 $E7 $DF $2F $C0 $E7 $BF $5F $80 $CF $BF $7F $80 $DF $7F $9F $00 $81 $FF $01 $00 $00 $7F $80 $00 $80
; Tile index $0B6
.db $BF $C0 $3F $7F $BF $C0 $3F $7F $BF $C0 $3F $7F $8F $F0 $0F $7F $F0 $FF $00 $8F $FF $FF $00 $F0 $FF $FF $00 $0F $FF $0F $00 $00
; Tile index $0B7
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $18 $E7 $18 $FF $E7 $FF $00 $18 $FF $FF $00 $E7 $FF $FF $00 $18
; Tile index $0B8
.db $EF $17 $E0 $F3 $CF $37 $C0 $F3 $DF $27 $C0 $E3 $DF $27 $C0 $E3 $1F $EF $00 $E7 $FF $FF $00 $0E $FF $FE $00 $F0 $FE $F1 $00 $01
; Tile index $0B9
.db $FD $FE $01 $FB $FB $FC $03 $F7 $F7 $F8 $07 $EF $EF $F0 $0F $DF $DF $E0 $1F $BF $BF $C0 $3F $7F $7F $80 $7F $FF $FF $00 $FF $FF
; Tile index $0BA
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $80 $7F $80 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BB
.db $FF $00 $FF $FF $F0 $0F $F0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $FF $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BC
.db $FF $00 $FF $FF $00 $FF $00 $FF $FE $01 $FE $FF $FF $00 $FF $FF $00 $FF $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0BD
.db $DF $27 $C0 $E3 $1F $E7 $00 $E3 $1F $E7 $00 $E3 $DF $23 $C0 $E1 $1F $E1 $00 $E0 $EF $10 $E0 $F0 $F7 $08 $F0 $F8 $F8 $07 $F8 $FF
; Tile index $0BE
.db $FF $FF $00 $FE $FF $FE $00 $FC $FE $FD $00 $F1 $F9 $F6 $01 $E7 $F7 $E8 $07 $0F $CF $30 $0F $3F $BF $40 $3F $7F $7F $80 $7F $FF
; Tile index $0BF
.db $9F $E0 $1F $7F $7F $80 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C0
.db $E9 $16 $E1 $F7 $F7 $08 $F7 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C1
.db $1F $E0 $1F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C2
.db $87 $78 $80 $F8 $F8 $07 $F8 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C3
.db $FF $00 $00 $00 $3F $C0 $00 $C0 $C0 $3F $C0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C4
.db $FF $18 $00 $00 $FF $00 $00 $00 $60 $9F $00 $9F $9F $60 $9F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $0C5
.db $F9 $06 $01 $07 $C7 $38 $07 $3F $3F $C0 $3F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
